// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_security_oauth2]]
= OAuth2 authentication

{product-name} can authenticate a user against an OAuth2/OIDC-compatible identity provider. OAuth2
providers can be configured alongside the usual form-based login. It is **not** compatible with the
<<sect_security_preauth,external pre-authentication>> and does not require setting the `auth.mode`
property.

The following example configuration declares an OAuth2 service connection named `inception-client`
which uses a Keycloak instance configured for OAuth2 running at 
`http://localhost:8180/realms/inception-demo`. The OAuth2 support of {product-name} should work with
any OAuth2/OIDC-compatible identity provider. For more details, please
refer to the link:https://docs.spring.io/spring-security/reference/servlet/oauth2/client/authorization-grants.html[Spring Security OAuth2 documentation].

.Example: Authenticate against a local Keycloak
----
spring.security.oauth2.client.registration.inception-client.client-name=Keycloak
spring.security.oauth2.client.registration.inception-client.client-id=inception-client
spring.security.oauth2.client.registration.inception-client.client-secret=ENCRYPTED_CLIENT_SECRET
spring.security.oauth2.client.registration.inception-client.scope=openid, profile
spring.security.oauth2.client.registration.inception-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.inception-client.redirect-uri=http://localhost:8080/login/oauth2/code/inception-client
spring.security.oauth2.client.provider.inception-client.issuer-uri=http://localhost:8180/realms/inception-demo 
spring.security.oauth2.client.provider.inception-client.user-name-attribute=preferred_username
----

NOTE: The following instructions run Keycloak in development mode. This is **not** meant for
      production, only for testing. For how to properly set up a production-level Keycloak server, please
      refer to the official documentation of Keycloak.

If you want to try this with a local testing instance of Keycloak, you can do this:

* Download link:https://www.keycloak.org[Keycloak]
* Run it using `./kc.sh start-dev --http-port 8180`
* Configure a new realm called `inception-demo`
* Define a new client `inception-client` and set the *Valid redirection URI* to `http://localhost:8080/login/oauth2/code/inception-client`.
* Replace the `ENCRYPTED_CLIENT_SECRET` in the example configuration above with the client secret from 
  the *Credentials* tab of the client in Keycloak.
* Add a new user in the *Manage users* area in Keycloak.

When you restart {product-name} and access the login page now, it should offer a login option called
*Keycloak*. You can change the label of that option by changing the 
`security.oauth2.client.registration.inception-client.client-name` setting.

== OAuth2 auto-login

When configuring the application for OAuth2, the user will still be required to choose an identity
provider via the login page (and is also given the opportunity to log in via form-based login there).

If you would like to automatically login through a particular OAuth2 identity provider, you
can configure this by setting the `security.auto-login` property to the registration ID of the
respective provider that you configured using the `spring.security.oauth2.client...` properties.

This setting is useful for single-sign-on scenarios where only a single identity provider is used.

[cols="4*", options="header"]
|===
| Setting
| Description
| Default
| Example
      
| `security.login.auto-login`
| Auto-login using given identity provider
| _<none>_
| `inception-client` (cf. example above)

|===

NOTE: In case it may be necessary to bypass the auto-login, e.g. to allow signing in via credentials,
      navigate to `.../login.html?skipAutoLogin=true`. Make sure to do this in a fresh browser session that is
      not yet logged into the application.
