// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_security_authentication]]
= Authentication

This section describes the different authentication mechanisms supported by {product-name}.

NOTE: A user can only log in through one mechanism, either as a local user or an external user.
      If you are using SAML/OAuth2, then the users are bound to one particular IdP. If a user with the same
      name tries to log in via another mechanism or IdP, the login will be rejected. If you plan to use
      multiple login mechanisms or IdPs at the same time, you must ensure that the user IDs are unique
      across all the mechanisms and IdPs or that a given user always uses the same login mechanism.
