// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_formats_pdf_legacy]]
= PDF Format (legacy)

====
CAUTION: Legacy feature. To use this functionality, you need to enable it first by adding `ui.pdf-legacy.enabled=true` to the `settings.properties` file. 

Support for this feature will be removed in a future version. The replacement is <<sect_formats_pdf>>.
====

This allows the import of PDF files. A PDF file can be viewed and annotated in its original form.
It is also possible to switch to another editor like the "brat" editor to annotate directly on the
text extracted from the PDF. The annotations made on PDF files can be exported again in other
formats (e.g. UIMA CAS XMI or UIMA CAS JSON), but not as PDF files.

This legacy PDF format support should no longer be used. It has known issues, in particular that
the creation of annotations in certain parts of a document may fail, that annotations disappear
from the PDF view after created (but still be visible in other editors), etc.

Unfortunately, there is no way to automatically migrate already annotated PDF files to the new PDF
editor which does not suffer from these problems. When importing new PDF documents, please ensure
to use the **PDF** and not the **PDF (legacy)** format. 

[cols="2,1,1,1,3"]
|====
| Format | Read | Write | Custom Layers | Description

| PDF (`pdf`)
| yes
| no
| n/a
| 
|====
