// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_formats_xml_custom]]
= XML (custom)

====
CAUTION: Experimental feature. To use this functionality, you need to enable it first by adding `format.custom-xml.enabled` to the `settings.properties` file.
====

Custom XML document support allows defining own XML annotation formats that can be displayed as formatted documents in HTML-based editors (e.g. the Apache Annotator editor or the RecogitoJS editor). Custom XML formats are based on the <<sect_formats_xml>> format support. They are defined by creating a sub-folder `xml-formats` in the application home direcotry. Within that folder, another folder is created for each custom XML format. The name of the folder is used as part of the format identifier. Within this per-format folder, a file called `plugin.json` need to be created with the following content:

.Example `plugin.json` for custom XML format
[source,json]
----
{
  "name": "XML dialog format (external)",
  "stylesheets": [ 
    "my-styles.css"
  ]
}
----

The `plugin.json` file should define one or more CSS stylesheets that define how elements of the custom XML format should be rendered on screen.

Additionally, a `policy.yaml` file should be present in the format folder. It defines how the elements of the XML should be handled when rendering the documents for display in the browser.

.Example `policy.yaml` for custom XML format
[source,yaml]
----
name: Transcription Content Policies
version: 1.0
policies:
  - { elements: [ "dialog", "turn" ], action: "PASS" }
  - { attributes: ["id", "speaker"], action: "PASS" }
----

An example XML file that could be imported with such a format would look like this:

.Example `dialog.xml` file
[source,json]
----
<dialog>
  <turn id="1" speaker="Mary">Hi, how are you?</turn>
  <turn id="2" speaker="Joe">I am fine, how are you?</turn>
</dialog>
----

NOTE: When exporting a project that contains documents using a custom XML format and importing 
      it into another {application-name} instance in which the format has not been declared, the custom 
      XML documents will not be usable. You will also have to copy the custom format declaration over
      to the new instance. If you use custom XML formats, make sure you keep backups of them
      along with the projects that use them. Also try to use names for your formats that are unlikely to
      clash with others. E.g. `tei` may not be the best name for a custom TEI format support -   
      `project-theater-2000-tei` may be a better name.¸

[cols="2,1,1,1,3"]
|====
| Format | Read | Write | Custom Layers | Description

| XML (custom) (`custom-xml-format-FOLDERNAME`)
| yes
| no
| no
| 
|====
