// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_formats_xml]]
= 🧪 XML (generic)

====
CAUTION: Experimental feature. To use this functionality, you need to enable it first by adding `format.generic-xml.enabled` to the `settings.properties` file.
====

Generic support for XML documents. This format imports the entire XML document structure and is
able to retain it until export. None of the XML elements are converted to editable annotations
though. In combination with a HTML-based editor, this format allows annotating in styled XML 
documents. Note that some XML elements and attributes are filtered out during rendering. These
include e.g. elements which in a HTML file would be JavaScript-related elements and attributes as
well as links which could easily interfere with the functionality of the annotation editor.

Note that when exporting a document in this format, you only recover the originally imported XML
document - no annotations will be included. If you want to export the annotated data, you should
use e.g. <<sect_formats_uimajson>>. 

[cols="2,1,1,3"]
|====
| Format | Import | Export | Supported layers

| XML (generic) (`dkpro-core-xml-document`)
| yes
| yes
| None
|====
