// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_formats_mhtml]]
= 🧪 MHTML (Web archive)

====
CAUTION: Experimental feature. To use this functionality, you need to enable it first by adding `format.mhtml.enabled=true` to the `settings.properties` file. In order to load images from MHTML files, it is currently also necessary to disable image blocking in the safety net using `ui.external.block-img=false` and set `ui.external.allow-img-source=LOCAL` - this will allow loading images
embedded into documents, but not to load images from remote servers.
====

link:https://en.wikipedia.org/wiki/MHTML[MHTML] is a format supported by many browsers which stores the website currently shown in the browser along with most resources required to display the page - including but not limited to images.

E.g. in Chrome, you may save a web page in this format using **Save as...** and then selecting the 
format **Web page, Single File**.

{product-name} will load the web page saved in this format, but it will not look like the original. You will notice that most of the styling will be gone. This usually leads to a lot of boiler plate being visible in particular at the start and end of the document, e.g. page navigation sections, sidebars, etc. which have been inlined into the document structure because they are missing their usual styles. However, other essential styling like paragraph, headings, figures, tables, etc. should mostly be preserved.

A special feature of the MHTML format is that it also allows images that were part of the original page to be displayed in {product-name}. Note that when saving a page, it is possible that the browser does not capture all the images into the MHTML file. {product-name} will only be able to display those images that are actually included.

[cols="2,1,1,3"]
|====
| Format | Import | Export | Supported layers

| MHTML (`hmtml`)
| yes
| no
| None
|====
