# Default values for inception.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/inception-project/inception
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "33.2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

networkPolicies:
  enabled: true

config:
  baseUrl: "/"
  logging: TRACE

  security:
    acceptedOrigins: "localhost"
    allowHttp: true

  database:
    name: "inception"
    hostname: ""
    port: 3306
    useSSL: false
    serverTimezone: "UTC"
    auth: 
      username: "inception"
      password:
        value: "Gre@tPwd465!*"
        existingSecret:
          secretName: ""
          secretKey: ""

  extraConfig:
    config.key: config-value

auth:
  oauth2:
    enabled: false
    autoLogin: true 
    clientName: Keycloak OIDC
    clientID: inception-local-oidc
    clientSecret: 
      value: "Tn6yHpQ9kik6BFZPGXxTvqBJiQ54TxwS"
      existingSecret: 
        secretName: ""
        secretKey: ""
    scope: openid, profile
    authorizationGrantType: authorization_code
    redirectURI: http://localhost/login/oauth2/code/inception-client
    issuerURI: https://auth.workshop.eds-ovh.org/realms/datalab-workshop
    userNameAttribute: preferred_username

  saml2:
    enabled: true
    autoLogin: true
    signRequest: 
      enabled: false
      certificateValue:
      privateKeyValue:  
      existingTlsSecret: ""
    assertingPartyCertificate:
      value: |
        -----BEGIN CERTIFICATE-----
        MIICrzCCAZcCBgGLfUUjxjANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQDDBBkYXRhbGFiLXdvcmtzaG9wMB4XDTIzMTAyOTIxMDc0NVoXDTMzMTAyOTIxMDkyNVowGzEZMBcGA1UEAwwQZGF0YWxhYi13b3Jrc2hvcDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAN4crtQpxQom2Mj8RipMZnrB/Fkt2GIID1tg+3OeFhUWkAyRwD8HYeLsW3hfv0XJj6vUSqGTGh7KYq2nLhYHNeOVOG3sdujZeBjxhdoV0zfQaVK+R/9BdKlWKRpqx1DG5DDP3nKRe53zDwoh6xwA88ZCl3PkMa6SDXXlykQB9227vKbHjSj2wvRsm/cGxRLFIJ2UlyZdt0GIfgAKN/cSkw4Dqi+KLGGBOSQ4wYT1DT7dsiRZGTWxr80rln1ImXsrFPp/AFf2dnbUqP2QheCoPE9xX4YYlRKztuH7hpDLzw0LvHS6nJFUg2pkqM7wFX3enxx9wEJjjxusn8Jn8LxUE0ECAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAoDvLXDj3Ha7BOzi4dTzDPi3mtOCqM/DWU2TaB2tg5Ww0JfXFO+FrnQ9xE6g6HSj05A80bzskk4d7eRpMIb3vpBAhUs4kq7m2HbSzceHlnKA2Z0ug18Dkp+GqbGR6yFSUiHu8didRTzmuabTq9EzFmfxkDjoCHLWhApElvsFariZtdQtPvy2ZbkXOcebx4mD9HsEQKOW1BfTWr6yGz6NVy7WmKEKKPkd/6H8O3Ju6ifpKSnkzejphqgX16M3TmMKsqDSVhIOw/HXU8Nu+oOqADF5F8sg/WbbKU5XAewVS1XaNztT9S78j/QtoE/pOO+rd9Wf5GYu11x/gGdbZvGRe/g==
        -----END CERTIFICATE-----
      existingSecret: 
        secretName: ""
        secretKey: ""    
    assertingPartyEntityID: "https://auth.workshop.eds-ovh.org/realms/datalab-workshop"
    assertingPartySSOUrl: "https://auth.workshop.eds-ovh.org/realms/datalab-workshop/protocol/saml"

  preAuthentication:
    enabled: false
    headerPrincipal:
    newUserRole: ROLE_USER
    customUserRoles: 
      Franz: ROLE_ADMIN

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 2000
  runAsGroup: 2000
  fsGroup: 2000
  runAsNonRoot: true

securityContext:
  readOnlyRootFilesystem: true
  privileged: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"

  hosts:
    - paths:
      - path: /
        pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

storage:
  data:
    storageClassName: "standard"
    size: "5Gi"
    accessMode: ReadWriteOnce
    
nodeSelector: {}

tolerations: []

affinity: {}

mariadb:
  enabled: true
  image:
    debug: true
  primary:
    persistence:
      storageClass: "standard"
      accessModes:
      - "ReadWriteOnce"
      size: "5Gi"
    service:
      ports:
        mysql: 3306
  networkPolicy:
    allowExternal: false
  auth:
    database: "inception"
    username: "inception"
    password: "Gre@tPwd465!*"
    configuration: |-
      [client]
      default-character-set = utf8mb4

      [mysql]
      default-character-set = utf8mb4

      [mysqld]
      character-set-client-handshake = FALSE
      character-set-server = utf8mb4
      collation-server = utf8mb4_bin