# Default values for inception.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Custom Helm Release name. 
nameOverride: ""

# Custom Helm Release full name.
fullnameOverride: ""

# -- Number of replicas fir INCEpTION deployment
replicaCount: 1

# Extra annotations for INCEpTION pod
podAnnotations: {}

# Extra labels for INCEpTION pod
podLabels: {}

# -- User-defined init-container to run before INCEpTION pod, as defined in [Kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/)
initContainers: {}

# -- User-defined extra containers to run alongside INCEpTION pod, as defined in [Kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/pods/#using-pods)
extraContainers: {}

# -- Extra environment variables for INCEpTION's container.
extraEnv: {}

# -- INCEpTION container image settings
image:
  # -- Image repository
  repository: ghcr.io/inception-project/inception
  # -- Image Pull Policy
  pullPolicy: IfNotPresent
  # -- Image tag
  tag: "33.2"

# -- INCEpTION container image Pull Secret
imagePullSecrets: {}

# -- INCEpTION configuration settings
config:
  # -- Base URL prefix on which INCEpTION is deployed
  baseUrl: "/"
  # -- INCEpTION log level (affects the application and Spring Security framework)
  logging: DEBUG

  # -- INCEpTION security settings
  security:
    # -- Accepted origin (see [dedicated INCEpTION documentation](https://inception-project.github.io/releases/33.2/docs/admin-guide.html#sect_reverse_proxy))
    acceptedOrigins: ""
    # -- Allowing HTTP unsecure communications
    allowHttp: false

  # -- INCEpTION database connection settings
  database:
    # -- Database name
    name: "inception"
    # -- Database hostname
    hostname: ""
    # -- Database port
    port: 3306
    # -- Database SSL communication
    useSSL: false
    ## -- Database server timezone
    serverTimezone: "UTC"
    # -- Database authentication settings
    auth: 
      # -- INCEpTION username
      username: "inception"
      # -- INCEpTION password
      password:
        # -- Password in plain text (NOT RECOMMENDED FOR PRODUCTION!). Ignored if a reference to an external secret is specified.
        value: ""
        # -- Reference to an external Kubernetes secret in the same namespace holding the password's value.
        existingSecret:
          # -- Secret name
          secretName: ""
          # -- Secret key holding the password's value
          secretKey: ""
  # -- Extra configuration added at the end of the `settings.properties` file, in `key: value` format.
  extraConfig: {}


# -- INCEpTION's authentication configuration
auth:
  # -- Default Administrator account configuration (see [dedicated INCEpTION documentation](https://inception-project.github.io/releases/33.2/docs/admin-guide.html#_unsupervised_installation))
  defaultAdmin:
    # -- Enabling Default Administrator feature 
    enabled: true
    # -- Default Administrator username
    username: "admin"
    # -- Default Administrator password
    password: 
      # -- Password in plain text (NOT RECOMMENDED FOR PRODUCTION!). `bcrypt` hash will be derived from that password and stored in the `settings.properties` file.
      #    Ignored if a reference to an external secret is specified. 
      value: "admin123"
      # -- Reference to an external Kubernetes secret in the same namespace holding the password's bcrypt hash's value, in the `{bcrypt}XXXXXX` format.
      existingSecret:
        # -- Secret name.
        secretName: ""
        # -- Secret key holding the password's `bcrypt` hash.
        secretKey: ""

  # -- OAuth2 settings
  oauth2:
    # -- Enabling OAuth2 SSO connection
    enabled: false
    # -- Enabling OAuth2 as default login method (skips INCEpTION's default login page)
    autoLogin: false 
    # -- OAuth2 client name, to be displayed on INCEpTION's login page.
    clientName: ""
    # -- OAUth2 client ID
    clientID: ""
    # -- OAuth2 client secret
    clientSecret:
      # -- OAuth2 client secret in plain text (NOT RECOMMENDED FOR PRODUCTION!). Ignored if a reference to an external secret is specified.
      value: ""
      # -- Reference to an external Kubernetes secret in the same namespace holding the OAuth2 secret's value.
      existingSecret: 
        # -- Secret name
        secretName: ""
        # -- Secret key holding the OAuth2 client secret's value. 
        secretKey: ""
    # -- OAuth2 scope
    scope: ""
    # -- OAuth2 grant type
    authorizationGrantType: ""
    # -- OAuth2 redirect URI
    redirectURI: ""
    # -- OAuth2 Issuer URI
    issuerURI: ""
    # -- OAuth2 claim holding the username attribute.
    usernameAttribute: ""

  saml2:
    enabled: false
    autoLogin: false
    signRequest: 
      enabled: false
      certificateValue: ""
      privateKeyValue: ""
      existingTlsSecret: ""
    assertingPartyCertificate:
      value: ""
      existingSecret: 
        secretName: ""
        secretKey: ""    
    assertingPartyEntityID: ""
    assertingPartySSOUrl: ""

  preAuthentication:
    enabled: false
    headerPrincipal: ""
    newUserRole: ""
    customUserRoles: {}


podSecurityContext:
  runAsUser: 2000
  runAsGroup: 2000
  fsGroup: 2000
  runAsNonRoot: true

securityContext:
  readOnlyRootFilesystem: true
  privileged: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  enabled: true
  initialDelaySeconds: 0
  periodSeconds: 5
  failureThreshold: 2
startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

storage: {}
nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

networkPolicies:
  enabled: true

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"

  hosts:
    - host: localhost
      paths:
      - path: /
        pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


mariadb:
  enabled: true
  image:
    debug: true
    service:
      ports:
        mysql: 3306
  networkPolicy:
    allowExternal: false
  auth:
    database: "inception"
    username: "inception"
    password: "Gre@tPwd465!*"
    configuration: |-
      [client]
      default-character-set = utf8mb4

      [mysql]
      default-character-set = utf8mb4

      [mysqld]
      max_allowed_packet=500M
      character-set-client-handshake = FALSE
      character-set-server = utf8mb4
      collation-server = utf8mb4_bin