// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_monitoring_agreement]]
== Agreement

Agreement can be inspected on a per-feature basis and is calculated pair-wise between all 
annotators across all documents.

The first time a feature is selected for agreement inspection, it takes a moment to calculate the
differences between the annotated documents. Switching between different features subsequently
is much faster.

Agreement is calculated in two steps:

. *Generation of positions and configuration sets* - all documents are scanned for annotations and 
   annotations located at the same positions are collected in configuration sets. To determine if
   two annotations are at the same position, different approaches are used depending on the layer
   type. For a span layer, the begin and end offsets are used. For a relation layer, the begin and end
   offsets of the source and target annotation are used. Chains are currently not supported. 
. *Calculation of pairwise agreement* - based on the generated configuration sets, agreement is calculated.
  There are two cases where a configuration set may be omitted from the pairwise agreement calculation:
.. one of the users did not make an annotation at the position;
.. one or both of the users did not assign a value to the feature on which agreement is calculated
   at the position.

The lower part of the agreement matrix displays how many configuration sets were used to calculate
agreement and how many were found in total. The upper part of the agreement matrix displays the
pairwise Cohen's kappa scores.

The agreement calculations considers an unset feature (with a `null` value) to be equivalent to a
feature with the value of an empty string. Empty strings are considered valid labels and are not
excluded from agreement calculation.

Annotations for a given position are considered complete when both annotators have made an
annotation. Unless the agreement measure supports `null` values (i.e. missing annotations),
incomplete annotations are implicitly excluded from the agreement calculation. If the agreement
measure does support incomplete annotations, then excluding them or not is the users' choice.

.Possible combinations for agreement
|====
| Feature value annotator 1 | Feature value annotator 2 | Agreement | Complete

| `X`           
| `X`
| yes
| yes

| `X`           
| `Y`
| no
| yes

| *no annotation*           
| `Y`
| no
| no

| *empty*           
| `Y`
| no
| yes

| *empty*           
| *empty*
| yes
| yes

| *null*
| *empty*
| yes
| yes

| *empty*           
| *no annotation*
| no
| no

|====

  
CAUTION: Multiple interpretations in the form of stacked annotations are not supported in the agreement 
      calculation! This also includes relations for which source or targets spans are stacked.

