////
// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
////

[[sect_annotation_link_features]]
= Link Features

Link features can be used to link one annotation to others. Before a link can be made, a slot must be added.
If role labels are enabled enter the role label in the text field and press the *add*  button to create the slot. 
Next, click on field in the newly created slot to *arm* it. 
The field's color will change to indicate that it is armed. Now you can fill the slot by double-clicking on a span annotation.
To remove a slot, arm it and then press the *del* button.

.Navigating along links
Once a slot has been filled, there is a cross-hair icon in the slot field header which can be used to navigate to the slot filler.

When a span annotation is selected which acts as a slot filler in any link feature, then the  annotation owning the slow is shown in the annotation detail panel. 
Here, the cross-hair icon can be used to jump to the slot owner.

.Role labels
If role labels are enabled they can be changed by the user at any time.
To change a previously selected role label, no prior deletion is needed.
Just click on the slot you want to change, it will be highlighted in orange, and chose another role label.

If there is a large number of tags in the tagset associated with the link feature, the the role combobox is replaced with an auto-complete field. 
The difference is that in the auto-complete field, there is no button to open the dropdown to select a role. 
Instead, you can press space or use the cursor-down keys to cause the dropdown menu for the role to open. 
Also, the dropdown only shows up to a configurable maximum of matching tags. You can type in something (e.g. `action`) to filter for items containing `action`. 
The threshold for displaying an auto-complete field and the maximum number of tags shown in the dropdown can be configured globally.
The settings are documented in the administrators guide.

If role labels are disabled for the link feature layer they cannot be manually set by the user.
Instead the UI label of the linked annotation is displayed.
