// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_formats_pdf]]
= PDF Format

This allows the import of PDF files. A PDF file can be viewed and annotated in its original form.
It is also possible to switch to another editor like the "brat" editor to annotate directly on the
text extracted from the PDF. The annotations made on PDF files can be exported again in other
formats (e.g. UIMA CAS XMI or UIMA CAS JSON), but not as PDF files.

When importing PDF files, {produce-name} will automatically detect token and sentence boundaries.
It is presently not possible override these boundaries externally. 

NOTE: When importing a PDF file, you may get a message that the file cannot be imported because it
     is _empty_. You may be confused because you can see contents in the PDF if you open the file in your
     PDF viewer of choice. It may be that your PDF contains only an image of the text, but not actual text
     data. For {product-name} to be able to work with a PDF, it must be _searchable_ - i.e. the text must not
     only be included as an image but as actual Unicode character information. You may try using an OCR tool
     to process your PDF into a searchable PDF before importing it.

NOTE: There is a feature of PDF files called "annotations" which you may create in tools like
      Acrobat Reader. These means annotations like notes, comments or highlights that are embedded in the
      PDF file itself. You may be able to see those in the annotation editor, but do not confuse them
      with {product-name} annotations. There is currently no way for {product-name} to interact with these
      "PDF annotations".

[cols="2,1,1,1,3"]
|====
| Format | Read | Write | Custom Layers | Description

| PDF (`pdf2`)
| yes
| no
| n/a
| 
|====
