[[sect_search-mtas]]

==== Mtas search syntax

The INCEpTION Mtas search provider allows queries to be executed using CQL (Corpus 
Query Language), as shown in the following examples.
More examples and information about CQL syntax can be found 
in https://meertensinstituut.github.io/mtas/search_cql.html.

* Single token: all occurrences of the token *Galicia*

 Galicia
 
* Multiple tokens: all occurrences of the token sequence *The capital of Galicia*

 The capital of Galicia
 
* Lemma: all occurrences of the lemma *sign*

 [Lemma.Lemma="sign"]

* POS tag: all tokens that are annotated as a noun

 [POS.PosValue="NOUN"]

* Named entities: all named entity annotations

 <Named_entity/>

* Named entities: all occurrencies of a particular kind of named entity (in this case, *location* named entities)

 <Named_entity.value="LOC"/>

* Sequence: all occurrences of the lemma *be* immediately followed by the lemma *signed*

 [Lemma.Lemma="be"][Lemma.Lemma="sign"]

* Sequence: all occurrences of the token *house* immediately followed by a verb

 [Token=“house"][POS.PosValue=“VERB"]

* Sequence: all occurrences of a verb immediately followed by a named entity

 [POS.PosValue=“VERB"]<Named_entity/>
 
* Sequence: All occurrences of two named entities in a row

 <Named_entity/> {2}
 
* Sequence: All occurrences of two named entities in a row (alternative syntax)

  <Named_entity/> <Named_entity/>
  
* Sequence: All occurrences of a named entity followed by a token (whatever it is) and another named entity:

 <Named_entity/> [] <Named_entity/>

* Sequence: All occurrences of a named entity followed by an optional token and another named entity:
 
 <Named_entity/> []? <Named_entity/>

* Sequence: All occurrences of two named entities separated by exactly two tokens

 <Named_entity/> []{2} <Named_entity/>

* Sequence: All occurrences of two named entities separated by among one and three tokens

 <Named_entity/> []{1,3} <Named_entity/>
 
* OR: All named entities of type LOC or OTH
 
 (<Named_entity.value="OTH"/> | <Named_entity.value="LOC"/>)

* Within: All occurrences of the lemma *sign* annotated as a verb

 [POS.PosValue="VERB"] within [Lemma.Lemma="sign"]

* Within: All occurrences of a determinant inside a named entity

 [POS.PosValue="DET"] within <Named_entity/>

* Not within: All occurrences of a determinant not inside a named entity

 [POS.PosValue="DET"] !within <Named_entity/>

* Containing: All occurrences of named entities containing a determinant
 
 <Named_entity/> containing [POS.PosValue="DET"]

* Not containing: All occurrences of named entities not containing a determinant
 
 <Named_entity/> !containing [POS.PosValue="DET"]

* Intersecting: All named entities of type LOC intersecting with a semantic argument

 <Named_entity.value="LOC"/> intersecting <SemArg/>
 
* OR combined with Within: All named entities of type LOC or OTH contained in a semantic argument
 
 (<Named_entity.value="OTH"/> | <Named_entity.value="LOC"/>) within <SemArg/>

* OR combined with Intersecting query: Named entities of type LOC or OTH intersecting with a semantic argument

 (<Named_entity.value="OTH"/> | <Named_entity.value="LOC"/>) intersecting
<SemArg/>

==== Concept Annotation queries

* Generic Search over annotated KB entities : all occurrences for KB entity *Bordeaux*

 <KB.Entity="Bordeaux"/>

* Named Entity Identifier : all occurrences of the annotated identifier *ChateauMorgonBeaujolais* .
  Here *ChateauMorgonBeaujolais* is the label for an example instance from KnowledgeBase, with IRI: http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#ChateauMorgonBeaujolais 

 <Named_entity.identifier="ChateauMorgonBeaujolais"/>

* Named Entity Identifier for KB instance: all occurrences of the annotated identifier *ChateauMorgonBeaujolais*

 <Named_entity.identifier.instance="ChateauMorgonBeaujolais"/>

* Named Entity Identifier for KB concept: all occurrences of the annotated identifier *AmericanWine* 
  Here *AmericanWine* is the label for an example concept from KnowledgeBase, with IRI: http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#AmericanWine

 <Named_entity.identifier.class="AmericanWine"/>

* Named Entity Identifier covering multiple tokens: all occurrences of the annotated identifier *ChateauMorgonBeaujolais*

 <Named_entity.identifier="ChateauMorgonBeaujolais"/>
 
 * OR All named entities identifier with annotated identifier *ChateauMorgonBeaujolais* or *AmericanWine*
 
 (<Named_entity.identifier="ChateauMorgonBeaujolais"/> | <Named_entity.identifier="AmericanWine"/>)
 
