[[sect_search-mtas]]

== Mtas search syntax

The INCEpTION Mtas search provider allows queries to be executed using CQL (Corpus 
Query Language), as shown in the following examples.
More examples and information about CQL syntax can be found 
at https://meertensinstituut.github.io/mtas/search_cql.html.

It is possible to query for annotations on span and relation layers. However, zero-witdh span
annotations are not indexed and cannot be queried for. This includes relations which start or
end in zero-width spans. 

When performing queries, the user must reference the annotation types using the layer names, 
as defined in the project schema. In the same way, the features must be referenced using their names 
as defined in the project schema. In both cases, empty spaces in the names must be replaced by 
an underscore. 

Thus, *Lemma* refers to the *Lemma* layer, *Lemma.Lemma* refers to the the *Lemma* feature in the 
*Lemma* layer. In the same way, *Named_entity* refers to *Named entity* layer, and 
*Named_entity.value* refers to the *value* feature in the *Named entity* layer.

Annotations made over single tokens can be queried using the `[...]` syntax, while annotations 
made over multiple tokens must be queried using the `<.../>` syntax. Note that the multi-token
query syntax can also be used to retrieve single token annotations (e.g. POS or lemma annotations).

In the first case, the user must always provide a feature and a value. The following syntax returns 
all single token annotations of the *LayerX* layer whose *FeatureX* feature have the given value.

----
[LayerX.FeatureX="value"]
----
 
In the second case, the user may or not provide a feature and a value. Thus, the following syntax 
will return all multi-token annotations of the *LayerX* layer, regardless of their features and 
values. 

----
<LayerX/>
----
 
On the other hand, the following syntax will return the multi-token annotations whose *FeatureX* 
feature has the given value.

----
<LayerX.FeatureX="value"/>
----


=== Basic Annotation queries

.Single token: all occurrences of the token *Galicia*
----
Galicia
----
 
.Single token: all occurrences of the token *Galicia* (alternative)
----
"Galicia"
----
 
.Multiple tokens: all occurrences of the token sequence *The capital of Galicia*
----
The capital of Galicia
----
 
.Multiple tokens: all occurrences of the token sequence *The capital of Galicia* (alternative)
----
"The" "capital" "of" "Galicia"
----
 
.Lemma: all occurrences of the lemma *sign*
----
[Lemma.Lemma="sign"]
----

.POS tag: all tokens that are annotated as a noun
[POS.PosValue="NOUN"]

.Named entities: all named entity annotations
----
<Named_entity/>
----

.Named entities: all occurrencies of a particular kind of named entity (in this case, *location* named entities)
----
<Named_entity.value="LOC"/>
----

.Sequence: all occurrences of the lemma *be* immediately followed by the lemma *signed*
----
[Lemma.Lemma="be"] [Lemma.Lemma="sign"]
----

.Sequence: all occurrences of the token *house* immediately followed by a verb
----
"house" [POS.PosValue="VERB"]
----

.Sequence: all occurrences of a verb immediately followed by a named entity
----
[POS.PosValue="VERB"]<Named_entity/>
----
 
.Sequence: All occurrences of two named entities in a row
----
<Named_entity/>{2}
----
 
.Sequence: All occurrences of two named entities in a row (alternative syntax)
----
<Named_entity/> <Named_entity/>
----
  
.Sequence: All occurrences of a named entity followed by a token (whatever it is) and another named entity:
----
<Named_entity/> [] <Named_entity/>
----

.Sequence: All occurrences of a named entity followed by an optional token and another named entity:
----
<Named_entity/> []? <Named_entity/>
----

.Sequence: All occurrences of two named entities separated by exactly two tokens
----
<Named_entity/> []{2} <Named_entity/>
----

.Sequence: All occurrences of two named entities separated by among one and three tokens
----
<Named_entity/> []{1,3} <Named_entity/>
----
 
.OR: All named entities of type LOC or OTH
----
(<Named_entity.value="OTH"/> | <Named_entity.value="LOC"/>)
----

.Within: All occurrences of the lemma *sign* annotated as a verb
----
[POS.PosValue="VERB"] within [Lemma.Lemma="sign"]
----

.Within: All occurrences of a determinant inside a named entity
----
[POS.PosValue="DET"] within <Named_entity/>
----

.Not within: All occurrences of a determinant not inside a named entity
----
[POS.PosValue="DET"] !within <Named_entity/>
----

.Containing: All occurrences of named entities containing a determinant
----
<Named_entity/> containing [POS.PosValue="DET"]
----

.Not containing: All occurrences of named entities not containing a determinant
----
<Named_entity/> !containing [POS.PosValue="DET"]
----

.Intersecting: All named entities of type LOC intersecting with a semantic argument
----
<Named_entity.value="LOC"/> intersecting <SemArg/>
----
 
.OR combined with Within: All named entities of type LOC or OTH contained in a semantic argument
----
(<Named_entity.value="OTH"/> | <Named_entity.value="LOC"/>) within <SemArg/>
----

.OR combined with Intersecting query: Named entities of type LOC or OTH intersecting with a semantic argument
----
(<Named_entity.value="OTH"/> | <Named_entity.value="LOC"/>) intersecting <SemArg/>
----

=== Relation queries

When relations are index, they are indexed by their target span.

.Search for dependency targets
----
<Dependency/>
----

.Search for dependency based on a feature value
----
<Dependency.Relation="nsubj"/>
----

.Search for dependency target by the source text
----
<Dependency-source="John"/>
----

.Search for dependency target by the target text
----
<Dependency-target="Miller"/>
----

The following examples work for custom relation layers, but not for the built-in **Dependency**
layer. We assume a span layer called `component` and a relation layer called `rel` attached to it.
Both layers have a string feature called `value`.

.Search for rel annotations by feature on the relation source
----
<rel-source.value="foo"/>
----

.Search for rel annotations by feature on the relation target
----
<rel-target.value="foo"/>
----


=== Concept Annotation queries

.Generic Search over annotated KB entities : all occurrences for KB entity *Bordeaux*
----
<KB-Entity="Bordeaux"/>
----

The following query returns all mentions of *ChateauMorgonBeaujolais* or any of its subclasses in
the associated knowledge base.

.Named Entity Identifier for KB instance: all mentions of *ChateauMorgonBeaujolais*
----
<Named_entity.identifier="ChateauMorgonBeaujolais"/>
----

Mind that the label of a knowledge base item may be ambiguous, so it may be necessary to search by
IRI.

.Named Entity Identifier for KB instance: all mentions of *ChateauMorgonBeaujolais* by IRI
----
<Named_entity.identifier="http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#ChateauMorgonBeaujolais"/>
----


.Named Entity Identifier : all exact mentions of *ChateauMorgonBeaujolais* .
----
<Named_entity.identifier-exact="ChateauMorgonBeaujolais"/>
----


.OR All exact mentions of either *ChateauMorgonBeaujolais* or *AmericanWine*
---- 
(<Named_entity.identifier-exact="ChateauMorgonBeaujolais"/> | <Named_entity.identifier-exact="AmericanWine"/>)
----
