[[sect_search-mtas]]

==== Mtas search syntax

The INCEpTION Mtas search provider allows queries to be executed using CQL (Corpus 
Query Language), as shown in the following examples.
More examples and information about CQL syntax can be found 
in https://meertensinstituut.github.io/mtas/search_cql.html.

When performing queries, the user must reference the annotation types using the layer names, 
as defined in the project schema. In the same way, the features must be referenced using their names 
as defined in the project schema. In both cases, empty spaces in the names must be replaced by 
an underscore. 

Thus, *Lemma* refers to the *Lemma* layer, *Lemma.Lemma* refers to the the *Lemma* feature in the 
*Lemma* layer. In the same way, *Named_entity* refers to *Named entity* layer, and 
*Named_entity.value* refers to the *value* feature in the *Named entity* layer.

Annotations made over single tokens can be queried using the [...] syntax, while annotations 
made over multiple tokens must be queried using the <../> syntax. 

In the first case, the user must always provide a feature and a value. The following syntax returns 
all single token annotations of the *LayerX* layer whose *FeatureX* feature have the given value.

 [LayerX.FeatureX="value"]
 
In the second case, the user may or not provide a feature and a value. Thus, the following syntax 
will return all multi-token annotations of the *LayerX* layer, regardless of their features and 
values. 

 <LayerX/>
 
On the other hand, the following syntax will return the multi-token annotations whose *FeatureX* 
feature has the given value.

 <LayerX.FeatureX="value"/>

Notice that the multi-token query syntax can also be used to retrieve single token annotations (e.g.
POS or lemma annotations).

===== Basic Annotation queries
* Single token: all occurrences of the token *Galicia*

 Galicia
 
* Multiple tokens: all occurrences of the token sequence *The capital of Galicia*

 The capital of Galicia
 
* Lemma: all occurrences of the lemma *sign*

 [Lemma.Lemma="sign"]

* POS tag: all tokens that are annotated as a noun

 [POS.PosValue="NOUN"]

* Named entities: all named entity annotations

 <Named_entity/>

* Named entities: all occurrencies of a particular kind of named entity (in this case, *location* named entities)

 <Named_entity.value="LOC"/>

* Sequence: all occurrences of the lemma *be* immediately followed by the lemma *signed*

 [Lemma.Lemma="be"][Lemma.Lemma="sign"]

* Sequence: all occurrences of the token *house* immediately followed by a verb

 [Token="house"][POS.PosValue="VERB"]

* Sequence: all occurrences of a verb immediately followed by a named entity

 [POS.PosValue="VERB"]<Named_entity/>
 
* Sequence: All occurrences of two named entities in a row

 <Named_entity/> {2}
 
* Sequence: All occurrences of two named entities in a row (alternative syntax)

  <Named_entity/> <Named_entity/>
  
* Sequence: All occurrences of a named entity followed by a token (whatever it is) and another named entity:

 <Named_entity/> [] <Named_entity/>

* Sequence: All occurrences of a named entity followed by an optional token and another named entity:
 
 <Named_entity/> []? <Named_entity/>

* Sequence: All occurrences of two named entities separated by exactly two tokens

 <Named_entity/> []{2} <Named_entity/>

* Sequence: All occurrences of two named entities separated by among one and three tokens

 <Named_entity/> []{1,3} <Named_entity/>
 
* OR: All named entities of type LOC or OTH
 
 (<Named_entity.value="OTH"/> | <Named_entity.value="LOC"/>)

* Within: All occurrences of the lemma *sign* annotated as a verb

 [POS.PosValue="VERB"] within [Lemma.Lemma="sign"]

* Within: All occurrences of a determinant inside a named entity

 [POS.PosValue="DET"] within <Named_entity/>

* Not within: All occurrences of a determinant not inside a named entity

 [POS.PosValue="DET"] !within <Named_entity/>

* Containing: All occurrences of named entities containing a determinant
 
 <Named_entity/> containing [POS.PosValue="DET"]

* Not containing: All occurrences of named entities not containing a determinant
 
 <Named_entity/> !containing [POS.PosValue="DET"]

* Intersecting: All named entities of type LOC intersecting with a semantic argument

 <Named_entity.value="LOC"/> intersecting <SemArg/>
 
* OR combined with Within: All named entities of type LOC or OTH contained in a semantic argument
 
 (<Named_entity.value="OTH"/> | <Named_entity.value="LOC"/>) within <SemArg/>

* OR combined with Intersecting query: Named entities of type LOC or OTH intersecting with a semantic argument

 (<Named_entity.value="OTH"/> | <Named_entity.value="LOC"/>) intersecting
<SemArg/>

===== Concept Annotation queries

* Generic Search over annotated KB entities : all occurrences for KB entity *Bordeaux*

 <KB.Entity="Bordeaux"/>

* Named Entity Identifier : all occurrences of the annotated identifier *ChateauMorgonBeaujolais* .
  Here *ChateauMorgonBeaujolais* is the label for an example instance from KnowledgeBase, with IRI: http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#ChateauMorgonBeaujolais 

 <Named_entity.identifier.exact="ChateauMorgonBeaujolais"/>

* Named Entity Identifier for KB instance: all occurrences of the annotated identifier *ChateauMorgonBeaujolais*

 <Named_entity.identifier.instance="ChateauMorgonBeaujolais"/>

* Named Entity Identifier for KB concept: all occurrences of the annotated identifier *AmericanWine* 
  Here *AmericanWine* is the label for an example concept from KnowledgeBase, with IRI: http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#AmericanWine

 <Named_entity.identifier.class="AmericanWine"/>

* Named Entity Identifier covering multiple tokens: all occurrences of the annotated identifier *ChateauMorgonBeaujolais*

 <Named_entity.identifier.exact="ChateauMorgonBeaujolais"/>
 
 * OR All named entities identifier with annotated identifier *ChateauMorgonBeaujolais* or *AmericanWine*
 
 (<Named_entity.identifier.exact="ChateauMorgonBeaujolais"/> | <Named_entity.identifier.exact="AmericanWine"/>)
 
 * All annotated identifier with a sub concept or instance of a particular identifier  *RedWine* 
 
 <Named_entity.identifier="RedWine"/>
 
