kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "inception.fullname" . }}-data
spec:
  storageClassName: {{ .Values.storage.data.storageClassName }}
  accessModes:
    - {{ .Values.storage.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}