// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_constraints]]
== Constraints

Constraints reorder the choice of tags based on the context of an annotation. For instance, for a
given lemma, not all possible part-of-speech tags are sensible. Constraint rules can be set up to
reorder the choice of part-of-speech tags such that the relevant tags are listed first. This speeds
up the annotation process as the annotator can choose from the relevant tags more conveniently.

The choice of tags is not limited, only the order in which they are presented to the annotator. Thus, if
the project manager has forgotten to set up a constraint or did possible not consider an oddball case,
the annotator can still make a decision. 

A *constraint set* consists of two components:

* import statement
* scopes
* Import statements* are composed in the following way:

[source,text]
----
import <fully_qualified_name_of_layer> as <shortName>;
----

It is necessary to declare short names for all fully qualified names because only short names can be used when writing a constraint rule. Short names cannot contain any dots or special characters, only letters, numbers, and the underscore.

NOTE: If you are not sure what the fully qualified name of a layer is, you can look it up going to *Layers* in *Project settings*. Click on a particular layer and you can view the fully qualified name under *Technical Properties*.

*Scopes* consist of a *scope name* and one or more *rules* that refer to a particular annotation layer and define restrictions for particular conditions. For example, it is possible to reorder the applicable tags for a POS layer, based on what kind of word the annotator is focusing on. 

While scope names can be freely chosen, scope rules have a fixed structure. They consist of *conditions* and *restrictions*, separated by an arrow symbol (`->`).
Conditions consist of a *path* and a *value*, separated by an equal sign (`=`). Values always have to be embraced by double-quotes. Multiple conditions in the same rule are connected via the `&`-operator, multiple restrictions in the same rule are connected via the `|`-operator.

Typically a rule’s syntax is 

.Single constraint rule
[source,text]
----
<scopeName> {
  <condition_set> -> <restriction_set>;
}  
----

This leads to the following structure:

.Multiple constraint rules
[source,text]
----
<scopeName> {
  <rule_1>;
  ...
  <rule_n>;
}  
----

Both conditions and restrictions are composed of a *path* and a *value*. The latter is always enclosed in double quotes.

.Structure of conditions and restrictions
[source,text]
----
<path>="<value>"
----

A *condition* is a way of defining whether a particular situation in {product-name} is based on annotation layers and features in it.

A *condition set* consists of one or more conditions. They are connected with logical AND as follows. 

[source,text]
----
<condition> & <condition>
----

A *restriction set* defines a set of restrictions which can be applied if a particular condition set is evaluated to true. As multiple restrictions inside one rule are interpreted as conjunctions, they are separated by the `|`-operator”.

[source,text]
----
<restriction> | <restriction>
----

A *path* is composed of one or more steps, separated by a dot. A *step* consists of a *feature selector* and a *type selector*.
*Type selectors* are only applicable while writing the condition part of a rule. They comprise a *layer operator* `@` followed by the type (Lemma, POS, etc).
*Feature selectors* consist of a feature name, e.g.

[source,text]
----
pos.PosValue
----

*Navigation across layers* is possible via 

[source,text]
----
@<shortLayerName>
----

Hereby all annotations of type `<shortLayerName>` at the same position as the current context are found.

=== Comments

The constraint language supports block comments which start with `/*` and end with `*/`. These
comments may span across multiple lines.

[source,text]
----
/* This is a single line comment */

/*
   This is a multi-
   line comment
*/
----


=== Conditional features

Constraints can be used to set up conditional features, that is features that only become available
in the UI if another feature has a specific value. Let's say that for example you want to annotate
events and only *causing* events should additionally offer a *polarity* feature, while for *caused*
events, there should be no way to select a polarity.

Sticking with the example of annotating events, conditional features can be set up as following:

* Go to the *Layer* tab of the project settings
* Create a new tagset called *Event category* and add the tags *causing* and *caused*
* Create a new tagset called *Event polarity* and add the tags *positive* and *negative*
* Create a new span layer called *Event*
* Add a string feature called *category* and assign the tagset *Event category* 
* Save the changes to the *category* feature
* Add a string feature called *polarity* and assign the tagset *Event polarity* 
* Enabled the checkbox *Hide Un-constraint feature* on the *polarity* feature
* Save the changes to the *polarity* feature
* Create a new text file called `constraints.txt` with the following contents
.
[source,text]
----
import webanno.custom.Event as Event;

Event {
  category="causing" -> polarity="positive" | polarity="negative";
}
----
* Import `constraints.txt` in the tab *Constraints* in the project settings.

When you now annotate an *Event* in this project, then the *polarity* feature is only visible and
editable if the *category* of the annotation is set to *causing*.

NOTE: It is important that both of the features have tagsets assigned - otherwise the conditional
      effect will not take place.

=== Constraints for slot features

Constraints can be applied to the roles of slot features. This is useful, e.g. when annotating predicate/argument structures where specific predicates can only have certain arguments. 

Consider having a span layer `SemPred` resembling a semantic predicate and bearing a slot feature `arguments` and a string feature `senseId`. We want to restrict the possible argument roles based on the lemma associated with the predicate. The first rule in the following example restricts the `senseId` depending on the value of a `Lemma` annotation at the same position as the `SemPred` annotation. The second rule then restricts the choice of roles for the arguments based on the `senseId`. 

Note that some role labels are marked with the flag `(!)`. This is a special flag for slot features and indicates that slots with these role labels should be automatically displayed in the UI ready to be filled. This should be used for mandatory or common slots and saves time as the annotator does not have to manually create the slots before filling them.

[source,text]
----
SemPred {
  /* Rule 1 */
  @Lemma.value = "ask" -> senseId = "Questioning" | senseId = "Request" | senseId = "XXX";
  /* .. other lemmata */
  /* Rule 2 */
  senseId = "Questioning" -> 
    /* core roles */
    arguments.role = "Addressee" (!) | arguments.role = "Message" (!) | arguments.role = "Speaker" (!) |
    /* non-core roles */
    arguments.role = "Time" | arguments.role = "Iterations";
  /* .. other senses */
}
----

=== Constraints language grammar

.Constraints language grammar
[source,text]
----
// Basic structure ---------------------------------------
<file>            ::= <import>* | <scope>*
<scope>           ::= <shortLayerName> "{" <ruleset> "}"
<ruleset>         ::= <rule>*
<import>          ::= "import" <qualifiedLayerName> 
                      "as" <shortLayerName> 
<rule>            ::= <conds> "->" <restrictions> ";"

// Conditions --------------------------------------------
<conds>           ::= <cond> | <cond> "&" <conds>
<cond>            ::= <path> "=" <value>
<path>            ::= <featureName> | <step> "." <path>
<step>            ::= <featureName> | <layerSelector>
<layerSelector>   ::= <layerOperator>? <shortLayerName>
<layerOperator>   ::= "@" // select annotation in layer X

// Restrictions ------------------------------------------
<restrictions>    ::= <restriction> | 
                      <restriction> "|" <restrictions>
<restriction>     ::= <restrictionPath> "=" <value> 
                      ( "(" <flags> ")" )
<restrictionPath> ::= <featureName> | 
                      <restrictionPath> "." <featureName>
<flags>           ::= "!" // core role
----
