// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_formats_uimaxmi]]
= UIMA CAS XMI

The probably most commonly used formats supported by the Apache UIMA framework is UIMA CAS XMI.
It is able to capture all the information contained in the CAS. This is the de-facto standard for exchanging data in the UIMA world. Most UIMA-related tools support it.

The XMI format does not include type system information. When exporting files in the XMI format, a ZIP file is created for each document which contains the XMI file itself as well as an XML file containing the type system.

There are two flavors of CAS XMI, namely link:http://www.w3.org/TR/2006/REC-xml-20060816/Overview.html[XML 1.0] and link:http://www.w3.org/TR/xml11/Overview.html[XML 1.1]. XML 1.0 is more widely supported in
the world of XML parsers, so you may expect better interoperability with other programming languages
(e.g. Python) with the XML 1.0 flavor. XML 1.1 has a support for a wider range of characters, despite 
dating back to 2006, it is still not supported by all XML parsers.

The format can be processed in Java using the link:https://github.com/apache/uima-uimaj#readme[Apache UIMA Java SDK] (both flavors) or in Python using link:https://pypi.org/project/dkpro-cassis/[DKPro Cassis] (only the XMI 1.0 flavor).

[cols="2,1,1,1,3"]
|====
| Format | Read | Write | Custom Layers | Description

| link:https://uima.apache.org/d/uimaj-current/references.html#ugr.ref.xmi[UIMA CAS XMI (XML 1.0)] (`xmi`)
| yes
| yes
| yes
| UIMA XMI CAS (XML 1.0)

| link:https://uima.apache.org/d/uimaj-current/references.html#ugr.ref.xmi[UIMA CAS XMI (XML 1.1)] (`xmi-xml1.1`)
| yes
| yes
| yes
| UIMA XMI CAS (XML 1.1)
|====

