// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_formats]]
= Formats

This section provides information about the different formats that {product-name} can import and 
export. While many formats can be imported and exported, some formats can only be imported and others
can only be exported. Also, not all formats support custom annotation layers. Each format description
includes a small table explaining whether the format can be imported, exported and whether custom
layers are supported. The first column includes a format ID in addition to the format name. This
ID can be used e.g. in conjunction with the remote API when to select the format when importing or
exporting annotations and documents.
