// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
[sect_import]
= Import

Here, you can import project archives such as the example projects provided on our website or
projects exported from the <<sect_projects_export>> tab.

When a user with the role *project creator* imports a project, that user automatically becomes a
*manager* of the imported project.
However, no permissions for the project are imported!

NOTE: If the current instance has users with the same name as those who originally worked on the
      import project, the manager can add these users to the project and they can access their annotations.
      Otherwise, only the imported source documents are accessible.
      
When a user with the role *administrator* imports a project, the user can choose whether to *import the permissions* and whether to *automatically create users* who have permissions on the imported
project but so far do not exist.
If this option to create missing users disabled, but the option to import permissions is enabled, then projects still maintain their association to users by name.
If the respective user accounts are created manually after the import, the users will start showing up in the projects.

NOTE: Automatically added users are disabled and have no password.
      They must be explicitly enabled and a password must be set before the users can log in.
