// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_settings_sharing]]
= 🧪 Invite Links Settings

====
CAUTION: Experimental feature.
====

You can enable invite links for your {product-name} instance. This will allow project managers to 
generate invite links for their project which will expire automatically after one year or at a 
chosen date. They can also be deleted or regenerated by the manager. Any user of your instance can 
use this invite link to access the project. She will automatically be added to the project with 
annotator role when following it. 

Optionally, users can be invited using a password-less login. In this mode, the user logging in 
simply chooses a login name and a project-bound password-less account for this user is created.
The user can only login to this account via the invite link. When the project is deleted, all the
project-bound accounts are deleted as well. The project-bound accounts internally use a randomized
user ID which allows projects projects with such accounts to be exported and imported into other
instances.

.Invite Links settings
[cols="4*", options="header"]
|===
| Setting
| Description
| Default
| Example

| sharing.invites.enabled
| enable/disable invite links
| false
| true

| sharing.invites.guests-enabled
| enable/disable guest annotators
| false
| true

| sharing.invites.invite-base-url
| base URL used to generate invite links, e.g. when running behind a reverse proxy
| _unset_
| https://public.mydomain.com/inception
|===

