// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_formats_brat]]
= brat (experimental)

====
CAUTION: Experimental feature. To use this functionality, you need to enable it first by adding `format.brat.enabled=true` to the `settings.properties` file (see the <<admin-guide.adoc#sect_settings, Admin Guide>>).
====

This format is the native format of the link:https://brat.nlplab.org[brat rapid annotation tool]. 
Its official documentation can be found link:https://brat.nlplab.org/standoff.html[here].

This format is mainly directed towards users who have existing tooling compatible with the brat format and want to use
that tooling with texts annotated in {product-name}. The brat format is less expressive than the {product-name} data
model, so the export process may not be loss-less. Also, for this reason, importing brat data into {product-name} is not
trivial and therefore currently not supported.

NOTE: {product-name} supports attributes (features) on relations, but the original brat does not. For this reason, the
      files produced by this format may not import into or display properly in the original brat tool.

[cols="2,1,1,1,3"]
|====
| Format | Read | Write | Custom Layers | Description

| brat (experimental) (`brat`)
| false
| yes
| yes
| brat format

|====
