// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_formats_brat_basic]]
= 🧪 brat basic

====
CAUTION: Experimental feature. To use this functionality, you need to enable it first by adding `format.brat-basic.enabled=true` to the `settings.properties` file (see the <<admin-guide.adoc#sect_settings, Admin Guide>>).
====

This format is the native format of the link:https://brat.nlplab.org[brat rapid annotation tool]. 
Its official documentation can be found link:https://brat.nlplab.org/standoff.html[here].

The **brat basic** format is mainly directed towards users who have existing texts annotated in the brat format and want to import these into {product-name}. In the brat format, a document always consists of two files: an `.ann` file containing the annotations and a `.txt` file containing the text. However, {product-name} requires every document to consist only of a single file. In order to import a document in **brat basic** format, it is therefore currently necessary to create one ZIP file per each pair of `.ann` and `.txt` file and then uploading this ZIP file into {product-name}. 

Before importing, ensure that your project contains the pre-defined layers **Span** and **Relation**. All annotations imported from the brat data will be mapped to these two layers. Also add any attributes that you want to import as features to the **Span** layer. 

[cols="2,1,1,3"]
|====
| Format | Import | Export | Supported layers

| brat (experimental) (`bratBasic`)
| yes
| no
| Span (built-in), +
  Relation (built-in)
|====
