// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_docker]]
= Running via Docker

== Quick start

If you have Docker installed, you can run {product-name} using

[source,shell,subs="+attributes"]
----
$ docker run -it --name inception -p8080:8080 inceptionproject/inception:{revnumber}
----

The command downloads {product-name} from Dockerhub and starts it on port 8080. If this port is not
available on your machine, you should provide another port to the `-p` parameter. 

The logs will be printed to the console. To stop the container, press `CTRL-C`.

To run the {product-name} docker in the background use 

[source,shell,subs="+attributes"]
----
$ docker run -d --name inception -p8080:8080 inceptionproject/inception:{revnumber}
----

Logs are accessible by typing

[source,shell,subs="+attributes"]
----
$ docker logs inception
----

NOTE: Use `docker run` only the first time that you run {product-name}. If you try it a second time, Docker
      will complain about the name `inception` already being in use. If you follow Docker`s suggestion
      to delete the container, you will loose all your {product-name} data. Further below, we explain how
      you can store your data outside the container in a folder on your host.
      
When you want to run {product-name} again later, use the command

[source,shell,subs="+attributes"]
----
$ docker start -ai inception
----

or for the background mode 

[source,shell,subs="+attributes"]
----
$ docker start inception
----

== Storing data on the host

If you follow the quick start instructions above, {product-name} will store all its data inside the docker
container. This is normally not what you want because as soon as you delete the container, all data
is gone. That means for example that you cannot easily upgrade to a new version of the {product-name}
docker image when one is released.

To store your data on your host computer, first create a folder where you want to store your data.
For example, if you are on Linux, you could create a folder `/srv/inception`:

----
$ mkdir /srv/inception
----

When you run {product-name} via Docker, you then mount this folder into the container:

[source,shell,subs="+attributes"]
----
$ docker run -it --name inception -v /srv/inception:/export -p8080:8080 inceptionproject/inception:{revnumber}
----

== Settings file

The dockerized {product-name} expects the `settings.properties` file in the `/export` folder. Instead of
injecting a custom `settings.properties` file into the container, it is strongly recommender to
use the instructions above (Storing data on the host) to mount a folder from the host system to 
`/export` then to place the into the mounted folder `settings.properties`. Thus, if you follow
the instructions above, the settings file would go to `/srv/inception/settings.properties` on the host
system.

== Connecting to a dedicated database

By default, {product-name} uses an embedded SQL database to store its metadata (not the texts,
annotations and knowledge bases, these are stored in files on disk). For production use, it is highly
recommended to use a dedicated database server (i.e. MariaDB or compatible) instead of the embedded
SQL database.

== Docker Compose

Using Docker Compose, you can manage multiple related containers. This section illustrates how to use
Docker Compose to jointly set up a {product-name} container as well as a database container (i.e. 
link:https://hub.docker.com/_/mariadb/[this one]).

The following Compose script sets these containers up.

[source,text,subs="+attributes"]
.Docker Compose script
----
include::scripts/docker-compose.yml[]
----

Place the script into any folder, change to that folder, and issue the following command to start
the containers.

[source,shell,subs="+attributes"]
----
$ docker-compose -p inception up -d
----

This will start two docker containers: `inception_db_1`, and `inception_app_1`. 
You can check the logs of each by running 

[source,shell,subs="+attributes"]
----
$ docker logs inception_db_1
$ docker logs inception_app_1
----

The actual name of these containers might vary. A list of running containers can be retrieved by

[source,shell,subs="+attributes"]
----
$ docker ps
----

The data of the containers will be stored in Docker volumes. If you shut the containers down and
start them again later, the data will still be there - try it out! 

[source,shell,subs="+attributes"]
----
$ docker-compose -p inception down
----

You can list the Docker volumes on your system using

[source,shell,subs="+attributes"]
----
$ docker volume ls
----

If you want to provide a custom `settings.properties` file, you can also choose to mount the data volume
to your hosts file system instead of to a Docker volume by setting the `INCEPTION_HOME` environment
variable to the path you want to store your data in and where you will also put the `settings.properties`
file. You can also choose to override the default location for the database data by setting the
`INCEPTION_DB_HOME` environment variable.

[source,shell,subs="+attributes"]
----
$ export INCEPTION_HOME=/srv/inception/app-data 
$ export INCEPTION_DB_HOME=/srv/inception/db-data
$ docker-compose -f docker-compose.yml -p inception up
----

If you are running Docker on Linux, the data of the volumes should end up on the file system anyway
in a special folder used by Docker. You can figure out which folder that is using 
`docker volume inspect ...`. However, if you are running Docker on macOS or Windows, the data is likely to
live in a special virtual machine that is owned by Docker and it will not be easily accessible unless
you mount the data to folders on your host.

NOTE: Mind that you cannot arbitrarily switch between volume-managed and host-stored data. Choose wisely.

=== Java options

You can pass additional options to the Java runtime by extending the `JAVA_OPTS` variable in the
Docker Compose script. To increase the available memory (RAM) to e.g. 4Gb, append `-Xmx4g`.

[source,shell,subs="+attributes"]
----
- JAVA_OPTS=-Dspring.jpa.properties.hibernate.dialect.storage_engine=innodb -Xmx4g
----

There is a lot more that you can do using Docker and Docker Compose. Please see the link:https://docs.docker.com/compose/[docker-compose reference] for details.
