// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= MariaDB

For production use of {product-name}, it is highly recommended to use a MariaDB database. In this 
section, we briefly describe how to install a MariaDB server and how to prepare it for use with 
the application.

== Prepare database

* Install MariaDB
+
[source,bash]
----
$ apt install mariadb-server
----

[[character-set-config]]
* When setting up your database make sure your MariaDB server is configured for 4-byte UTF-8
  character set and (`utf8mb4`) and a case sensitive collation (`utf8mb4_bin`) to ensure that all
  unicode characters can be represented (e.g. emojis).
+
[NOTE]
====
[%collapsible]
.Upgrading an existing database installation to 4 Byte UTF-8
=====
Changing the character-set and 
collation later can lead to serious trouble, so make sure you have a backup of your database. 
In that case, you might also need to perform some additional migration steps. We do not 
provide a database migration guide here, but if you search e.g. for `mariadb convert utf8 to 
utf8mb4`, you should find several.
=====
[%collapsible]
.Case-sensitive vs insensitive collation (`utf8mb4_bin` vs. `utf8mb4_unicode_ci`)
=====
If you search for UTF-8 support in MariaDB, you will generally find the recommendation to use `utf8mb4_unicode_ci` as the collation. This, however,is a *case-insensitive* collation. {product-name} is usually *case-sensitive*. If you used a case-insensitive collation in the database, you could not create two projects, one being
called `MY PROEJCT` and the other being called `my project`, but instead of a nice error from
{product-name}, you would get an ugly error from the database. That is why we recommend using
the case-sensitive `utf8mb4_bin` for the database.
=====
====
+
Check that the character set and collation are configured properly (in particular the items marked
with a `*` in the following table).
+
[source,bash]
----
$ mariadb -u root -p
MariaDB> SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name IN ('collation_database', 'collation_server');
+--------------------------+-------------+
| Variable_name            | Value       |
+--------------------------+-------------+
| character_set_client     | utf8mb4     | *
| character_set_connection | utf8mb4     | 
| character_set_database   | utf8mb4     | *
| character_set_filesystem | binary      | 
| character_set_results    | utf8mb4     |
| character_set_server     | utf8mb4     | *
| character_set_system     | utf8mb3     | 
| collation_database       | utf8mb4_bin | *
| collation_server         | utf8mb4_bin | *
+--------------------------+-------------+
----
+
If your settings differ, add following lines to your MariaDB config files (most likely 
`/etc/mysql/my.cnf` or in `/etc/mysql/mariadb.conf.d`):
+
[source,bash]
----
[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_bin
----
* now set up the `inception` database. First login to MariaDB
+
[source,bash]
----
$ mariadb -u root -p
----
* create a database
+
[source,mariadb]
----
MariaDB> CREATE DATABASE inception DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
----
* create a database user called `inception` with the password `t0t4llYSecreT` which is later used by the application to access the database (instructions for the `settings.properties` file in the <<sect_home_folder, Home Folder>> section).
+
[source,mariadb]
----
MariaDB> CREATE USER 'inception'@'localhost' IDENTIFIED BY 't0t4llYSecreT';
MariaDB> GRANT ALL PRIVILEGES ON inception.* TO 'inception'@'localhost';
MariaDB> FLUSH PRIVILEGES;
----

IMPORTANT: For production use, make sure you choose a different, secret, and secure password.

## Older MariaDB versions

Depending on the MariaDB version you are running, you might have to make additional settings.
You can check these settings using the following command. 

[source,bash]
----
$ mariadb -u root -p
MariaDB> * SHOW VARIABLES WHERE Variable_name IN ('innodb_large_prefix', 'innodb_file_format', 'innodb_file_per_table', 'innodb_strict_mode', 'innodb_default_row_format');
----

Depending on the result, you may have to add these settings to your MariaDB configuration files
(cf. link:https://mariadb.com/kb/en/innodb-system-variables/[InnoDB System Variables]):

[source,bash]
----
[mysqld]
innodb_large_prefix=true            # Removed in MariaDB 10.6.0
innodb_file_format=barracuda        # Removed in MariaDB 10.6.0
innodb_file_per_table=1             # Deprecated in MariaDB 11.0.1
innodb_strict_mode=1
innodb_default_row_format='dynamic'
innodb_snapshot_isolation=0         # Probably required with MariaDB >= 11.6.2
----


== JDBC connection options

This section explains some settings that can be added to the `database.url` in the 
`settings.properties` file when using MariaDB. Settings are separated from the host name and database name with a `?` character and multiple settings are separated using the `&` character, e.g.:

----
database.url=jdbc:mariadb://localhost:3306/inception?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
----

If use are using a non-SSL database connection append the
following setting to the `database.url`:

----
useSSL=false
----

You might also need to add the following if the respective connection error occurs:

----
allowPublicKeyRetrieval=true
----

Connections to the database may be rejected by the database server unless a timezone is specified.
The easiest way to do this is to add the following setting to the `database.url`: 

----
serverTimezone=UTC
----

For proper Unicode support, ensure that the database server and database connection are configured correctly:

* in the `settings.properties` file, make sure that `database.url` includes 
+
----
useUnicode=true&characterEncoding=UTF-8
----
