// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= MariaDB

For production use of {product-name}, it is highly recommended to use a MariaDB database. In this 
section, we briefly describe how to install a MariaDB server and how to prepare it for use with 
the application.

NOTE: MariaDB is an open-source drop-in replacement for MySQL. As a matter of fact, most of the commands and configuration files still use `mysql` in many places - so do not be confused if you read a lot about MySQL below despite working with MariaDB.

== Prepare database

* Install MariaDB
+
[source,bash]
----
$ apt-get install mariadb-server
----

[[character-set-config]]
* When first setting up your database make sure your MariaDB server is configured for 4 Byte UTF-8 (`utf8mb4`, `utf8mb4_bin`) to ensure that all unicode characters can be represented (e.g. emojis).
+
NOTE: *Upgrading an existing database installation to 4 Byte UTF-8:* Changing the character-set and collation later can lead to serious trouble, so make sure you have a backup of your database. In that case, you might also need to perform some additional migration steps. We do not provide a database migration guide here, but if you search e.g. for `mariadb convert utf8 to utf8mb4` (or `mysql` for that matter), you should find several.
+
NOTE: *`utf8mb4_bin` vs. `utf8mb4_unicode_ci`:* If you search for UTF-8 support in MariaDB, you will generally find the recommendation to use `utf8mb4_unicode_ci` as the collation. This, however, is a *case-insensitive* collation. {product-name} is usually *case-sensitive*. If you used a case-insensitive collation in the database, you could not create two projects, one being called `MY PROEJCT` and the other being called `my project`, but instead of a nice error from INCEpTION, you would get an ugly error from the database. That is why we recommend using the case-sensitive `utf8mb4_bin` for the database.
+
Check that `character-set-server`, `default-character-set` are set to `utf8mb4` and `collation-server` is set to `utf8mb4_unicode_ci` by logging into MariaDB with
+
[source,bash]
----
$ mysql -u root -p
----
+
and running
+
[source,mysql]
----
mysql> SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';
----
+
If this is not the case add the following lines to your MariaDB config file (most likely `/etc/mysql/my.cnf` or in `/etc/mysql/mariadb.conf.d`):
+
[source,bash]
----
[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_bin
innodb_large_prefix=true
innodb_file_format=barracuda
innodb_file_per_table=1
----
* now set up the `inception` database. First login to MariaDB
+
[source,bash]
----
$ mysql -u root -p
----
* create a database
+
[source,mysql]
----
mysql> CREATE DATABASE inception DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
----
* create a database user called `inception` with the password `t0t4llYSecreT` which is later used by the application to access the database (instructions for the `settings.properties` file in the <<sect_home_folder, Home Folder>> section).
+
[source,mysql]
----
mysql> CREATE USER 'inception'@'localhost' IDENTIFIED BY 't0t4llYSecreT';
mysql> GRANT ALL PRIVILEGES ON inception.* TO 'inception'@'localhost';
mysql> FLUSH PRIVILEGES;
----

IMPORTANT: For production use, make sure you choose a different, secret, and secure password.


== Configuration options

This section explains some settings that can be added to the `database.url` in the 
`settings.properties` file when using MariaDB. Settings are separated from the host name and database name with a `?` character and multiple settings are separated using the `&` character, e.g.:

----
database.url=jdbc:mariadb://localhost:3306/inception?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
----

To suppress the warning about non-SSL database connections with recent MySQL databases, append the
following setting to the `database.url`:

----
useSSL=false
----

You might also need to add the following if the respective connection error occurs:

----
allowPublicKeyRetrieval=true
----

Recent MySQL drivers may refuse to work unless a database server timezone has been specified. The
easiest way to do this is to add the following setting to the `database.url`: 

----
serverTimezone=UTC
----

If you plan to use 4 Byte UTF-8 encoding for project name and tagset/tag name, make sure both of the following settings for MySQL database are configured:

* in the `settings.properties` file, make sure that `database.url` includes 
+
----
useUnicode=true&characterEncoding=UTF-8
----
+
NOTE: If you use older versins of MariaDB or MySQL (< 8), you may have to set the following property in the `settings.properties` file:
+
----
spring.datasource.hikari.connectionInitSql=SET NAMES utf8mb4 COLLATE utf8mb4_bin;
----
* change the `my.conf` MariaDB database configuration file if necessary to use `utf8mb4` as default character set and `utf8mb4_bin` for collation (see <<character-set-config, Preparing the database>>).
