// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= HSQLDB (embedded)

{product-name} displays a warning in the user interface when an embedded database is being used. 
It is not recommended to used an embedded database for various reasons:

* HSQLDB databases are known to run a risk of becoming corrupt in case of power failures which may
  render the application inaccessible and your data difficult to recover.
* In very rare cases it may be necessary to fix the database content which is more inconvenient
  for embedded databases.

In case that you really want to run {product-name} with an embedded database in production, 
you probably want to disable this warning. To do so, please add the following entry to 
the `settings.properties` file:

----
warnings.embeddedDatabase=false
----

