// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= Running via embedded Tomcat (JAR)

The {product-name} standalone JAR with an embedded Tomcat server and can be easily set up as a UNIX service.
This is the recommended way of running {product-name} on a server.

The instructions below expect a Debian Linux system.
Details may vary on other OSes and Linux distributions.

== Installing as a service

To set it up as a service, you can do the following steps.
For the following example, we assume that you install {product-name} in `/srv/inception`:

* Copy the standalone JAR file `inception-app-standalone-{revnumber}.jar` to `/srv/inception/inception.jar`.
Note the change of the filename to `inception.jar`.
* Create the file `/srv/inception/inception.conf` with the following content
+
[source,text]
----
JAVA_OPTS="-Djava.awt.headless=true -Dinception.home=/srv/inception --add-modules jdk.incubator.vector --enable-native-access=ALL-UNNAMED"
----
+
NOTE: The `--add-modules` and `--enable-native-access` options are used by the search index.
Without them, {product-name} still works, but it logs warnings during startup and the vector
search runs more slowly. See <<sect_jvm_options>> for details.
+
* In the previous step, you have already created the `/srv/inception/settings.properties` file.
You *may optionally* configure the Tomcat port using the following line
+
[source,text]
----
server.port=18080
----
+
If you need to do additional configurations of the embedded Tomcat, best refer to the documentation of Spring Boot itself.
+
* We will run {product-name} as the user `www-data`.
Change the owner/group of `/srv/inception/inception.jar` to `www-data`.
**Do NOT run {product-name} as root.**
+
[source,bash]
----
$ chown www-data:www-data /srv/inception/inception.jar
----
+
* Make the JAR file executable:
+
[source,bash]
----
$ chmod +x /srv/inception/inception.jar
----
+
* Create a file `/etc/systemd/system/inception.service` with the following content:
+
[source,bash]
----
[Unit]
Description=INCEpTION

[Service]
User=www-data
WorkingDirectory=/srv/inception
EnvironmentFile=/srv/inception/inception.conf
ExecStart=/usr/bin/java $JAVA_OPTS -jar /srv/inception/inception.jar

[Install]
WantedBy=multi-user.target
----
+
* Enable the {product-name} service using
+
[source,bash]
----
$ systemctl enable inception
----
+
* Start {product-name} using
+
[source,bash]
----
$ systemctl start inception
----
+
* Check the log output
+
[source,bash]
----
$ journalctl -u inception
----
+
* Stop {product-name} using
+
[source,bash]
----
$ systemctl stop inception
----

NOTE: If you encounter strange errors, e.g. `+{status=203/EXEC}+`  and INCEpTION starts when directly executing the jar but not via systemd, then we recommend to disable SELinux.

[[sect_jvm_options]]
== Recommended JVM options

The search index (Apache Lucene) uses two modern JVM facilities that must be explicitly enabled.
Both options are JVM options, so they need to appear *before* the `-jar` argument on the command
line. In the service file shown above, `$JAVA_OPTS` is already placed accordingly, so adding them
to `inception.conf` is sufficient.

`--add-modules jdk.incubator.vector`::
  Enables the Vector API which is used to speed up vector-based (semantic) search. Without it,
  {product-name} logs `Java vector incubator module is not readable` during startup and falls back
  to a slower implementation. As the name suggests, this is still an *incubator* module and it must
  therefore be enabled explicitly.

`--enable-native-access=ALL-UNNAMED`::
  Permits the use of the foreign function and memory API which is used to access the index files.
  Without it, the JVM prints a `WARNING: A restricted method in java.lang.foreign.Linker has been
  called` message during startup. Note that future Java versions are expected to turn this warning
  into an error.
+
NOTE: `ALL-UNNAMED` is required here because {product-name} is started from an executable JAR, so
all classes are loaded into the unnamed module and the permission cannot be narrowed down further.

The {product-name} Docker image as well as the Windows and macOS installers already set these
options. They only need to be configured manually when running the standalone JAR.

== Loading extra Java libraries

When running an application from a fat JAR (i.e. using `java -jar ...`), there is no way that you can specify extra libraries for the application to load (e.g. a database driver).
Therefore,
{product-name} offers a special approach that works around this limitation.

In order to have the application load additional JAR files during startup, create a folder `lib` in the application home folder.
Place any JARs that you want to load into that folder.

To check if the loading works as expected, you can add the parameter `-Dloader.debug=true` when starting up {product-name}.