// Copyright 2020
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= Monitoring the {product-name} instance

== Available metrics

We expose some metrics of the running {product-name} instance via JMX. These are currently

* the number of active as well as enabled users
* the overall number of documents
* the number of enabled recommenders
* the number of annotation documents i.e. documents being annotated per user

To make the metrics available `spring.jmx.enabled=true`
and `monitoring.metrics.enabled=true` 
must be set in the `settings.properties` file 
(see <<sect_home_folder>> on this file).

== Setting up metrics exporter

To export the metrics so they can be queried by the monitoring solution https://prometheus.io/[Prometheus],
you can e.g. use https://github.com/prometheus/jmx_exporter[the JMX exporter] as a java agent.

The JMX exporter can be run as a .jar file that should be placed together with its `config.yml` 
file next to the {product-name} .jar file. An example `config.yml` file that exposes metrics from 
INCEpTION but not webanno brat metrics (metrics associated with brat rendering) and conforms JMX metric 
names to https://prometheus.io/docs/practices/naming/[Prometheus Naming conventions] is:

....
ssl: false
whitelistObjectNames: ["de.tudarmstadt.ukp.inception.recommendation.metrics:*", 
"de.tudarmstadt.ukp.clarin.webanno.api.dao.metrics:*", "de.tudarmstadt.ukp.clarin.webanno.security.metrics:*"]
blacklistObjectNames: ["de.tudarmstadt.ukp.clarin.webanno.brat.metrics:*"]
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: 'de.tudarmstadt.ukp.inception.recommendation.metrics<name=recommendationMetricsImpl, type=RecommendationMetricsImpl><>(\w+): (\d+)'
    name: inception_$1
    value: $2
    help: "Inception metric $1"
    type: GAUGE
    attrNameSnakeCase: true
  
  - pattern: 'de.tudarmstadt.ukp.clarin.webanno.([\.\w]+).metrics<name=(\w+), type=(\w+)><>(\w+): (\d+)'
    name: webanno_$4
    value: $5
    help: "Inception metric $4"
    type: GAUGE
    attrNameSnakeCase: true
....

The following line will run the JMX exporter for the JVM that runs the inception.jar. 
The exporter will expose the metrics on the http-endpoint _localhost:9404_.
Make sure to use a port, 9404 in this case, that is not open to the public 
(only to the local network that your Prometheus instance runs in).

....
java -javaagent:./jmx_prometheus_javaagent-0.13.0.jar=9404:config.yaml -jar inception.jar
....

The JMX exporter will also automatically expose JVM metrics in the `java.lang` namespace 
which can be used to e.g. monitor memory usage:

* _jvm_memory_bytes_used_: Used bytes of a given JVM memory area.
* _jvm_memory_bytes_committed_: Committed (bytes) of a given JVM memory area. This means (opposed to max memory) 
that this memory is available to the JVM.

and others.

== Scheduling
The default schedule for pulling of Prometheus is 10s, however it is necessary to make this a longer 
interval to avoid overwhelming your {product-name} instance with requests for metrics. 
You will need to do this in your Prometheus config file.

