// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= Internal annotation backup

{product-name} stores its annotations internally in files. Whenever a user 
performs an action on a document, the file is updated. It is possible to configure {product-name}
to keep internal backups of these files, e.g. to safeguard against certain types of crashes or bugs.

NOTE: This internal backup is not a replacement for a proper backup. It affects only the annotation
files - not the project data, knowledge bases, or other kinds of data. Also, the annotation data is
not directly re-usable by {product-name} without additional information that is contained in the 
database!

.Example internal backup
[source,text]
----
# Delete annotation backups older than 30 days (60 * 60 * 24 * 30 = 30 days)
backup.keep.time=2592000

# At least 5 minutes must pass between two annotation backups (60 * 5 = 5 minutes)
backup.interval=300

# Keep at most 10 backups for each annotation backup
backup.keep.number=10
----


The internal backups are controlled through three properties:

.Database settings in the `settings.properties` file
[cols="4*", options="header"]
|===
| Setting
| Description
| Default
| Example

| `backup.interval`
| Time between backups (seconds)
| `172800` _(60 * 60 * 24 = 24 hours)_
| `0` _(disabled)_

| `backup.keep.number`
| Maximum number of backups to keep
| `2`
| `0` _(unlimited)_

| `backup.keep.time`
| Maximum age of backups to keep (seconds)
| `0` _(unlimited)_
| `2592000` _(60 * 60 * 24 * 30 = 30 days)_
|===

The interval controls the minimum time between changes to a document that needs to have elapsed in
order for a new backup to be created. Setting the interval to `0` disables the internal backups.

When backups are enabled, either or both of the properties **backup.keep.number** and 
**backup.keep.time** should be changed as well, because their default values will cause the
backups to be stored indefinitely and they will eventually fill up the disk.

The properties **backup.keep.number** and **backup.keep.time** control how long backups are keep
and the maximal number of backups to keep. These settings are effective simultaneously.

.Example: Make backups every 5 minutes and keep 10 backups irrespective of age
----
backup.interval    = 300
backup.keep.number = 10
backup.keep.time   = 0
----

.Example: Make backups every 5 minutes and all not older than 7 days (60 * 60 * 24 * 7 seconds)
----
backup.interval    = 300
backup.keep.number = 0
backup.keep.time   = 604800
----

.Example: Make backups every 5 minutes and keep at most 10 backups that are not older than 7 days
----
backup.interval    = 300
backup.keep.number = 10
backup.keep.time   = 604800
----
