// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_installation]]
== Installation

=== Prerequisites

* This guide assumes Debian 9.1 (Stretch). It may also work on Ubuntu with some modifications, but we do not test this. Instructions for other Linux distributions likely deviate significantly.
* It is further assumed that the user "www-data" already exists on the system and that it shall be used to run the application.
* All commands assume that you are logged in as the *root* user. 

NOTE: If you cannot log in as root but have to use `sudo` to become root, then the recommended way to do that is using the command `sudo su -`.

=== Install Java 8

You can install an Oracle Java 8 JDK using the following commands.

[source,bash]
----
$ apt-get update
$ apt-get install dirmngr
$ echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee /etc/apt/sources.list.d/webupd8team-java.list
$ echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
$ apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
$ apt-get update
$ apt-get install oracle-java8-installer
$ apt-get install oracle-java8-set-default
----

=== Prepare database

For production use, it is highly recommended to use a MySQL database. In this section,
we briefly describe how to install a MySQL server and how to prepare it for use with {product-name}.

* Install MySQL
+
[source,bash]
----
$ apt-get install mysql-server
----
* make sure your MySQL server is configured for UTF-8. Check the following line is present in `/etc/mysql/mariadb.conf.d/50-server.cnf` (this is specific to Debian 9; on other systems the relevant file
may be `/etc/mysql/my.cnf`):
+
[source,bash]
----
character-set-server = utf8
collation-server     = utf8_bin
----
* also ensure the default settings for client connections to are UTF-8 in `/etc/mysql/mariadb.conf.d/50-server.cnf` (again Debian 9; likely in `/etc/mysql/my.cnf` on other systems)
+
[source,bash]
----
default-character-set = utf8
----
* login to MySQL
+
[source,bash]
----
$ mysql -u root -p
----
* create a database
+
[source,mysql]
----
mysql> CREATE DATABASE inception DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
----
* create a database user called `inception` with the password `t0t4llYSecreT` which is later used by the application to access the database (instructions for `settings.properties` file below).
+
[source,mysql]
----
mysql> CREATE USER 'inception'@'localhost' IDENTIFIED BY 't0t4llYSecreT';
mysql> GRANT ALL PRIVILEGES ON inception.* TO 'inception'@'localhost';
mysql> FLUSH PRIVILEGES;
----

IMPORTANT: For production use, make sure you choose a different, secret, and secure password.

=== Setting up the application home folder

The application home folder is the place where {product-name}'s configuration file `settings.properties`
resides and where the data is stored. Mind that if you are using a MySQL database server
(recommended), then some data is also stored in the MySQL database. This is important when
you plan to perform a backup, as both the home folder and the database content need to be
included in the backup.

Now, let's go through the steps of setting up the application home folder creating a
configuration file to access the previously created MySQL database.

* Create the application home folder. This is the directory where the settings files and projects (documents, annotations, etc.) are stored
+
[source,bash]
----
$ mkdir /srv/inception
----
* Edit `/srv/inception/settings.properties` to define the database connection:
+
[source,text]
----
database.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
database.driver=com.mysql.jdbc.Driver
database.url=jdbc:mysql://localhost:3306/inception?useSSL=false
database.username=inception
database.password=t0t4llYSecreT
----
+
* Fix permissions of the application home folder
+
[source,bash]
----
$ chown -R www-data /srv/inception
----

=== Running via embedded Tomcat

The {product-name} standalone JAR with an embedded Tomcat server and can be easily set up as a 
UNIX service. This is the recommended way of running {product-name} on a server.

==== Installing as a service

To set it up as a service, you can do the following steps. For the following
example, I assume that you install the application in `/srv/inception`:

* Copy the standalone JAR file +inception-app-standalone-{revnumber}.jar+ to `/srv/inception/inception.jar`.
   Note the change of the filename to `inception.jar`.
* Create the file `/srv/inception/inception.conf` with the following content
+
[source,text]
----
JAVA_OPTS="-Djava.awt.headless=true -Dinception.home=/srv/inception"
----
+
* In the previous step, you have already created the `/srv/inception/settings.properties` file. 
  You *may optionally* configure the Tomcat port using the following line
+
[source,text]
----
server.port=18080
----
+
If you need to do additional configurations of the embedded Tomcat, best refer to the 
documentation of Spring Boot itself.
+
* Make sure that the file `/srv/inception/inception.conf` is owned by the root user. If this is
  not the case, it will be ignored and any settings made there will not have any effect. If
  you start the application and instead of using the MySQL database, it is using an embedded database,
  then you should double-check that `/srv/inception/inception.conf` is owned by the root user.
+
[source,bash]
----
$ chown root:root /srv/inception/inception.conf
----
+
* Change the owner/group of `/srv/inception/inception.jar` to `www-data`. When the service is started,
  it will run with the privileges of the user that owns the JAR file, i.e. in this case the application
  will run as under the `www-data` user.
+
[source,bash]
----
$ chown www-data:www-data /srv/inception/inception.jar
----
+
* Create a symlink from `/etc/init.d` to the `/srv/inception/inception.jar`:
+
[source,bash]
----
$ ln -s /srv/inception/inception.jar /etc/init.d/inception
----
+
* Start {product-name} using
+
[source,bash]
----
$ service inception start
----
+
* Stop {product-name} using
+
[source,bash]
----
$ service inception stop
----

==== Running the standalone behind HTTPD

These are *optional* instructions if you want to run the application behind an Apache web-server instead
of accessing it directly. This assumes that you already have the following packages installed:

* Apache Web Server
* mod_proxy
* mod_proxy_ajp

* Add the following lines to `/srv/inception/settings.properties`:
+
[source,text]
----
tomcat.ajp.port=18009
server.contextPath=/inception
server.use-forward-headers=true
----
+
* Edit `/etc/apache2/conf.d/inception.local.conf`
+
[source,xml]
----
ProxyPreserveHost On

<Proxy ajp://localhost/inception >
  Order Deny,Allow
  Deny from none
  Allow from all
</Proxy>

<Location /inception >
  ProxyPass ajp://localhost:18009/inception timeout=1200
  ProxyPassReverse http://localhost/inception
</Location>
----
* Restart Apache web server
+
[source,bash]
----
$ service apache2 restart
----
