// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= MySQL

For production use of {product-name}, it is highly recommended to use a MySQL database. In this 
section, we briefly describe how to install a MySQL server and how to prepare it for use with 
the application.

== Prepare database

* Install MySQL
+
[source,bash]
----
$ apt-get install mysql-server
----

[[character-set-config]]
* make sure your MySQL server is configured for 4 Byte UTF-8 (utf8mb4) to ensure that all unicode characters can be represented (e.g. emojis). In MySQL versions 8 and upwards, this is the default. Check that `character-set-server`, `default-character-set` are set to  `utf8mb4` and `collation-server` is set to `utf8mb4_unicode_ci` by logging into MySQL with
+
[source,bash]
----
$ mysql -u root -p
----
and running
+
[source,mysql]
----
mysql> SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';
----
+
If this is not the case add the following lines to your MySQL config file (most likely `/etc/mysql/my.cnf` or in `/etc/mysql/mariadb.conf.d`):
+
[source,bash]
----
[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
innodb_large_prefix=true
innodb_file_format=barracuda
innodb_file_per_table=1
----
* now set up the `inception` database. First login to MySQL
+
[source,bash]
----
$ mysql -u root -p
----
* create a database
+
[source,mysql]
----
mysql> CREATE DATABASE inception DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
----
* create a database user called `inception` with the password `t0t4llYSecreT` which is later used by the application to access the database (instructions for the `settings.properties` file in the <<sect_home_folder, Home Folder>> section).
+
[source,mysql]
----
mysql> CREATE USER 'inception'@'localhost' IDENTIFIED BY 't0t4llYSecreT';
mysql> GRANT ALL PRIVILEGES ON inception.* TO 'inception'@'localhost';
mysql> FLUSH PRIVILEGES;
----

IMPORTANT: For production use, make sure you choose a different, secret, and secure password.


== Configuration options

This section explains some settings that can be added to the `database.url` in the 
`settings.properties` file when using MySQL. Settings are separated from the host name and database
name with a `?` character and multiple settings are separated using the `&` character, e.g.:

----
database.url=jdbc:mysql://localhost:3306/inception?useSSL=false&serverTimezone=UTC
----

To suppress the warning about non-SSL database connections with recent MySQL databases, append the
following setting to the `database.url`:

----
useSSL=false
----

You might also need to add the following if the respective connection error occurs:

----
allowPublicKeyRetrieval=true
----

Recent MySQL drivers may refuse to work unless a database server timezone has been specified. The
easiest way to do this is to add the following setting to the `database.url`: 

----
serverTimezone=UTC
----

If you plan to use 4 Byte UTF-8 encoding for project name and tagset/tag name, make sure both of the following settings for MySQL database are configured:

* in the `settings.properties` file, make sure that `database.url` includes 
+
----
useUnicode=true&characterEncoding=UTF-8
----
+
and you set the following property for MySQL versions below 8
+
----
spring.datasource.hikari.connectionInitSql=SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
----
* change the `my.conf` MySQL database configuration file if necessary to use `utf8mb4` as default character set and `utf8mb4_unicode_ci` for collation (see <<character-set-config, Preparing the database>>).
