// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_home_folder]]
= Application home folder

The {product-name} home folder is the place where {product-name}'s configuration file `settings.properties`
resides and where {product-name} stores its data. The `settings.properties` file is not automatically created by the application 
and needs to be created manually in the case that settings need to be configured.
Mind that if you are using a dedicated database server
(recommended), then {product-name} also stores some data in the dedicated database. This is important when
you plan to perform a backup, as both the home folder and the database content need to be
included in the backup.

Now, let's go through the steps of setting up a home folder for {product-name} and creating a
configuration file instructing {product-name} to access a dedicated <<sect_database,database>>.

* Create {product-name} home folder. This is the directory where {product-name} settings files and projects (documents, annotations, etc.) are stored
+
[source,bash]
----
$ mkdir /srv/inception
----
////
// FIXME How to reference to sample data?
* *Optional* If you want to test {product-name} with some sample data, skip the _Users and permissions_ section and follow the instruction at [Sampledata], then come back here.
////
* Create and edit `/srv/inception/settings.properties` to define the database connection as well as internal backup properties:
+
[source,text]
----
database.url=jdbc:mariadb://localhost:3306/inception?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
database.username=inception
database.password=t0t4llYSecreT

# 60 * 60 * 24 * 30 = 30 days
backup.keep.time=2592000

# 60 * 5 = 5 minutes
backup.interval=300

backup.keep.number=10
----
+
* Fix permissions in {product-name} home folder
+
[source,bash]
----
$ chown -R www-data:www-data /srv/inception
----


