// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_recommender_tutorial]]
= Implementing a custom recommender

This section describes the overall design of internal recommenders in {product-name} and gives a
tutorial on how to implement them. Internal recommenders are created by implementing relevant 
Java interfaces and are added via Maven dependencies. These are then picked up during application
startup by the Spring Framework.

For this tutorial, we will add a recommender for named entities that uses the data majority label for
predicting, i.e. it predicts always the label that appears most often in the training data. The full
code for this example can be found in the **inception-example-imls-data-majority** module.

== Setting up the environment

To get started, check out the most recent source code of {product-name} from
https://github.com/inception-project/inception[Github] and import it as a Maven project in the IDE
of your choice. Add a new module to the INCEpTION project itself, we will call it
**inception-example-imls-data-majority**.

In the root `pom.xml` of the {product-name} project, add your recommender as a dependency. Update 
the version of the dependency entry you just created to the version you find in the _pom.xml_ of the
{product-name} project. It should look like this:

[source,xml,indent=0,subs="+attributes"]
----
<dependencies>
…
    <dependency>
        <groupId>de.tudarmstadt.ukp.inception.app</groupId>
        <artifactId>inception-imls-data-majority</artifactId>
        <version>{revnumber}</version>
    </dependency>
…
</dependencies>
----

Add the same entry in `inception-app-webapp`, but omit the version number. It then uses automatically the
version in the parent POM file. Also add it to `usedDependencies` there.

To add a new recommender to INCEpTION, two classes need to be created. These are
described in the following.

== Implementing the RecommendationEngine

Recommenders give suggestions for possible annotations to the user. In order to do that,
they need to be able be to trained on existing annotations, predict annotations in a document and
be evaluated for a performance estimate. This is what the `RecommendationEngine` abstract class is for.
It defines the methods that are used to train, test and evaluate a machine learning algorithm and offers
several helper methods. Instances of this class often wrap external machine learning packages like
https://opennlp.apache.org/[OpenNLP] or https://deeplearning4j.org/[Deeplearning4j].

Recommenders in {product-name} heavily rely on https://uima.apache.org[Apache UIMA] types and features.
A recommender is configured for a certain layer and a certain feature. A layer can be seen as the
type of annotation you want to to, e.g. `POS`, `NER`. Layers correspond to UIMA types. A feature is
one piece of information that should be annotated, e.g. the POS tag. One layer can have many features.
When extending `RecommendationEngine`, the predicted layer/type can be obtained by `getPredictedType`,
the feature to predict respectively by `getPredictedFeature`.

Annotations are given to a recommender in the form of a
http://uima.apache.org/d/uimaj-current/apidocs/index.html[UIMA CAS]. One CAS corresponds to one
document in INCEpTION. Annotations from a CAS can be read and manipulated via the
https://uima.apache.org/d/uimafit-current/api/org/apache/uima/fit/util/CasUtil.html[CasUtil].

We start by creating a new class `de.tudarmstadt.ukp.inception.recommendation.imls.datamajority.DataMajorityNerRecommender` that implements `RecommendationEngine`.
Please see the JavaDoc of the respective methods for their semantics.

.Class and member definition for the DataMajorityNerRecommender
[source,java,indent=0]
----
include::{source-dir}inception-example-imls-data-majority/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommender.java[tags=classDefinition]

include::{source-dir}inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommendationEngine.java[tags=methodDefinition]

include::{source-dir}inception-example-imls-data-majority/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommender.java[tags=utility]
}
----

For the constructor, we take the `Recommender` object which contains the recommender configuration,
e.g. the layer and the name of the feature to recommend. The next step is to implement the required
methods.

`DataMajorityModel` and `Annotation` are internal data classes to simplify the code.

=== RecommenderContext

Instances of https://github.com/inception-project/inception/blob/master/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommenderContext.java[RecommendationEngine] itself are stateless. If data like trained models need to be
saved and loaded, it can be saved in the `RecommenderContext` that is given in the interface methods.
When needed again, e.g. for prediction, it then can be loaded again. The `Key` class is used in order
to ensure type safety.

=== Training

Training consists of extracting annotations followed by training and saving the model. The 
platform needs to know whether the recommender is ready for prediction, this is done by 
overriding `RecommendationEngine::isReadyForPrediction`.

.Training routine
[source,java,indent=0]
----
include::{source-dir}inception-example-imls-data-majority/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommender.java[tags=train]
----

Extracting annotations itself is done by iterating over all documents and selecting all annotations
for each. Here, we need to use the layer name and feature for which the recommender is configured
to extract the correct annotations.

.Extracting annotations from the documents
[source,java,indent=0]
----
include::{source-dir}inception-example-imls-data-majority/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommender.java[tags=extractAnnotations]
----

The training itself is done by counting the number of occurrences for each label that was seen in the
documents. The label is then the one which occurred the most in the training documents.

.Training the model
[source,java,indent=0]
----
include::{source-dir}inception-example-imls-data-majority/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommender.java[tags=trainModel]
----

We also compute a dummy score here which is displayed in the UI and used for e.g. active learning.

=== Predicting

The first thing we do when predicting is to load the model we saved during training. For every
candidate in the document, we assign the majority label, create a new annotation and add it to the `CAS`.
From there, it will be read by {product-name} and displayed to the user.

.Predicting annotations for a CAS
[source,java,indent=0]
----
include::{source-dir}inception-example-imls-data-majority/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommender.java[tags=predict1]
----

For a document, we consider possible candidates for a named entity to be tokens that are upper case.
In a real recommender, the step of candidate extraction should be more elaborate than that, but for this
tutorial, it is sufficient.

When making predictions, we also set the score feature to put a number on the quality of the annotation.
The UIMA score feature to set can be obtained by calling `getScoreFeature` inside a `RecommendationEngine`.
When creating predictions, make sure to call `annotation.setBooleanValue(isPredictionFeature, true);` so
that {product-name} knows it is a prediction, not a real annotation. In addition, we provide an explanation for
the score through the UIMA feature obtained by calling `getScoreExplanationFeature` inside a `RecommendationEngine`.

.Making the predictions
[source,java,indent=0]
----
include::{source-dir}inception-example-imls-data-majority/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommender.java[tags=predict2]
----

We use the dummy score here from the training as the recommender score.

=== Evaluating

When configuring a recommender, it can be specified that it needs to achieve a certain score
before the recommendations are shown to the user. For that, the platform regularly evaluates 
recommenders in the background. We use macro-averaged F1-score as an evaluation score.  
In code, the evaluation is implemented in the `evaluate` method.

Evaluation is done on a set of documents. In order to properly divide the annotations into training
and test set, a `DataSplitter` is given which tells you to which data set an annotation belongs.

For the actual evaluation, we collect the true label and the predicted majority label in a 
`LabelPair` for each true label. A stream of these instances can then be collected with 
the use of an `EvaluationResultCollector` as an `EvaluationResult` object - the result of the 
evaluation. This object provides access to calculations for token-based accuracy, macro-averaged 
precision, recall and F1-score. This F1-score is later used for 
comparison with the user-defined threshold to activate the recommender.
 

.Evaluating the recommender
[source,java,indent=0]
----
include::{source-dir}inception-example-imls-data-majority/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommender.java[tags=evaluate]
----


== RecommendationFactory

The `RecommendationFactory` is used to create a new recommender instance. It also defines for which
types of layers and features the recommender itself can be used. Here, we decided to only support
token span layers without cross sentence annotations.

.The RecommendationFactory
[source,java,indent=0]
----
include::{source-dir}inception-example-imls-data-majority/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityRecommenderFactory.java[tags=classDefinition]
----


