// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_formats_uimajson_legacy]]
= 🪦 UIMA CAS JSON

====
CAUTION: Legacy feature. To use this functionality, you need to enable it first by adding `format.json-cas-legacy.enabled=true` to the `settings.properties` file. 

Support for this feature will be removed in a future version. The replacement is <<sect_formats_uimajson>>.
====

This is an old and deprecated UIMA CAS JSON format which can be exported but not imported.
It should no longer be used. Instead, one should turn to <<sect_formats_uimajson>>.

The format does support custom layers.

For more details on this format, please refer to the link:https://uima.apache.org/d/uimaj-current/references.html#ugr.ref.json[UIMA Reference Guide].

By default, the format writes all values to the JSON output, even if the values are the default values
in JSON (e.g. `0` for numbers or `false` for booleans). You can configure this behavior by setting
`format.json-cas-legacy.omit-default-values` to `true` or `false` (default) respectively.

[cols="2,1,1,3"]
|====
| Format | Import | Export | Supported layers

| link:https://uima.apache.org/d/uimaj-current/references.html#ugr.ref.json[UIMA CAS JSON (legacy)] (`json`)
| no
| yes
| All built-in and custom layers
|====
