apiVersion: v1
kind: Service
metadata:
   name: inception-svc
   labels:
     app: inception
spec:
   type: NodePort
   ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
     nodePort: 32000
   selector:
     app: inception