[[sect_external-search-repos-elasticsearch]]
= ElasticSearch

Selecting the **ElasticSearch** repository type allows connecting to remote ElasticSearch instances.

In order to set up a connection to an ElasticSearch repository, the following information needs to
be provided:

* *URL*: the URL where the ElasicSearch instance is running (e.g. `http://localhost:9200/`
* *Index Name*: the name of the index within the instance (e.g. `mycorpus`)
* *Search path*: the suffix used to access the searching endpoint (usually `_search`)
* *Object type*: the endpoint used to download the full document text

From this information, two URLs are constructed:

* the search URL: `<URL>/<index name>/<search path>`
* the document retrieval URL as: `<URL>/<index name>/<object type>/<document id>`

The *remote order* setting allows to switch the ranking of results from the default ranking used by
the ElasticSearch server to a random order. The documents returned will still match the query, but
the order does not correspond to the matching quality anymore. When random ordering is enabled, no
score is associated with the search results. If desired, the *random seed* used for the ordering
can be customized.
