// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_installation]]
== Installation

=== Prerequisites

* This guide assumes Debian 8.0.0 (Jessie). It may also work on Ubuntu with some modifications, but we do not test this. Instructions for other Linux distributions likely deviate significantly.
* It is further assumed that the user "www-data" already exists on the system and that it shall be used to run WebAnno. Finally, it is expected that you have set up a MySQL database that WebAnno can use. 
* All commands assume that you are logged in as the *root* user. 

NOTE: If you cannot log in as root but have to use `sudo` to become root, then the recommended way to do that is using the command `sudo su -`.

=== Install Java 8

You can install an Oracle Java 8 JDK using the following commands.

[source,bash]
----
$ echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee /etc/apt/sources.list.d/webupd8team-java.list
$ echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
$ apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
$ apt-get update
$ apt-get install oracle-java8-installer
$ apt-get install oracle-java8-set-default
----

=== Prepare database

* Install MySQL
+
[source,bash]
----
$ sudo apt-get install mysql-server
----
* make sure your MySQL server is configured for UTF-8. Check the following line is present in `/etc/mysql/my.cnf`:
+
[source,bash]
----
character-set-server = utf8
----
* login to MySQL
+
[source,bash]
----
$ mysql -u root -p
----
* create a database
+
[source,mysql]
----
mysql> CREATE DATABASE webanno DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
----
* create a database user called `webanno` with the password `t0t4llYSecreT` which is later used by the application to access the database (instructions for `settings.properties` file below).
+
[source,mysql]
----
mysql> CREATE USER 'webanno'@'localhost' IDENTIFIED BY 't0t4llYSecreT';
mysql> GRANT ALL PRIVILEGES ON webanno.* TO 'webanno'@'localhost';
----

IMPORTANT: For production use, make sure you choose a different, secret, and secure password.

=== Dedicated Tomcat instance

* Install package to install user-instances of Tomcat. 
+
[source,bash]
----
$ aptitude install tomcat8-user authbind
----
* Create new instance
+
[source,bash]
----
$ cd /opt
$ tomcat8-instance-create -p 18080 -c 18005 webanno
$ chown -R www-data /opt/webanno
----

NOTE: If WebAnno is the only application you install on your server, then you can also have WebAnno running on port 80 or port 443. In that case, substitute all instances of port `18080` in these
guidelines with the respective port. Mind that running via SSL on port 443 requires additional steps that we have not yet documented. Ports lower than 1024 are privileged and the WebAnno init script will automatically use a tool called *authbind* to allow WebAnno to operate on these ports as the unprivileged www-data user.

* Configure the startup script. Edit `/etc/init.d/webanno` and add the following contents or just download the file from link:admin-guide/scripts/webanno[here] and place it in `/etc/init.d`.
+
[source,bash]
----
include::scripts/webanno[]
----
* Make the script executable and register it to run during system start:
+
[source,bash]
----
$ chmod +x /etc/init.d/webanno
$ update-rc.d webanno defaults
----

Now we have a dedicated Apache Tomcat instance for WebAnno installed at `/opt/webanno/` that automatically starts when the system boots and that can be managed through the usual `service` commands.

=== Deploy WAR file

* Place the WebAnno WAR into the Tomcat `webapps` folder:
+
[source,bash,subs="+attributes"]
----
$ cp webanno-webapp-{revnumber}.war /opt/webanno/webapps/webanno.war
----
+
NOTE: Mind that the copy command above renames the WAR file to `webanno.war`! This is important so that WebAnno is accessible at the URL noted later in the present guidelines.
* Create WebAnno home folder. This is the directory where webanno settings files and projects (Serialized Cases, Source documents...) are stored
+
[source,bash]
----
$ mkdir /srv/webanno
----
////
// FIXME How to reference to sample data?
* *Optional* If you want to test WebAnno with some sample data, skip the _Users and permissions_ section and follow the instruction at [Sampledata], then come back here.
////
* Edit `/srv/webanno/settings.properties` to define the database connection as well as internal backup properties and enable/disable crowd sourcing component:
+
[source,text]
----
database.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
database.driver=com.mysql.jdbc.Driver
database.url=jdbc:mysql://localhost:3306/webanno
database.username=webanno
database.password=t0t4llYSecreT

# 60 * 60 * 24 * 30 = 30 days
backup.keep.time=1000000

# 60 * 5 = 5 minutes
backup.interval=1000

backup.keep.number=10

ui.brat.sentences.number = 5
----
+
NOTE: If you are using MySQL 5.5.45{plus}, 5.6.26{plus} or 5.7.6{plus}, you may have to append `?useSSL=false` to the `database.url` value.
* Fix permissions in WebAnno home folder
+
[source,bash]
----
$ chown -R www-data /srv/webanno
----
* Start WebAnno
+
[source,bash]
----
$ service webanno start
----
* Open it with your browser at `http://localhost:18080/webanno`. If you chose to run WebAnno behind the Apache web-server use `http://localhost/webanno`.
The first time, it will create a username admin with password admin. login with this username and proceed.

You can start with the SampleProjects to explore some of the functionalities.

=== Running behind Apache HTTPD

These are *optional* instructions if you want to run WebAnno behind an Apache web-server instead of accessing it directly. This assumes that you already have the following packages installed:

* Apache Web Server
* mod_proxy
* mod_proxy_ajp

* Edit `/opt/webanno/conf/server.xml` and enable AJP Connector on localhost (comment in, add address, and change port
+
[source,xml]
----
<Connector port="18009" protocol="AJP/1.3" redirectPort="8443" address="127.0.0.1"/>
----
* Disable HTTP Connector (just comment it out)
+
[source,xml]
----
<!--Connector port="8080" protocol="HTTP/1.1".
           connectionTimeout="20000".
           URIEncoding="UTF-8"
           redirectPort="8443" /-->
----
* Edit `/etc/apache2/conf.d/webanno.local`
+
[source,xml]
----
ProxyPreserveHost On

<Proxy ajp://localhost/webanno >
  Order Deny,Allow
  Deny from none
  Allow from all
</Proxy>

<Location /webanno >
  ProxyPass ajp://localhost:18009/webanno timeout=1200
  ProxyPassReverse http://localhost/webanno
</Location>
----
* Restart Apache web server
+
[source,bash]
----
$ service apache2 restart
----
