[[sect_installation]]
== Installation

=== Prerequisites

  * This guide assumes Debian 6.0.0 (Squeeze). It may also work on Ubuntu with some modifications, but we do not test this. Instructions for other Linux distributions likely deviate significantly.
  * It is further assumed that the user "www-data" already exists on the system and that it shall be used to run WebAnno. Finally, it is expected that you have set up a MySQL database that WebAnno can use. 
  * All commands assume that you are logged in as the *root* user.

=== Prepare database

   * Install MySQL
----
$ sudo apt-get install mysql-server
----
   * login to MySQL
----
$ mysql -u root -p
----
   * Create databases
----
mysql> CREATE DATABASE webanno DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
----
   * create a database user called `webanno` with the password `t0t4llYSecreT`which is later used by the application to access the database (instructions for `settings.properties`file below).
----
mysql> CREATE USER 'webanno'@'localhost' IDENTIFIED BY 't0t4llYSecreT';
mysql> GRANT ALL PRIVILEGES ON webanno.* TO 'webanno'@'localhost';
----

=== Dedicated Tomcat instance

   * Install Tomcat. 
----
$ aptitude install tomcat6
----
   * Install package to install user-instances of Tomcat. 
----
$ aptitude install tomcat6-user
----
   * Create new instance
----
$ cd /opt
$ tomcat6-instance-create -p 18080 -c 18005 webanno
$ chown -R www-data /opt/webanno
----
Now we have the /opt/webanno/ apache tomcat installation. You will put the <font color="red"> *webanno.war*</font>  file in the /opt/webanno/webapps/ folder. If you get the war file in different name, such as Webanno-1.1-beta-10.war, *PLEASE RE-NAME IT TO* <font color="red">*webanno.war*</font>
   * Configure the startup script. Edit `/etc/init.d/webanno` and add the following contents:
----
#!/bin/sh
export JAVA_OPTS="-Djava.awt.headless=true -Xmx750m -XX:+UseConcMarkSweepGC -Dwebanno.home=/srv/webanno"

case "$1" in
start)
su -c "sh /opt/webanno/bin/startup.sh" www-data
;;

stop)
su -c "sh /opt/webanno/bin/shutdown.sh" www-data
;;

restart)
su -c "sh /opt/webanno/bin/shutdown.sh" www-data
su -c "sh /opt/webanno/bin/startup.sh" www-data
;;
esac

exit 0
----
   * Make the script executable and register it to run during system start:
----
$ chmod +x /etc/init.d/webanno
$ update-rc.d webanno defaults
----

=== Deploy WAR file

   * Place the WebAnno WAR into the Tomcat `webapps` folder:
----
$ cp webanno.war /opt/webanno/webapps/webanno.war
----
   * Create WebAnno home folder. This is the directory wher webanno settings files and projects (Serialized Cases, Source documents...) are stored
----
$ mkdir /srv/webanno
----
// FIXME How to reference to sample data?
   * *Optional* If you want to test WebAnno with some sample data, skip the _Users and permissions_ section and follow the instruction at [Sampledata], then come back here.
   * Edit `/srv/webanno/settings.properties` to define the database connection as well as internal backup properties and enable/disable crowd sourcing component:
----
database.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
database.driver=com.mysql.jdbc.Driver
database.url=jdbc:mysql://localhost:3306/webanno
database.username=webanno
database.password=t0t4llYSecreT

# 60 * 60 * 24 * 30 = 30 days
backup.keep.time=1000000

# 60 * 5 = 5 minutes
backup.interval=1000

backup.keep.number=10
----
   * Fix permissions in WebAnno home folder
----
$ chown -R www-data /srv/webanno
----
   * Start WebAnno
----
$ service webanno start
----
   * Open it with your browser at `http://localhost:18080/webanno`. If you chose to run WebAnno behind the Apache web-server use `http://localhost/webanno`.
The first time, it will create a username admin with password admin. login with this username and proceed.

You can start with the SampleProjects to explore some of the functionalities.

=== Running behind Apache HTTPD

These are *optional* instructions if you want to run WebAnno behind an Apache web-server instead of accessing it directly. This assumes that you already have the following packages installed:

   * Apache Web Server
   * mod_proxy
   * mod_proxy_ajp

   * Edit `/opt/webanno/conf/server.xml`
      * Enable AJP Connector on localhost (comment in and add address)
----
<Connector port="38009" protocol="AJP/1.3" redirectPort="8443" address="127.0.0.1"/>
----
      * Disable HTTP Connector (just comment it out)
----
<!--Connector port="38080" protocol="HTTP/1.1".
           connectionTimeout="20000".
           URIEncoding="UTF-8"
           redirectPort="8443" /-->
----
   * Edit `/etc/apache2/conf.d/webanno.local`
----
ProxyPreserveHost On

<Proxy ajp://localhost/webanno >
  Order Deny,Allow
  Deny from none
  Allow from all
</Proxy>

<Location /webanno >
  ProxyPass ajp://localhost:18009/webanno timeout=1200
  ProxyPassReverse http://localhost/webanno
</Location>
----
   * Restart Apache web server
----
$ sudo /etc/init.d/apache2 restart
----
