// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_formats_imscwb]]
= IMS CWB (aka VRT)

The "verticalized XML" format used by the link:http://cwb.sourceforge.net[IMS Open Corpus Workbench], 
a linguistic search engine. It uses a tab-separated format with limited markup (e.g. for sentences, 
documents, but not recursive structures like parse-trees). In principle, it is a generic format - 
i.e. there can be arbitrary columns, pseudo-XML elements and attributes. However, support is limited
to a specific set of columns that must appear exactly in a specific order: *token text*, 
*part-of-speech tag*, *lemma*. Also only specific pseudo-XML elements and attributes are supported:
`text` (including an `id` attribute), `s`.

[cols="2,1,1,3"]
|====
| Format | Import | Export | Supported layers

| IMS CWB VRT (`imscwb`)
| yes
| no
| Part-of-speech tagging (built-in), +
  Lemmatization (built-ion)
|====

.Example
[source,text,tabsize=0]
----
<text id="http://www.epguides.de/nikita.htm">
<s>
Nikita	NE	Nikita
(	$(	(
La	FM	La
Femme	NN	Femme
Nikita	NE	Nikita
)	$(	)
Dieser	PDS	dies
Episodenführer	NN	Episodenführer
wurde	VAFIN	werden
von	APPR	von
September	NN	September
1998	CARD	1998
bis	APPR	bis
Mai	NN	Mai
1999	CARD	1999
von	APPR	von
Konstantin	NE	Konstantin
C.W.	NE	C.W.
Volkmann	NE	Volkmann
geschrieben	VVPP	schreiben
und	KON	und
im	APPRART	im
Mai	NN	Mai
2000	CARD	2000
von	APPR	von
Stefan	NE	Stefan
Börzel	NN	Börzel
übernommen	VVPP	übernehmen
.	$.	.
</s>
</text>
----

