// Copyright 2019
// Ubiquitous Knowledge Processing (UKP) Lab
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

== WebLicht

In order to create a WebLicht recommender, you first need to obtain an API key: https://weblicht.sfs.uni-tuebingen.de/WaaS/apikey

Next, log in to WebLicht to build a processing chain: https://weblicht.sfs.uni-tuebingen.de/

Start with one of the example documents. Then build you pipeline using either the easy or advanced
modes. Once you are done, use the  **Download chain** button to download the processing chain
definition.

Now, create a new WebLicht recommender in {product-name}. Enter the API key you obtained in the 
previous step. Before you can upload the process chain definition file, you need to save the recommender.