/* Generated By:JJTree: Do not edit this line. ASTConditions.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.tudarmstadt.ukp.clarin.webanno.constraints.grammar;

import java.util.ArrayList;
import java.util.List;

public class ASTConditions
    extends SimpleNode
{
    private List<ASTCondition> conditions = new ArrayList<>();

    public ASTConditions(int id)
    {
        super(id);
    }

    public ASTConditions(ConstraintsParser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(ConstraintsParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public void addCondition(ASTCondition aCondition)
    {
        conditions.add(aCondition);
    }

    public List<ASTCondition> getConditions()
    {
        return conditions;
    }
}
/* JavaCC - OriginalChecksum=bd289650a6242f546937a488c651af3b (do not edit this line) */
