/* Generated By:JJTree: Do not edit this line. ASTRestrictions.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.tudarmstadt.ukp.clarin.webanno.constraints.grammar;

import java.util.ArrayList;
import java.util.List;

public class ASTRestrictions
    extends SimpleNode
{
    private List<ASTRestriction> restrictions = new ArrayList<>();

    public ASTRestrictions(int id)
    {
        super(id);
    }

    public ASTRestrictions(ConstraintsParser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(ConstraintsParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public void addRestriction(ASTRestriction aRestriction)
    {
        restrictions.add(aRestriction);
    }

    public List<ASTRestriction> getRestrictions()
    {
        return restrictions;
    }
}
/* JavaCC - OriginalChecksum=74067aaef39362920668db5a81d6104b (do not edit this line) */
