/* Generated By:JJTree: Do not edit this line. ASTRestriction.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.tudarmstadt.ukp.clarin.webanno.constraints.grammar;

public class ASTRestriction
    extends SimpleNode
{
    private ASTPath path;
    private String value;
    private boolean important;

    public ASTRestriction(int id)
    {
        super(id);
    }

    public ASTRestriction(ConstraintsParser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(ConstraintsParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public ASTPath getPath()
    {
        return path;
    }

    public void setPath(ASTPath aPath)
    {
        path = aPath;
    }

    public String getValue()
    {
        return value;
    }

    public void setValue(String aValue)
    {
        value = aValue;
    }

    public void setImportant(boolean important)
    {
        this.important = important;
    }

    public boolean isImportant()
    {
        return important;
    }
}
/* JavaCC - OriginalChecksum=bf92f16ef90548b7e7e55f144af991a4 (do not edit this line) */
