env:
  browser: true
  es2021: true
  mocha: true
extends:
  - standard
  - plugin:svelte/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  extraFileExtensions: ['.svelte']
plugins:
  - '@typescript-eslint'
  - 'chai-friendly'
overrides:
  - files: ['*.svelte']
    parser: svelte-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
rules: {
  "no-unused-expressions": 0,
  "chai-friendly/no-unused-expressions": 2
}
