// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

=== Version 3.2.x to 3.3.0

* When upgrading from 3.2.x or earlier to 3.3.0 or later, Automation projects break.

=== Version 2.3.1 to 3.0.0

* The access permissions of administrators have changed. Administrators can no longer access
  annotation, curation, and monitoring pages for all projects. They can only access them if they
  are annotators, managers, or curators in the respective projects. However, they still have full
  access to the project settings of all projects and can simply give themselves the missing
  permissions. **After an upgrade to 3.0.0, all administrators who require project permissions on 
  existing projects should assign these permissions to themselves. This also applies when importing 
  old projects.** For new projects, the creator of the project always starts with annotator, curator,
  and manager permissions. If these permissions are not required by the project creator,
  they should be removed after project creation.