{{- if and (.Values.auth.defaultAdmin.enabled) (not .Values.auth.defaultAdmin.password.existingSecret.secretName) }}
{{- $passwordValue := required ("You must define a default admin password if you enabled this feature without indicating an external secret reference!") (.Values.auth.defaultAdmin.password.value) }}
kind: Secret
metadata:
  name: {{ include "inception.secret.admin.name" . }}
type: Opaque
apiVersion: v1
data:
  password: {{ $passwordValue | b64enc | quote }}
  passwordHash: {{ htpasswd "" $passwordValue | trimPrefix ":" | print "{bcrypt}" | b64enc | quote }}
{{- end }}