{{- if  not .Values.config.database.auth.existingSecret }}
kind: Secret
metadata:
  name: {{ include "inception.secret.databaseAuth.name" . }}
type: Opaque
apiVersion: v1
data:
  password: {{ required "You must specify a database password in the 'config.database.auth.password.password.value' key of your values file if you're not refereing to an existing Secret!" .Values.config.database.auth.password.value | b64enc | quote }}
{{- end }}