{{- if  and (.Values.auth.saml2.enabled) (not .Values.auth.saml2.assertingPartyCertificate.existingSecret.secretName) }}
kind: Secret
metadata:
  name: {{ include "inception.secret.saml2.idp-cert.name" . }}
type: Opaque
apiVersion: v1
data:
  saml-idp.crt: {{ required "You must specify a SAML2 IdP certificate in the 'auth.saml2.assertingPartyCertificate.value' key of your values file if you're not refering to an existing Secret!" .Values.auth.saml2.assertingPartyCertificate.value | b64enc | quote }}
{{- end }}