// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_layers_feature_link]]
= Link features

Link features allow an annotation to connect to one or more span annotations.
Optionally, each of the links may have a role label. 
Link features are for example used to model event structures where the owner of the feature is the event trigger and the spans linked to represent the particpants or circumstances related to the event.

A link feature may be configured to link only to a particular span layer or to any span layer.
When linking to a particular span layer, an armed slot may be filled simply by selecting the span of text to fill it.
An appropriate span annotation will be created automatically.
If the link feature is configured to any layer, an existing span annotation needs to be selected as a slot filler.

.Link feature properties
[cols="1v,2", options="header"]
|====
| Property | Description

| Role labels
| Allows users to add a role label to each slot when linking anntations. 
  If disabled the UI labels of annotations will be displayed instead of role labels. 
  This property is enabled by default.

| Multiplicity
| Determines how links are compared to each other e.g. when calulating agreement or when merging annotations during curation.
  Use *Target can be linked in multiple different roles* if a link target can appear in multiple roles with respect to the same source span.
  In this mode, if an annotator links multiple targets using the same role, the links will be considered stacked and not be not auto-merged by curation or used for agreement calculation.
  Use *Target should be linked in only one role* if you expect that a link target should only appear in a single roles with respect to the same source span.
  In this mode, if an annotator links the same target in multiple roles, the links will be considered stacked and not be auto-merged by curation or used for agreement calculation.
  Use *Target can be linked in multiple roles (same or different)* if you expect that a link target should be linked multiple times with different roles as well as different targets can be linked with the same role.
  In this mode, there is no stacking.

| Tagset
| The tagset controlling the possible values for the link roles.

| Default slots
| For each of the specificed roles, an empty slot will be visible in the UI. 
  This can save the annotator time to create a slot for frequently used slots.
|====
