// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_remote_api_webhooks]]
= Webhooks

Webhooks allow {product-name} to notify external services about certain events. For example, an 
external service can be triggered when an annotator marks a document as finished or when all 
documents in a project have been completely curated.

Webhooks are declared in the `settings.properties` file. For every webhook, it is necessary to 
specify an URL (`url`) and a set of topics (`topics`) about with the remote service listening at the
given URL is notified. If the remote service is accessible via https and the certificate is not
known to the JVM running {product-name}, the certificate verification can be disabled
(`verify-certificates`). 

The following topics are supported:

* `DOCUMENT_STATE` - events related to the change of a document state such as when any user starts
  annotating or curating the document.
* `ANNOTATION_STATE` - events related to the change of an annotation state such as when a user
  starts or completes the annotation of a document.
* `PROJECT_STATE` - events related to the change of an entire project such as when all documents
  have been curated.

.Example webhook configuration
----
webhooks.globalHooks[0].url=http://localhost:3333/
webhooks.globalHooks[0].topics[0]=DOCUMENT_STATE
webhooks.globalHooks[0].topics[1]=ANNOTATION_STATE
webhooks.globalHooks[0].topics[2]=PROJECT_STATE
webhooks.globalHooks[0].verify-certificates=false
----

TIP: You can test receiving WebHooks e.g. using link:https://pypi.org/project/pyserv/[pyserv] or link:https://en.wikipedia.org/wiki/Netcat[netcat].

== Authentication headers

If the recipient of the webhook requires an authentication header, you can configure the header and
its value.

```
webhooks.globalHooks[0].auth-header=Bearer
webhooks.globalHooks[0].auth-header-value=MY-SECRET-TOKEN
```

== Retries

In some cases, the recipient of a webhook notification may be temporarily unavailable. It is possible to retry the delivery of a notification several times before giving up. By default,
only one delivery attempt is made (`webhooks.retry-count=0`). However, you can configure up to three additional attempts with a delay of up to 5000ms between them.

```
webhooks.retry-count=3
webhooks.retry-delay=5000
```

NOTE: Events being triggered while {product-name} is being shut down may not trigger any webhook deliveries.

== Bulk changes

When performing bulk changes of annotation states (i.e. via the workload management page), no 
individual `ANNOTATION_STATE` events are  generated. The document and project states are re-calculated
after the bulk change and depending on whether the bulk action had any effect on them,
`DOCUMENT_STATE` and/or `PROJECT_STATE` events are generated.

== Message examples

When a webhook is triggered, it sends a HTTP `POST` request to the configured URL. The `X-AERO-Notification` header indicates the topic and the body of the request is a JSON structure providing
details about the state change. The JSON in the examples below have been pretty-printed for your
convenient - the actual messages are not pretty-printed.

.Example `PROJECT_STATE`
----
{
  "timestamp": 1234567890,
  "projectId": 123,
  "projectName": "Example project",
  "projectPreviousState": "CURATION-IN-PROGRESS",
  "projectState": "ANNOTATION-IN-PROGRESS"
}
----

.Example `DOCUMENT_STATE`
----
{
  "timestamp": 1234567890,
  "projectId": 123,
  "projectName": "Example project",
  "documentId": 565,
  "documentName": "document.txt",
  "documentPreviousState": "CURATION-IN-PROGRESS",
  "documentState": "ANNOTATION-IN-PROGRESS"
}
----

.Example `ANNOTATION_STATE`
----
{
  "timestamp": 1234567890,
  "projectId": 123,
  "projectName": "Example project",
  "documentId": 565,
  "documentName": "document.txt",
  "user": "annotator1",
  "annotationUser": "annotator1",
  "annotationPreviousState": "COMPLETE",
  "annotationState": "COMPLETE",
  "annotatorAnnotationState": "IN_PROGRESS",
  "annotatorComment":"Test comment"
}
----

In the `ANNOTATION_STATE` message, we have two fields containing a user name: `user` and `annotationUser`.
Usually, these two fields will be the same. They differ if a user changes the state of a document
of another user. An example is when a curator marks the curation of a document as finished. In this
case, the curator's username is in the field `user` while the `annotationUser` field has the value
`CURATION_USER`.

The effective annotation state can be found in the `annotationState` field. However, it can be the
case that a manager has overridden the state, e.g. because an annotator forgot to mark a document
as finished. The `annotatorAnnotationState` field contains the state that was  (implicitly) set by the
annotator.

The `annotatorComment` field contains the comment that annotators can set when closing a document
and is typically used to report a problem with the document. Thus, it can typically be found only
when the `annotatorState` is `COMPLETE` (document closed as successful) or `LOCKED` (document closed
as not successful).