// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

== String Matcher

The string matching recommender is able to provide a very high accuracy for tasks such as named 
entity identification where a word or phrase always receives the same label. If an annotation is 
made, then the string matching recommender projects the label to all other identical spans, 
therefore making it easier to annotate repeated phenomena. So if we annotate _Kermit_ once as a 
_PER_, then it will suggest that any other mentions of _Kermit_ should also be annotated as _PER_.
When the same word or phrase is observed with different labels, then the matcher will assign the
relative frequency of the observations as the score for each label. Thus, if _Kermit_ is annotated
twice as _PER_ and once as _OTH_, than the score for _PER_ is 0.66 and the score for _OTH_ is 0.33.

The recommender can be used for span layers that anchor to single or multiple tokens and where
cross-sentence annotations are not allowed. It can be used for string features or features which get
internally represented as strings (e.g. concept features).

=== Gazeteers

It is possible to pre-load gazeteers into string matching recommenders. A gazeteer is a simple text
file where each line consists of a text and a label separated by a tab character. The order of 
items in the gazeteer does not matter. Suggestions are generated considering the longest match. Comment lines start with a `#`. Empty lines are ignored.

.Gazeteer example
----
# This is a comment
Obama	PER
Barack Obama	PER
Illinois	LOC
Illinois State Senate	ORG	
Hawaii	LOC	
Indonesia	LOC
----

=== Character-level layers

For layers which are configured to have a character-level annotation granularity, the string 
matching recommender will still try to match only at the beginning of tokens. However, it will not
require that the end of a match also ends at a token boundary. This helps e.g. in situations where
punctuation is not correctly detected as being a separate token.

NOTE: For layers with character-level granularity or layers which allow cross-sentence annotations,
      the evaluation scores of the recommender may not be exact.
