// Copyright 2018
// Ubiquitous Knowledge Processing (UKP) Lab
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_projects_list]]
== Project overview

After logging in to {product-name}, the first thing you see is the project overview. Here, you can
see all the projects to which you have access. For every project, the roles you have are shown.

Using the filter toggle buttons, you can select which projects are listed depending on the
role that you have in them. By default, all projects are visible.

Users with the role *project creator* can conveniently *create new projects* or
*import project archives* on this page.

Users without a *manager* role can leave a project by clicking on the *Leave Project* button 
below the project name.

When uploading projects via this page, user roles for the project are not fully imported! 
If the importing user has the role *project creator*, then the *manager* role is added
for the importing user. Otherwise, only the roles of the importing user are retained.

If the current instance has users with the same name as those who originally worked on the
import project, the manager can add these users to the project and they can access their annotations.
Otherwise, only the imported source documents are accessible. 

Users with the role *administrator* who wish to import projects with all permissions and optionally 
create missing users have to do this through the <<sect_projects>> which can be access through
the *Administration* link in the menu bar.
