// Copyright 2018
// Ubiquitous Knowledge Processing (UKP) Lab
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_menu]]
== Menu bar

At the top of the screen, there is always a menu bar visible which allows a quick navigation within
the application. It offers the following items:

  * **Home** - always takes you back to the main menu.
  * **Help** - opens the integrated help system in a new browser window.
  * **Administration** - takes you to the administrator dashboard which allows configuring projects
    or managing users. This item is only available to administrators.
  * **Username** - shows the name of the user currently logged in. If the administrator has allowed
    it, this is a link which allows accessing the current user's profile, e.g. to change the 
    password.
  * **Log out** - logs out of the application. 
  * **Timer** - shows the remaining time until the current session times out. When this happens, 
    the browser is automatically redirected to the login page.
    
