////
// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
////

== Creating annotations

The *Layer* box in the right sidebar shows the presently active layer span layer. To create a span
annotation, select a span of text or double click on a word.

If a relation layer is defined on top of a span layer, clicking on a corresponding span annotation
and dragging the mouse creates a relation annotation.

One an annotation has been created or if an annotation is selected, the *Annotation* box shows
the features of the annotation.

The result of changing the active layer in the *Layer* box while an annotation is selected depends
on the *Remember layer* setting. If this setting is disabled, changing the active layer causes the
currently selected annotation to be deleted and replaced with an annotation of the selected layer.
In this mode, it is necessary to unselect the current annotation by pressing the *Clear* button
before an annotation on another layer can be created. If *Remember layer* is enabled, changing
the active layer has no effect on the currently selected annotation.

The definition of layers is covered in Section <<sect_projects_layers>>.
