// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= MySQL

For production use of WebAnno, it is highly recommended to use a MySQL database. In this section,
we briefly describe how to install a MySQL server and how to prepare it for use with WebAnno.

== Prepare database

* Install MySQL
+
[source,bash]
----
$ apt-get install mysql-server
----
* make sure your MySQL server is configured for UTF-8. Check the following line is present in `/etc/mysql/mariadb.conf.d/50-server.cnf` (this is specific to Debian 9; on other systems the relevant file
may be `/etc/mysql/my.cnf`):
+
[source,bash]
----
character-set-server = utf8
collation-server     = utf8_bin
----
* also ensure the default settings for client connections to are UTF-8 in `/etc/mysql/mariadb.conf.d/50-server.cnf` (again Debian 9; likely in `/etc/mysql/my.cnf` on other systems)
+
[source,bash]
----
default-character-set = utf8
----
* login to MySQL
+
[source,bash]
----
$ mysql -u root -p
----
* create a database
+
[source,mysql]
----
mysql> CREATE DATABASE webanno DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
----
* create a database user called `webanno` with the password `t0t4llYSecreT` which is later used by the application to access the database (instructions for `settings.properties` file below).
+
[source,mysql]
----
mysql> CREATE USER 'webanno'@'localhost' IDENTIFIED BY 't0t4llYSecreT';
mysql> GRANT ALL PRIVILEGES ON webanno.* TO 'webanno'@'localhost';
mysql> FLUSH PRIVILEGES;
----

IMPORTANT: For production use, make sure you choose a different, secret, and secure password.


== Configuration options

This section explains some settings that can be added to the `database.url` in the 
`settings.properties` file when using MySQL. Settings are separated from the host name and database
name with a `?` character and multiple settings are separated using the `&` character, e.g.:

----
database.url=jdbc:mysql://localhost:3306/webanno?useSSL=false&serverTimezone=UTC
----

To suppress the warning about non-SSL database connections with recent MySQL databases, append the
following setting to the `database.url`:

----
useSSL=false
----

Recent MySQL drivers may refuse to work unless a database server timezone has been specified. The
easiest way to do this is to add the following setting to the `database.url`: 

----
serverTimezone=UTC
----

If you plan to use UTF-8 encoding for project name and tagset/tag name, make sure either of the following settings for MySQL database

* in the `settings.properties` file, make sure that `database.url` includes 
+
----
useUnicode=true&characterEncoding=UTF-8
----

* change the `my.conf` MySQL databse configuration file to include the following line
+
----
character-set-server = utf8
----
