// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_settings]]
== Settings

[cols="4*", options="header"]
|===
| Setting
| Description
| Default
| Example

| auth.mode
| Authentication mode
| database
| preauth

| auth.preauth.header.principal
| Principal header
| remote_user
| _some other header_

| auth.preauth.newuser.roles
| Default roles for new users (comma separated)
| _<none>_
| ROLE_PROJECT_CREATOR

| auth.user._<username>_.roles
| Extra roles for user (comma separated)
| _<none>_
| ROLE_ADMIN

| database.dialect
| Database dialect
| org.hibernate.dialect.HSQLDialect
| org.hibernate.dialect.MySQL5InnoDBDialect

| database.driver
| Database driver
| org.hsqldb.jdbc.JDBCDriver
| com.mysql.jdbc.Driver

| database.url
| JDBC connection string
| _location in WebAnno home_
| jdbc:mysql://localhost:3306/weblab?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

| database.username
| Database username
| sa
| user

| database.password
| Database password
| _unset_
| pass

| database.initial-pool-size
| Initial database connection pool size
| 4
|

| database.min-pool-size
| Minimum database connection pool size
| 4
| 

| database.max-pool-size
| Maximum database connection pool size
| 10
| 

| backup.interval
| Time between backups (seconds)
| 0
| 300 _(60 * 5 = 5 minutes)_

| backup.keep.number
| Maximum number of backups to keep
| 0
| 5

| backup.keep.time
| Maximum age of backups to keep (seconds)
| 0
| 2592000 _(60 * 60 * 24 * 30 = 30 days)_

| ui.brat.autoScroll
| Whether to scroll the annotation being edited into the center of the page
| true
| 

| ui.brat.pageSize
| The number of sentences to display per page
| 5
| 

| ui.brat.singleClickSelection
| Whether to select annotations with a single click
| false
| 

| style.logo
| Logo image displayed in the upper-right corner
| _unset_
| _path to an image file_

| style.header.icon...
| Icons/links to display in the page header. For details, see below.
| _unset_
| 

| warnings.embeddedDatabase
| Warn about using an embedded database
| true
| false

| warnings.unsupportedBrowser
| Warn about unsupported browser
| true
| false

| debug.showExceptionPage
| Show a page with a stack trace instead of an "Internal error" page. Do not use in production!
| false
| true

| login.message
| Custom message to appear on the login page, such as project web-site, annotation guideline link, ... The message can be an HTML content.
| _unset_
| `<span style="color:red; font-size: 200%;">Use are your own risk.</span>`

| user.profile.accessible
| Whether regular users can access their own profile to change their password and other profile information. This setting has no effect if WebAnno is running in pre-authentication mode.
| false
| true
|===

=== Configure database via environment variables

The database connection details can also be configured via environment variables. When these
environment variables are present, they are preferred over the `settings.properties` file. 
The following environment variables can be used:

[cols="4*", options="header"]
|===
| Setting
| Description
| Default
| Example

| `WEBANNO_DB_DIALECT`
| Database dialect
| org.hibernate.dialect.HSQLDialect
| org.hibernate.dialect.MySQL5InnoDBDialect

| `WEBANNO_DB_DRIVER`
| Database driver
| org.hsqldb.jdbc.JDBCDriver
| com.mysql.jdbc.Driver

| `WEBANNO_DB_URL`
| JDBC connection string
| _location in WebAnno home_
| jdbc:mysql://localhost:3306/weblab?useUnicode=true&characterEncoding=UTF-8

| `WEBANNO_DB_USERNAME`
| Database username
| sa
| user

| `WEBANNO_DB_PASSWORD`
| Database password
| _unset_
| pass
|===


=== Custom header icons

WebAnno allows adding custom icons to the page header. You can declare such custom icons in the WebAnno settings file as shown in the example below. Each declaration begins with the prefix `style.header.icon.` followed by an identifier (here `myOrganization` and `mySupport`). The suffixes `.linkUrl` and `.imageUrl` indicate the URL of the target page and of the icon image respectively. Images are automatically resized via CSS. However, to keep loading times low, you should point to a reasonably small image.

The order of the icons is controlled by the ID, not by the order in the configuration file!

.Example: Custom header icon
----
style.header.icon.myOrganization.linkUrl=http://my.org
style.header.icon.myOrganization.imageUrl=http://my.org/logo.png
style.header.icon.mySupport.linkUrl=http://my.org/support
style.header.icon.mySupport.imageUrl=http://my.org/help.png
----

=== Internal backups

WebAnno stores its annotations internally in files. Whenever a user performs an action on a
document, the file is updated. It is possible to configure WebAnno to keep internal backups of
these files, e.g. to safeguard against crashes or bugs. 

The internal backups are controlled through three properties:

[cols="3*", options="header"]
|===
| Setting
| Description
| Default

| backup.interval
| Time between backups (seconds)
| `0` _(disabled)_

| backup.keep.number
| Maximum number of backups to keep
| `0` _(unlimited)_

| backup.keep.time
| Maximum age of backups to keep (seconds)
| `0` _(unlimited)_
|===

By default, backups are disabled (**backup.interval** is set to `0`). Changing this properties to
any positive number enables internal backups. The interval controls the minimum time between changes
to a document that needs to have elapsed in order for a new backup to be created.

When backups are enabled, either or both of the properties **backup.keep.number** and 
**backup.keep.time** should be changed as well, because their default values will cause the
backups to be stored indefinitely and they will eventually fill up the disk.

The properties **backup.keep.number** and **backup.keep.time** control how long backups are keep
and the maximal number of backups to keep. These settings are effective simultaneously.

.Example: Make backups every 5 minutes and keep 10 backups irrespective of age
----
backup.interval    = 300
backup.keep.number = 10
backup.keep.time   = 0
----

.Example: Make backups every 5 minutes and all not older than 7 days (60 * 60 * 24 * 7 seconds)
----
backup.interval    = 300
backup.keep.number = 0
backup.keep.time   = 604800
----

.Example: Make backups every 5 minutes and keep at most 10 backups that are not older than 7 days
----
backup.interval    = 300
backup.keep.number = 10
backup.keep.time   = 604800
----

=== External pre-authentication

WebAnno can be used in conjunction with header-based external per-authentication. In this mode,
WebAnno looks for a special HTTP header (by default `remote_user`) and if that header exists, 
it is taken for granted that this user has been authenticated. WebAnno will check its internal
database if a user by the given name exists, otherwise it will create the user.

Pre-authentication can be enabled by setting the property `auth.mode` to `preauth`. When enabling
pre-authentication mode, the default roles for new users can be controlled using the 
`auth.preauth.newuser.roles` property. The `ROLE_USER` is always added, even if not specified
explicitly. Adding also the role `ROLE_PROEJCT_CREATOR` allows all auto-created users also to
create their own projects. 

Since the default administrator user is not created in pre-authentication, it is useful to also
declare at least one user as an administrator. This is done through the property 
`auth.user.<username>.roles` where `<username>` must be replaced with the name of the user.
The example below shows how the user *Franz* is given administrator permissions. 

.Example: Authenticate using the `remote_user` header, new users can create projects, user *Franz* is always admin.
----
auth.mode                     = preauth
auth.preauth.header.principal = remote_user
auth.preauth.newuser.roles    = ROLE_PROJECT_CREATOR
auth.user.Franz.roles         = ROLE_ADMIN
----

NOTE: The roles specified through `auth.preauth.newuser.roles` are saved in the database when a
      user logs in for the first time and can be changed after creation through the user interface.
      
NOTE: The roles added through `auth.user.<username>.roles` properties are *not* saved in the
      database and *cannot* be edited through the user interface.

