// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_recommendation]]
= Recommenders system

For information on the different recommenders, please refer to <<user-guide.adoc#sect_projects_recommendation,user guide>>.

// [plantuml]
// ....
// package "inception-recommendation" {
//   [LearningRecordService]
// }
// 
// package "webanno-api-dao" {
//   [DocumentService]
// }
// 
// DocumentService -- LearningRecordService : AfterDocuemntResetEvent
// ....

== Recommenders

Recommenders provide the ability to generate annotation suggestions. Optionally, they can be trained based on existing annotations. Also optionally, they can be evaluated.

* The `RecommendationEngineFactory` interface provides the API for implementing recommender types.
* The `RecommendationEngine` interface provides the API for the actual recommenders produced by the factory.
* The `RecommenderFactoryRegistry` interface and its default implementation `RecommenderFactoryRegistryImpl` serve as an access point to the different recommender types.

== Suggestion supports

Suggestion supports provide everything necessary to handle annotation suggestions. This includes: 

* extracting suggestions from the predicted annotations that the recommenders
* rendering these suggestions
* handling actions like accepting/correting, rejecting, or skipping suggestions

The subsystem is made up of the following main APIs:

* The `SuggestionSupport` interface provides the API for handling different kinds of suggestions.
* The `SuggestionSupportRegistry` interface and its default implementation `SuggestionSupportRegistryImpl` serve as an access point to the different recommender types.
* The `SuggestionRenderer` interface provides the API for rendering suggestions into a `VDoc`.

