apiVersion: v2
name: inception
description: A semantic annotation platform offering intelligent assistance and knowledge management.
home: https://inception-project.github.io
sources: 
  - https://github.com/inception-project/inception

kubeVersion: ">=v1.24.0-0"

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0-alpha

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "33.3"

# Using Bitnami MariaDB chart as Inception's DB backend
dependencies:
- name: mariadb
  alias: mariadb
  condition: mariadb.enabled
  version: "19.0.1"
  repository: "oci://registry-1.docker.io/bitnamicharts"
