////
// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
////

= Primitive Features

Supported primitive features types are string, boolean, integer, and float.
Boolean features are displayed as a checkbox that can either be marked or unmarked. Integer and 
float features are displayed using a number field. However if an integer feature is limited and the
difference between the maximum and minimum is lower than 12 it can also be displayed with a radio
button group instead. String features are displayed using a text field
or a text area with multiple rows. If multiple rows are enabled it can either be dynamically sized
or a size for collapsing and expanding can be configured. The multiple rows, non-dynamic text area
can be expanded if focused and collapses again if focus is lost. In case the string feature has a
tagset it will instead use a combobox.  
