apiVersion: apps/v1
kind: Deployment
metadata:
  name: inception
spec:
  selector:
    matchLabels:
      app: inception
  replicas: 1
  template:
    metadata:
      labels:
        app: inception
    spec:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        runAsNonRoot: true
      containers:
      - name: inception
        image: "ghcr.io/inception-project/inception-snapshots:32.3"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          readOnlyRootFilesystem: true
          privileged: false
        volumeMounts:
        - mountPath: /export
          name: inception-data-pv
        - mountPath: /tmp
          name: inception-tmp-pv
        - mountPath: /var/log
          name: inception-log-pv
      volumes:
      - name: inception-data-pv
        persistentVolumeClaim:
          claimName: inception-data-pvc
      - name: inception-tmp-pv
        persistentVolumeClaim:
          claimName: inception-tmp-pvc
      - name: inception-log-pv
        persistentVolumeClaim:
          claimName: inception-log-pvc