// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_webannotsv]]
= WebAnno TSV 3.3 File format

In this section, we will discuss the WebAnno TSV (Tab Separated Value) file format version 3.3. 
The format is similar to the CoNNL file formats with specialized additions to the header and column
representations. The file format inhabits a header and a body section. The *header* section
present information about the different types of annotation layers and features used in the file.
While importing the WebAnno TSV file, the specified headers should be first created in to the
running WebAnno project. Otherwise, the importing of the file will not be possible.

The *body* section of the TSV file presents the document and all the associated annotations
including sentence and token annotations.

== Encoding and Offsets

TSV files are always encoded in UTF-8. However, the offsets used in the TSV file are based on
UTF-16. This is important when using TSV files with texts containing e.g. Emojis or some modern
non-latin Asian, Middle-eastern and African scripts.

WebAnno is implemented in Java. The Java platform internally uses a UTF-16 representation for
text. For this reason, the offsets used in the TSV format currently represent offsets of the 16bit
units in UTF-16 strings. This is important if your text contains Unicode characters that cannot
be represented in 16bit and which thus require two 16bit units. For example a token represented
by the Unicode character 😊 (U+1F60A) requires two 16bit units. Hence, the offset count increased
by 2 for this character. So Unicode characters starting at U+10000 increase the offset count by 2.

.Example: TSV sentence containing a Unicode character from the Supplementary Planes
[source,text,tabsize=0]
----
#Text=I like it 😊 .
1-1	0-1	I	_
1-2	2-6	like	_
1-3	7-9	it	_
1-4	10-12	😊	*
1-5	13-14	.	_
----

NOTE: Since the character offsets are based on UTF-16 and the TSV file itself is encoded in UTF-8,
      first the text contained in the file needs to be transcoded from UTF-8 into UTF-16 before the offsets
      can be applied. The offsets cannot be used for random access to characters directly in the TSV file.

== File Header

WebAnno TSV 3.3 file header consists of two main parts: 

* the format indicator
* the column declarations

After the header, there must be **two** empty lines before the body part containing the annotations
may start. 

.Example: format in file header
[source,text,tabsize=0]
----
#FORMAT=WebAnno TSV 3.3
----

Layers are marked by the `#` character followed by `T_SP=` for *span types* (including *slot features*), `T_CH=` for *chain layers*, and `T_RL=` for *relation layers*. Every layer is written in new line, followed by the features in the layer.
If all layer type exists, first, all the span layers will be written, then the chain layer, and finally the relation layers.
Features are separated by the `|` character and only the short name of the feature is provided.

.Example: Span layer with simple features in file header
[source,text,tabsize=0]
----
#T_SP=webanno.custom.Pred|bestSense|lemmaMapped|senseId|senseMapped
----
 
Here the layer name is *webanno.custom.Pred* and the features are named *bestSense*, *lemmaMapped*, *senseId*, *senseMapped*.
Slot features start with a prefix `ROLE_` followed by the name of the role and the link. The role feature name and the link feature name are separated by the `_` character.

The target of the slot feature always follows the role/link name

.Example: Span layer with slot features in file header
[source,text,tabsize=0]
----
#T_SP=webanno.custom.SemPred|ROLE_webanno.custom.SemPred:RoleSet_webanno.custom.SemPredRoleSetLink|uima.tcas.Annotation|aFrame
----

Here the name of the role is *webanno.custom.SemPred:RoleSet* and the name of the role link is *webanno.custom.SemPredRoleSetLink* and the target type is *uima.tcas.Annotation*.

Chain layers will have always two features, *referenceType* and *referenceRelation*.

.Example: Chain layers in file header
[source,text,tabsize=0]
----
#T_CH=de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink|referenceType|referenceRelation
----

Relation layers will come at last in the list and the very last entry in the features will be the type of the base (governor or dependent) annotations with a prefix `BT_`.

.Example: Relation layers in file header
[source,text,tabsize=0]
----
#T_RL=de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency|DependencyType|BT_de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS
----

Here, the relation type `de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency` has a feature `DependencyType` and the relation is between a base type of `de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS`.

== File Body / Annotations

In this section we discuss the different representations of texts and annotation in WebAnno TSV3format

=== Reserved Characters

Reserved characters have a special meaning in the TSV format and must be are escaped with the *backslash* (`\`) character if they appear in text or feature values. Reserved characters are the following:

.Reserved Characters
[source,text]
----
\,[,],|,_,->,;,\t,\n,*
----

NOTE: The way that TSV is presently defined/implemented, it kind of considers `->` as a single 
      "character"... and it is also escaped as a single unit, i.e. `->` becomes `\->`. It is something to
      be addressed in a future iteration of the format.

=== Sentence Representation

Sentence annotations are presented following the text marker `#Text=`, before the token
annotations. All text given here is inside the sentence boundaries.

.Example: Original text sections
[source,text,tabsize=0]
----
#Text=Bell , based in Los Angeles , makes and distributes electronic , computer and building products .
----

The text of an imported document is reconstructed from the sentence annotations. Additionally,
the offset information of the sentence tokens are taken into account to determine whether padding
needs to be added between sentences. The TSV format can presently not record text that occurs in
between two sentences.

If a sentence spans multiple lines, the text is split at the line feed characters (ASCII 12) and
multiple `#Text=` lines are generated. Note that carriage return characters (ASCII 13) are kept
as escaped characters (`\r`). 

.Example: Original multi-line text
[source,text,tabsize=0]
----
#Text=Bell , based in Los Angeles , makes and distributes
#Text=electronic , computer and building products .
----

Optionally, an alphanumeric sentence identifier can be added in the sentence header section.

.Example: Sentence identifier 
[source,text]
----
#Sentence.id=s1
#Text=Bell , based in Los Angeles , makes and distributes electronic , computer and building products .
----


=== Token and Sub-token Annotations

Tokens represent a span of text within a sentence. Tokens cannot overlap, although then can be
directly adjacent (i.e. without any whitespace between them). The start offset of the first
character of the first token corresponds to the start of offset of the sentence.

Token annotation starts with a `sentence-token` number marker followed by the begin-end offsets
and the token itself, separated by a TAB characters. 

.Example: Token position
[source,text,tabsize=0]
----
1-2	4-8	Haag
----

Here `1` indicates the sentence number, `2` indicates the token number (here, the second token
in the first sentence) and `4` is the begin offset of the token and `8` is the end offset of the
token while `Haag` is the token.

The begin offset of the first token in a sentence must coincide with the offset at which the first
`#Text` line starts in the original document text.

.Example: Valid sentence text header / token offsets
----
#Text=Hello
1-1	0-6	Hello
----

.Example: Invalid sentence text header / token offsets
----
#Text= Hello
1-1	1-7	Hello
----

Sub-token representations are affixed with a `.` and a number starts from 1 to N. 

.Example: Sub-token positions
[source,text,tabsize=0]
----
1-3	9-14	plays
1-3.1	9-13	play
1-3.2	13-14	s
----

Here, the sub-token `play` is indicated by sentence-token number `1-3.1` and the sub-token `s` is
indicated by `1-3.2`.

While tokens may not overlap, sub-tokens may overlap.

.Example: Overlapping sub-tokens
[source,text,tabsize=0]
----
1-3	9-14	plays
1-3.1	9-12	pla
1-3.2	11-14	ays
----

=== Span Annotations

For every features of a span Annotation, annotation value will be presented in the same row as the token/sub-token annotation, separated by a TAB character. If there is no annotation for the given span layer, a `_` character is placed in the column. If the feature has no/null annotation or if the span layer do not have a feature at all, a `*` character represents the annotation.

.Example: Span layer declaration in file header
[source,text,tabsize=0]
----
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS|PosValue
#T_SP=webanno.custom.Sentiment|Category|Opinion
----

.Example: Span annotations in file body
[source,text,tabsize=0]
----
1-9	36-43	unhappy	JJ	abstract	negative
----

Here, the first annotation at column 4, `JJ` is avalue for a feature *PosValue* of the layer *de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS*. For the two features of the layer *webanno.custom.Sentiment* (*Category* and *Opinion*), the values `abstract` and `negative` are
presented at column 5 and 6 resp.

NOTE: When serializing a span annotation starts or ends in a space between tokens, then the
      annotation is truncated to start at the next token after the space or to end at the last token 
      before the space. For example, if you consider the text `[one two]` and there is an some span annotation
      on `[one ]` (note the trailing space), the extent of this span annotation will be serialized as only
      covering `[one]`. It is not possible in this format to have annotations starting or ending in 
      the space between tokens because the inter-token space is not rendered as a row and therefore is not
      addressable in the format. 

=== Disambiguation IDs

Within a single line, an annotation can be uniquely identified by its type and stacking index.
However, across lines, annotation cannot be uniquely identified easily. Also, if the exact type
of the referenced annotation is not known, an annotation cannot be uniquely identified. For this
reason, disambiguation IDs are introduced in potentially problematic cases:

* stacked annotations - if multiple annotations of the same type appear in the same line
* multi-unit annotations - if an annotations spans multiple tokens or sub-tokens
* un-typed slots - if a slot feature has the type `uima.tcas.Annotation` and may thus refer to
  any kind of target annotation.

The disambiguation ID is attached as a suffix `[N]` to the annotation value. Stacked annotations are separated by `|` character.

.Example: Span layer declaration in file header
[source,text,tabsize=0]
----
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS|PosValue
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity|value
----

.Example: Multi-token span annotations and stacked span annotations
[source,text,tabsize=0]
----
1-1	0-3	Ms.	NNP	PER[1]|PERpart[2]
1-2	4-8	Haag	NNP	PER[1]
----

Here, `PER[1]` indicates that token `1-1` and `1-2` have the same annotation (multi-token annotations) while `PERpart[2]` is the second (stacked) annotation on token `1-1` separated by `|` character.

NOTE: On chain layers, the number in brackets is *not* a disambiguation ID but rather a chain ID!

=== Slot features

Slot features and the target annotations are separated by TAB character (first the feature column then the target column follows). In the target column, the `sentence-token` id is recorded where the feature is drawn.

Unlike other span layer features (which are separated by `|` character), multiple annotations for a slot feature are separated by the `;` character.

.Example: Span layer declaration in file header
[source,text,tabsize=0]
----
#T_SP=webanno.custom.Frame|FE|ROLE_webanno.custom.Frame:Roles_webanno.custom.FrameRolesLink|webanno.custom.Lu
#T_SP=webanno.custom.Lu|luvalue
----

.Example: Span annotations and slot features
[source,text,tabsize=0]
----
2-1	27-30	Bob	_	_	_	bob
2-2	31-40	auctioned	transaction	seller;goods;buyer	2-1;2-3[4];2-6
2-3	41-44	the	_	_	_	clock[4]
2-4	45-50	clock	_	_	_	clock[4]
2-5	52-54	to	_	_	_	_
2-6	55-59	John	_	_	_	john
2-7	59-60	.	_	_	_	_
----

Here, for example, at token `2-2`, we have three slot annotations for feature `Roles` that are `seller`, `goods`, and `buyer`. The targets are on token `2-1`, `2-3[4]`, and `2-6` respectively which are on annotations of the layer `webanno.custom.Lu` which are `bob`, `clock` and `john`. 

=== Chain Annotations

In the Chain annotation, two columns (TAB separated) are used to represent the `referenceType` and the `referenceRelation`. A chain ID is attached to the `referenceType` to distinguish to which of the chains the annotation belongs. The `referenceRelation` of the chain is represented by the relation value followed by `->` and followed by the `CH-LINK` number where `CH` is the chain number and `LINK` is the link number (the order the chain).

.Example: Chain layer declaration in file header
[source,text]
----
#T_CH=de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink|referenceType|referenceRelation
----

.Example: Chain annotations
[source,text,tabsize=0]
----
1-1	0-2	He	pr[1]	coref->1-1
1-2	3-7	shot	_	_
1-3	8-15	himself	pr[1]	coref->1-2
1-4	16-20	with	_	_
1-5	21-24	his	pr[1]	*->1-3
1-6	25-33	revolver	_	_
1-7	33-34	.	_	_
----

In this example, token `1-3` is marked as `pr[1]` which indicates that the *referenceType* is `pr` and it is part of the chain with the ID `1`. The relation label is `coref` and with the `CH-LINK` number `1-2` which means that it belongs to chain `1` and this is the second link in the chain.

=== Relation Annotations

Relation annotations comes to the last columns of the TSV file format. Just like the span annotations, every feature of the relation layers are represented in a separate TAB. Besides, one extra column (after all feature values) is used to write the token id from which token/sub-token this arc of a relation annotation is drawn.

.Example: Span and relation layer declaration in file header
[source,text,tabsize=0]
----
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS|PosValue
#T_RL=de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency|DependencyType|BT_de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS
----

.Example: Span and relation annotations
[source,text,tabsize=0]
----
1-1	0-3	Ms.	NNP	SUBJ	1-3
1-2	4-8	Haag	NNP	SBJ	1-3
1-3	9-14	plays	VBD	P|ROOT	1-5|1-3
1-4	15-22	Elianti	NNP	OBJ	1-3
1-5	23-24	.	.	_	_
----

In this example (say token `1-1`), column 4 (`NNP`) is a value for the feature `PosValue` of the *de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS* layer. Column 5 (`SUBJ`) records the value for the feature *DependencyType* of the *de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency* relation layer, where as column 6 (`1-3`) shows from which governor (`VBD`) the dependency arc is drawn.

For relations, a single disambiguation ID is not sufficient. If a relation is ambiguous, then
the source ID of the relation is followed by the source and target disambiguation ID separated
by an underscore (`_`). If only one of the relation endpoints is ambiguous, then the other one
appears with the ID `0`. E.g. in the example below, the annotation on token `1-5` is ambiguous,
but the annotation on token `1-1` is not.

.Example: Disambiguation IDs in relations
[source,text,tabsize=0]
----
#FORMAT=WebAnno TSV 3.3
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity|value
#T_RL=webanno.custom.Relation|value|BT_de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity


#Text=This is a test .
1-1	0-4	This	*	_	_
1-2	5-7	is	_	_	_
1-3	8-9	a	_	_	_
1-4	10-14	test	_	_	_
1-5	15-16	.	*[1]|*[2]	*	1-1[0_1]
----
 
== Changes

* 3.3
  * Adds support for the optional `#Sentence.id` stanza in the sentence header
* 3.2
  * First time the format is fully documented
