// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_formats_bioc]]
= 🧪 BioC

====
CAUTION: Experimental feature. To use this functionality, you need to enable it first by adding `format.bioc.enabled=true` to the `settings.properties` file (see the <<admin-guide.adoc#sect_settings, Admin Guide>>).
====

This is a new and still experimental BioC format. 

NOTE: This format dynamically maps information from the imported files to the layers and features configured in 
      the project. For this process to work, the layers and features need to be set up **before** importing BioC files.

.Supported features
* Sentence information is supported
  * If sentences are present in a BioC document, they are imported. Otherwise, {product-name} will
    automatically try to determine sentence boundaries.
  * On export, the BioC files are always created with sentence information.
* Passages are imported as a `Div` annotations and the passage `type` infon is set as the `type`
  feature on these `Div` annotations
* When reading span or relation annotations, the `type` infon is used to look up a suitable 
  annotation layer. If a layer exists where either the full technical name of the layer or the
  simple technical name (the part after the last dot) match the type, then an attempt will be made
  to match the annotation to that layer. If the annotation has other infons that match features on
  that layer, they will also be matched. If no layer matches but the default `Span` layer is 
  present, annotations will be matched to that. Similarly, if only a single infon is present in an 
  annotation and no other feature matches, then the infon value may be matched to a potentially
  existing `value` feature.
* When exporting annotations, the `type` infon will always be set to the full layer name and
  features will be serialized to infons matching their names.
* If a document has not been imported from a BioC file containing passages and does not contain
  `Div` annotations from any other source either, then on export a single passage containing the
  entire document is created.
* Multi-value features are supported. They are serialized as a sequence of infons using the same key
  (but different values). They can also be deserialized from those infons. When there are multiple
  infons with the same key during deserialization but the target feature is not multi-valued, then
  only the first infon is considered and the others are ignored.

.Unsupported features  
* Cross-passage relations are not supported.
* Sentence-level infons are not supported.
* Passage-level infons are not supported.
* Document-level infons are not supported.
* The writer writes one BioC file per CAS (i.e. writing multiple documents to a single collection file is not supported).

[cols="2,1,1,3"]
|====
| Format | Import | Export | Supported layers

| link:https://raw.githubusercontent.com/2mh/PyBioC/master/BioC.dtd[BioC (experimental)] (`bioc`)
| yes
| yes
| see description
|====

