// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_upgrade]]
== Upgrade

This section describes how to upgrade the standalone version of {product-name} using an embedded database. For further information on how to upgrade {product-name}, in particular the WAR version when using a MySQL database or older versions of {product-name}, please refer to the <<admin-guide.adoc#,Administrator Guide>>.

IMPORTANT: Before any upgrade, make a copy of your {product-name} home folder. If {product-name} is 
            configured to use an external database, e.g. MySQL, make a backup of this database as well. See
            the <<admin-guide.adoc#,Administrator Guide>> for further information.

include::../common/migration.adoc[]

