// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_formats_tei_legacy]]
= 🪦 TEI P5 XML (old)

The link:https://tei-c.org/guidelines/p5/[TEI P5 XML] format is a widely used standard format. It is a very complex format and furthermore is often extended for specific corpora. 

{product-name} supports importing annotations from various common element types, but by far not all. For more details about the supported element types, see the link:https://dkpro.github.io/dkpro-core/releases/2.2.0/docs/format-reference.html#format-Tei[DKPro Core TEI support] documentation.

When importing TEI files using this format, the XML structure of the document is **not** retained. When exporting an annotated document in this format, the XML structure is generated from scratch.

[cols="2,1,1,3"]
|====
| Format | Import | Export | Supported layers

| link:https://www.tei-c.org/release/doc/tei-p5-doc/en/html/index.html[TEI P5] (`dkpro-core-tei`)
| yes
| yes
| Part-of-speech tagging (built-in), +
  Lemmatization (built-ion), +
  Named entity tagging (built-in)
|====
