// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_database]]
== Database Model

=== Projects

`project`

=== Documents

==== `source_document`

The original document uploaded by a user into a project. The document is preserved in its original
format.

==== `annotation_document`

Annotations made by a particular user on a document. The annotation document is persisted separately
from the original document. There is one annotation document per user per document. Within the tool,
a CAS data structure is used to represent the annotation document.


=== Layers

==== `annotation_type`

|====
| Column | Description

| id
| 

| project
| 

| name
| UIMA type name

| uiName
| Layer name displayed in the UI

| type
| span/relation/chain

| description
| 

| builtIn
| Built-in types are pre-defined via DKPro Core and cannot be deleted.

| enabled
| If the type can be used for annotation or not. Types cannot be deleted after creation because we
need to retain the type definitions in order to load CASes which still contains the type, so this
is a way to not allow editing/displaying of these types anymore.

| readonly
| If the annotations of this type can be created/edited.

| attachType
| *optional (span)*

| attachFeature
| *optional, forbidden if attachType is unset*

| allowSTacking
| Behavior

| crossSentence
| Behavior

| linkedListBehavior
| *chain* Behavior

| lockToTokenOffset
| *span* Behavior

| multipleTokens
| *span* Behavior
|====

NOTE: For historical reasons, the names in the database differ: `attachType` is called 
      `annotation_type`, `attachFeature` is called `annotation_feature`.

===== Span layer

A span layer allows to create annotations over spans of text.

If `attachType` is set, then an annotation can only be created over the same span on which an 
annotation of the specified type also exists. For span layers, setting `attachFeature` is mandatory
if a `attachType` is defined. The `attachFeature` indicates the feature on the annotation of the 
`attachType` layer which is to be set to the newly created annotation. 

For example, the `Lemma` layer has the `attachType` set to `Token` and the `attachFeature` set to 
`lemma`. This means, that a new lemma annotation can only be created where a token already exists
and that the `lemma` feature of the token will point to the newly created lemma annotation.

Deleting an annotation that has other annotations attached to it will also cause the attached 
annotations to be deleted.

NOTE: This case is currently not implemented because WebAnno currently does not allow to 
      create spans that attach to other spans. The only span type for which this is relevant
      is the `Token` type which cannot be deleted.

===== Relation layer

A relation layer allows to draw arcs between span annotations. The `attachType` is mandatory for 
relation types and specifies which type of annotations arcs can be drawn between. 

Arcs can only be drawn between annotations of the same layer. It is not possible to draw an arc 
between two spans of different layers. 

Only a single relation layer can attach to any given span layer.

If the `annotation_feature` is set, then the arc is not drawn between annotations of the layer 
indicated by `annotation_type`, but between annotations of the type specified by the feature. E.g. 
for a dependency relation layer, `annotation_type` would be set to `Token` and `annotation_feature`
to `pos`. The `Token` type has no visual representation in the UI. However, the `pos` feature points
to a `POS` annotation, which is rendered and between which the dependency relation arcs are then 
drawn. 

Deleting an annotation that is the endpoint of a relation will also delete the relation. In the case
that `annotation_feature`, this is also the case if the annotation pointed to is deleted. E.g. if
a POS annotation in the above example is deleted, then the attaching relation annotations are also
deleted.

===== Chain layer

==== `annotation_feature`

|====
| Column | Description

| id
|

| project
|

| name
| UIMA feature name

| uiName
| Feature name displayed in the UI

| description
|

| annotation_type
| (foreign key) The type to which this feature belongs.

| type
| The type of feature. Must be a type from the CAS or a UIMA built-in type such as "uima.cas.String".

| multi_value_mode
| Used to control if a feature can have multiple values and how these are represented. "none", "array".

| link_mode
| If the feature is a link to another feature structure, this column indicates what kind of relation
is used, e.g. "none", "simple", "withRole".

| link_type_name
| If a "multipleWithRole" type is used, then the an additional UIMA type must be created that
bears a role feature and points to the target type.

| link_type_role_feature_name
| The name of the feature bearing the role.

| link_type_target_feature_name
| The name of the feature pointing to the target.

| tag_set
| *optional* The id of the tagset which is used for this layer. If this is null, the label can be freely set
(text input field), otherwise only values from the tagset can be used as labels.

| builtIn
| Built-in features are pre-defined via DKPro Core and cannot deleted.

| enabled
| If the feature can be used for annotation or not. Features cannot be deleted after creation 
because we need to retain the type definitions in order to load CASes which still contains the type,
so this is a way to not allow editing/displaying of these types anymore.

| visible
| Feature rendered - if set to false only shown in annotation editor

| remember
| Remember feature value - whether the annotation detail editor should carry values of this feature
over when creating a new annotation of the same type. This can be useful when creating many annotations
of the same type in a row.

| hideUnconstraintFeature
| Hides un-constraint feature - whether the feature should be showed if constraints rules are enabled and 
based on the evaluation of constraint rules on a feature.  
|====

===== Examples

.Part-of-speech tag feature in the DKPro Core POS layer
|====
| Column | Value

| name
| PosValue

| uiName
| Part of speech

| description
| Part-of-speech tag

| annotation_type
| -> de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS (span)

| type
| uima.cas.String

| link_mode
| null

| link_type_name
| null

| link_type_role_feature_name
| null

| link_type_target_feature_name
| null

| tag_set
| -> STTS

| builtIn
| true
|====

.Arguments feature in a custom semantic predicate-argument structure
|====
| Column | Value

| name
| args

| uiName
| Arguments

| description
| Semantic arguments

| annotation_type
| -> webanno.custom.SemanticPredicate (span)

| type
| webanno.custom.SemanticArgument (span)

| link_mode
| multipleWithRole

| link_type_name
| webanno.custom.SemanticArgumentLink

| link_type_role_feature_name
| role

| link_type_target_feature_name
| target

| tag_set
| null

| builtIn
| false
|====

=== Tagsets

`tag_set`
`tag`


=== Constraints

`constraints`

|====
| Column | Description

| id
|

| project
|

| name
|

| description
|

| rules
|
|====


=== Permissions

`project_permissions`
`authorities`
`users`