// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_setup]]
== Setup

=== GIT

All WebAnno files are stored using UNIX line endings. If you develop on Windows, you have to
set the `core.autocrlf` configuration setting to `input` to avoid accidentally submitting Windows
line endings to the repository. Using `input` is a good strategy in most cases, thus you should
consider setting this as a global (add `--global`) or even as a system (`--system`) setting.

.Configure git line ending treatment
[source,text]
----
C:\> git config --global core.autocrlf input
----

After changing this setting, best do a fresh clone and check-out of WebAnno.

=== Installation guide to develop WebAnno in Eclipse

This is a guide to setting up a developer environment in Eclipse for WebAnno using Max OS X. The 
procedure should be similar for other operation systems.  

First, you need to follow some steps of the user [InstallationGuide installation guide]. You need to
configure your MySQL-server for WebAnno. After that, jump right to the chapter WebAnno and follow
all steps besides the first one until the end of the document.

We recommend you start from a *Eclipse IDE for Java Developers* package.

==== Use a JDK

On Linux or OS X, the following setting is not necessary. Having a full JDK installed on your
system is generally sufficient. You can skip on to the next section.

On Windows, you need to edit the `eclipse.ini` file and directly before the `-vmargs` line, you
have to add the following two lines. Mind to replace `C:/Program Files/Java/jdk1.8.0_144` with the actual
location of the JDK on your system. Without this, Eclipse will complain that the 
`jdk.tools:jdk.tools` artifact would be missing.

.Force Eclipse to run on a JDK
[source,text]
----
-vm
C:/Program Files/Java/jdk1.8.0_144/jre/bin/server/jvm.dll
----

==== Eclipse Plug-ins

* *Maven Integration:* m2e , already comes pre-installed with the Eclipse IDE for Java Developers.
  If you use another edition of Eclipse which does not have m2e pre-installed, go to *Help->Install
  New Software*, select "--All available sites--" and choose *Collaboration -> m2e - Maven Integration
  for Eclipse*

* *Apache UIMA tools:* Update site: `http://www.apache.org/dist/uima/eclipse-update-site/`

* *Eclipse Web Development Tooling:* go to *Help->Install New Software*, select "--All available
  sites--" and select the following plug-ins for installation from the section *Web, XML, Java EE
  and OSGi Enterprise Development*:
** Eclipse Java Web Developer Tools
** Eclipse Web Developer Tools
** Eclipse XML Editors and Tools
** JST Server Adapters
** JST Server Adapters Extensions
** JST Server UI
** m2e-wtp - Maven Integration for WTP
** WST Server Adapters

=== Eclipse Workspace Settings

* You should check that Text file encoding is UTF-8  in *Preferences -> General -> Workspace* of 
  your Eclipse install.

=== Importing {product-name} into the Workspace

Checkout out the {product-name} git repository with your favorite git client. If you use the command-line
client, use the command

[source,text]
----
$ git clone https://github.com/webanno/webanno.git
----

In Eclipse, go to *File -> Import*, choose *Existing Maven projects*, and select the folder to which
you have cloned {product-name}. Eclipse should automatically detect all modules.

=== Eclipse Tomcat Integration

Download Apache Tomcat from `http://tomcat.apache.org/` (we're using version 8.5). Then, you need to
add the Tomcat server to your runtime configuration. Go to preferences and go to
*Servers -> Runtime environments*:

// http://webanno.googlecode.com/svn/wiki/images/AddApacheTomcat.png

When prompted for an installation path, specify the folder where you extracted (or installed) Apache
Tomcat v8.5 into. 

Change the runtime configuration for the project. On the left side of the dialog, you should now be
able to select Apache Tomcat. Change its VM arguments and include the definition 
`-Dwebanno.home="/srv/webanno"` to specify the home directory for WebAnno. Also add
`-Dwicket.configuration=development` to enable the development mode for WebAnno. This adds additional
debugging features to the UI and disables UI caches.

// http://webanno.googlecode.com/svn/wiki/images/ChangeRunConfiguration.png

Head to the servers pane. If you cannot locate it in your eclipse window, add it by going to
*Window -> Show View -> Other...* and select *Servers*. Right click on *Tomcat v8.5 localhost* and
click on *Add and remove...*:

// http://webanno.googlecode.com/svn/wiki/images/AddAndRemoveServer.png

// You should end up with:

// http://webanno.googlecode.com/svn/wiki/images/AddAndRemoveServerFinal.png

{product-name} should now be configured to start with Tomcat.

In the *Servers* view, double-click on the Tomcat instance you have configured. Activate the
checkbox *Serve modules without publishing*. Go to the *Modules* tab, select the {product-name} module
and disable auto-reloading. After these changes, you will have to manually restart the Tomcat
server in order for changes to Java class files to take effect. However, as a benefit, changes to
HTML, CSS or JavaScript files take effect immediately and you just have to refresh the browser to
see the changes.

=== Checkstyle and Formatting

We use a style for formatting the source code in {product-name}. Our approach consists of two steps:

* DKPro code formatting profile - the profile configures your IDE to auto-format the code according to
  our guidelines as you go.
* Checkstyle - this tool is used to check if the source code is actually formatted according to our
  guidelines. It is run as part of a Maven build and the build fails if the code is not formatted
  properly.

Here is a brief summary of the formatting rules:
* no tabs, only spaces
* indenting using 4 spaces in Java files and 2 spaces in XML files
* maximum 100 characters per line (with a few exceptions)
* curly braces on the next line for class/method declarations, same line for logic blocks (if/for/...)
* parameter names start with `a` (e.g. `void foo(String aValue)`)

First, obtain the DKPro code formatting profile from the link:https://dkpro.github.io/contributing/[DKPro website] (Section "Code style"). In Eclipse, go to **Preferences -> Java -> Code Style -> Formatter** to import the file. Apparently, the files can also be used with IntelliJ via the [Eclipse Code Formatter](https://plugins.jetbrains.com/plugin/6546-eclipse-code-formatter) plugin.

NOTE: The parameter prefix `a` needs to be configured manually. In Eclipse go to 
       *Preferences -> Java -> Code Style* set the *prefix list* column in the *parameters* row to `a`.
       
Second, install the Checkstyle plugin for Eclipse as well as the Maven Checkstyle plugin for Eclipse.
These plugins make Eclipse automatically pick up the checkstyle configuration from the Maven project
and highlight formatting problems directly in the source code editor.

* Install *Checkstyle Eclipse plugin* from here: `http://eclipse-cs.sourceforge.net`
* Install the *Checkstyle configuration plugin for M2Eclipse* from here: `http://m2e-code-quality.github.com/m2e-code-quality/site/latest/`
* Select all {product-name} projects, right click and do a *Maven -> Update project*

NOTE: Should the steps mentioned above not have been sufficient, close all the {product-name} projects
      in Eclipse, then remove them form the workspace (not from the disk), delete any `.checkstyle` files
      in the {product-name} modules, and then re-import them into Eclipse again using *Import->Existing Maven
      projects*. During the project import, the Checkstyle configuration plugin for M2Eclipse should
      properly set up the `.checkstyle` files and activate checkstyle. 


// === Troubleshooting
// 
// If you run into problems with the last step (Add and remove...) and get the error 'There are no
// resources that can be added or removed from the server', checkout if you have installed 
// _m2eclipse-wtp_:
// 
// http://webanno.googlecode.com/svn/wiki/images/Problems%20with%20no%20resource%20available.png
// 
// and go to the project settings and check if these project facets are activated for the project. 
// If you have the _ m2eclipse-wtp_ installed, it should be sufficient to right-click on the project 
// and do a  *Maven -> Update project* to reconfigure the project and have m2e update these settings:
// 
// http://webanno.googlecode.com/svn/wiki/images/ProjectsFacets.png