= Concept features

Concept features allow linking an annotation to a concept (class, instance, property) from a 
knowledge base. 

There are two types of concept features: single-value and multi-value. A single
value feature can only link an annotation to a single concept. The single-value feature is displayed
using an auto-complete field. When a concept has been linked, its description is shown below the
auto-complete field. A multi-value concept feature allows linking the annotation up to more than
one concept. It is shown as a multi-select auto-complete field. When hovering with the mouse over
one of the linked concepts, its description is displayed as a tooltip. 

.Searching for concepts
Typing into the field triggers a query against the knowledge base and displays candidates in a
dropdown list. The query takes into account not only what is typed into the input field, but also
the annotated text.

TIP: Just press kbd:[SPACEBAR] instead of writing anything into the field to search the knowledge
     base for concepts matching the annotated text.

.Filtering
The query entered into the field only matches against the label of the knowledge base items, not
against their description. However, you can filter the candidates by their description. E.g. if you
wish to find all knowledge base items with `Obama` in the label and `president` in the description,
then you can write `Obama :: president`. A case-insensitive matching is being used.

If the knowledge base is configured for additional matching properties and the value entered into
the field matches such an additional property, then the label property will be shown separately
in the dropdown. In this case, filtering does not only apply to the description but also to the
canonical label.

.Substring matching
Depending on the knowledge base and full-text mode being used, there may be fuzzy matching. To
filter the candidate list down to those candidates which contain a particular substring, put
double quotes around the query, e.g. `"County Carlow"`. A case-insensitive matching is being used.

.IRI matching
You can enter a full concept IRI to directly link to a particular concept. Note that searching by
IRIs by substrings or short forms is not possible. The entire IRI as used by the knowledge base must
be entered. This allows linking to concepts which have no label - however, it is quite inconvenient.
It is much more convenient if you can ensure that your knowledge base offers labels for all its
concepts.

.Not finding the expected results?
The number of results displayed in the dropdown is limited. If you do not find
what you are looking for, try typing in a longer search string. If you know the IRI of the concept
you are looking for, try entering the IRI. Some knowledge bases (e.g. Wikidata) are not making a
proper distinction between classes and instances. Try configuring the *Allowed values* in
the feature settings to *any* to compensate.

.Browsing the knowledge base
Instead of searching a concept using the auto-complete field, you can also browse the knowledge
base. However, this is only possible if:

* the concept feature is bound to a specific knowledge base or the project contains only a single
  knowledge base;
* the concept feature **allowed values** setting is not set to **properties**.

Note that only concept and instances can be linked, not properties - even if the **allowed values** setting is set to **any**.
