// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_external-search-repos-pmc]]
= 🧪 PubMed Central

====
CAUTION: Experimental feature. To use this functionality, you need to enable it first by adding `external-search.pmc.enabled=true` to the `settings.properties` file (see the <<admin-guide.adoc#sect_settings, Admin Guide>>). You should also add `format.bioc.enabled=true` to enable
support for the BioC format used by this repository connector.
====

link:https://www.ncbi.nlm.nih.gov/pmc/[PubMed Central]® (PMC) is a free full-text archive of biomedical and life sciences journal literature at the U.S. National Institutes of Health's National Library of Medicine (NIH/NLM). It can be added as an external document repository by
selecting the **PubMed Central** repository type.

NOTE: {product-name} uses the BioC version of the PMC documents for import. This is only available for 
      Open Access texts. {product-name} automatically adds a filter for open access results (`"open access"[filter]`) 
      to the query. The BioC version of these texts may be available only with a delay {product-name} automatically 
      excludes results that were published in the last 24h to try to keep the number of non-importable results low. 
      If you are still unable to import a result, try a bit later.
