Getting Started

This Getting-Started-Guide shall assist new users to install and start
and work with INCEpTION. It gives a quick overview (estimated time for
reading only: approx. 15 minutes) on the main issues in order to get
familiar with the tool and does not incude special cases and details due
to simplicity and focus on the first steps. For further reading on any
issue, see our main documentation.: LINK EINFÜGEN. For quick overviews,
also see our tutorial videos (Topics: Introduction, Overview,
Recommender Basics, Entity Linking):
https://www.youtube.com/playlist?list=PL5Hz5pttaj96SlXHGRZf8KzlYvpVHIoL-

 +
_Introduction_

* What can INCEpTION be used for? (also see our introduction video for a
first impression what INCEpTION is):
https://www.youtube.com/watch?list=PL5Hz5pttaj96SlXHGRZf8KzlYvpVHIoL-&time_continue=135&v=Ely8eBKqiSI&feature=emb_logo)

* {blank}
** INCEpTION is a text-annotation enviroment useful for various kinds of
annotation projects. The core functionality is annotating any kind of
written text. Annotations can be used both for linguistic and machine
learning concerns.
** But INCEpTION is not only an annotation tool. It integrates three
steps in one plattform: creating a corpus to be annotated (*Corpus
Creation*); annotating it and merging annotations made by several
annotators (*Annotation, Curation*); and managing the knowledge used for
annotating (*Knowledge Bases*.) You may want to do one, two or all three
steps with INCEpTION. Also, it is extendable and adoptable to individual
requrements in all of these three areas. This Guide focuses on
Annotation. For details on Corpus Creation and Knowledge
Management/Knowledge Bases, see the main documentation.
+
* Tell us what you would like to have
** INCEpTION is still in developement, so you are welcome to give us
feedback and tell us your wishes and requirements. For any questions,
you are welcome to join our Google group „inception users“:
https://groups.google.com/forum/#!forum/inception-users
+
* Know our documentation for further reading
** You will find lots of information in our Guides, called documentation
(on our website, among the tabs on top: → _Documentation:_
https://inception-project.github.io/documentation/[https://inception-]https://inception-project.github.io/documentation/[project.github.io/documentation/]
. There, see the upper section.). If they do not answer your question,
don‘t hesitate to contact our team: ____ We are glad to help you.
** Whenever you find a blue questionmark-sign in INCEpTION, you may
click on it to find further explanation in the main documentation.
** For more details, see the installation guide
** For more installation, see the admin guide. You find it on our
website, among the tabs on top: → _Documentation_,
https://inception-project.github.io/releases/0.10.0/docs/admin-guide.html[h]https://inception-project.github.io/releases/0.10.0/docs/admin-guide.html[ttps://inception-project.github.io/releases/0.10.0/docs/admin-guide.html]

Installing and starting INCEpTION

* Installing Java
** In order to make INCEpTION run, you will need to install Java (in
case you do not have it yet). Here
https://java.com/en/download/help/download_options.xml#linux you find
instructions on how to install Java on Windows, Mac, Linux and Solaris.

* Download and start INCEpTION
** Now, download the .jar-file from our website
https://inception-project.github.io/ . You will find the
„Download“-Button top right. Wait a moment until it is fully downloaded.
That is, until the name of the downlauded folder ends on „.jar“, not on
„.jar.part“ anymore.
+
_Note_: We recommend working on the latest version always. So check the
website once in a while and download the new .jar-file when a later
version is available.
** Now, simply ***double-click ***on the downloaded .jar-file. After a
moment, a splash screen will display while the application is
initializing. Once the initialization is complete, a dialog appears.
Here, you can open the application in your default browser or shut it
down again.
** If you are used to the command line, you may enter this command there
instead:
+
$ java -jar inception-app-standalone-0.10.0.jar
+
In this case, no splash screen will start. Just enter
http://localhost:8080/[_http://localhost:8080_] in you browser.
** Use „admin“ as username and password to login, since a default user
with these properties is created the first time you start the
application.

* Download an example project for your first steps
** Also on our website, clicking the tab „Example Projects“ on the very
top leads you to the following page:
https://inception-project.github.io/example-projects/ . To follow this
Guide, please download the _Interactive Concept Linking_ project.
+

First Steps with INCEpTION

* You may want to watch our tutorial video „Overview“ on how to create
annotation:
https://www.youtube.com/watch?v=wp4AN3p23mQ&list=PL5Hz5pttaj96SlXHGRZf8KzlYvpVHIoL-&index=3&t=0s
* In order to import our example project, after logging into INCEpTION,
click on the blue folder on the top right (next to „Import project
archives“) and browse for the example project you have downloaded
before. Finally, click the grey **upload-**Butten right next to the blue
folder to upload the selected project.

* The project has now been added. Choose it by clicking on it and you
will be on the dashboard of this project. Select *Annotation* on the top
left and choose _pets1.tsv_ (the first file) in the window which now
opened.
* You will see several annotations already. If you import a documents
without annotations yet, there will be none. But in the example
projects, we have added some annotations already to show you some
examples of annotations.
* To create your first annotation, let‘s start with Part of Speech
Tagging: Select *POS* from the *Layer* dropdown on the top right. When
you click on a word in the text (e.g. „does“, in line 4), an annotation
is immediately created and you can edit its details in the panels at the
right (e.g. choose „VERB“ in the PosValue-dropdown to lable it as a
verb).

Congratulations! You have created your first annotation!

* Let‘s examine the right panel:

* {blank}
** You find the field „Layer“ on top and „Annotation“ below. In the
*Layer*-dropdown, you can choose the layer you want to annotate with as
we yust did. You find several default layers linke Part Of Speech or
Named Entity already. You can also adjust them and create own layers in
the project settings (we will deal with the project settings later on).
INCEpTION supports span layers (annotating a span in the text, e.g. from
the 51th character („letter“) in the text to the 55th) and relation
layers (annotating two span annotations). For span layers, the default
is to always annotate one or more tokens („words“) but you can adjust to
character level or sentence level. For more details, see the main
documentation. LINK EINFÜGEN.
** In the field *Annotation* below, you see the details of a selected
annotation. It shows the layer the annotation is made on (field „layer“)
and what has been annotated (field „text“). Below, you can see and
modify what has been entered for each of the so called *Features*. Each
layer has different features. E.g. on the Part of Speech-layer, the
PosValue-feature tells if the token is a noun/verb/adjective/… See the
main documentation for the different feature types and how to adjust
features for your individual task. LINK EINFÜGEN
+
You may enter free text here or work with *Tagsets* to have a well
defined set of values to enter. You can modify and create tagsets in the
project settings (section „Tagsets“) which we will deal with later. See
our main documentation on how to create and modify tagsets. LINK
EINFÜGEN
* In the **Annotation Sidebar **at the left (it folds out when clicking
on the little arrow on top) there are several features you might want to
check the main documentation for. Especially the *Recommender* section
(the black speech bubble) is worth a look if you use recommenders
(recommenders will be explained later on in this guide). E.g. you find
their measures and learning behaviours. Note the *Search* (the magnifier
glass): You can create or delete annotations on all or some of the
search results.
* To get familiar with INCEpTION, you may want to follow the
instructions for your example-project which are on the website where you
downloaded it or explore INCEpTION yourself, learning by doing.
+
One way or the other: *Have fun exploring*!

Anatomy of an annotation project

* In order to work with your own projects, you might want to understand
the anatomy of an INCEpTION project. Let‘s see what the dashboard
(clicking on the dashboard button on the top) provides: As a Project
Manager of a project, you see all of the following sub pages (roles and
rights will be presented later on in this guide). For details on each
section, check the main documentation.
** *Annotation*: We have been here already. Here, you can make your
annotationsjust loke before.
** *Curation*: If several annotators work on a project, you may want a
curator to finally decide which annotations to accept. Everyone with
curation rights (see below) within this project can curate. All others
do not have access to nor see this page. Only documents marked as
finished by at least one annotator can be curated. For details on how to
courate, see the main documentation LINK EINFÜGEN or just try it out:
*** Add another fake user (see below)
*** Create some annotations in any document
*** Mark the document as finished: Just click on the lock on top.
*** Log out and log in again as the fake user.
*** In the very same document, make some annotations exactly like before
but also some which are different. Mark the document as finished.
*** Log in as any user with couration rights (e.g. the „admin“ user we
used before), enter the couration page and explore how to courate: You
see the automatic merge on top (what was equal from both users is being
accepted already) and the annotations of each of the users below.
Differences are highlightet. You can accept an annotation by clicking on
it. You can also create new annotations.
** *Knowledge Base*: On this sub page, you can manage and create your
knowledge bases for this project. You can create new ones from the
scratch, modify existing ones and integrate remote or local knowledge
bases into your project.
** **Monitoring: **Here you can check the overall progress of your
project; which user is working on or has finished which document; and
for each user, you can toggle the status of each document between
***Done****/****In Progress ****or between **New / Locked**.***
** Agreement: On this page, you can calculate the agreement of you
annotators‘ work. Four different measures for agreement are provided.
_Note:_ Only documents marked as finished by annotators (clicking on the
little lock on the annotation page) are taken into account.
** *Evaluation*: The evaluation page shows a learning courve diagram of
each recommender (we will explain recommenders later on on this guide).
** *Settings*: This is the heart of your project. Here, you can
organize, manage and adjust all details of your project. We will look at
the ones you need to get started for your own projects. For a quick
overview on the settings, you might want to watch our tutorial video
„Overview“:
https://www.youtube.com/watch?v=wp4AN3p23mQ&list=PL5Hz5pttaj96SlXHGRZf8KzlYvpVHIoL-&index=3&t=0s.

* Each project consist of
** One or more *documents* to annotate
** *Users* to work on the project
** *Layers* to annotate with
** Optional: one or more *Knowledge Base/s*
** Optional: *Recomenders* to automatically suggest annotations
** Optional: *Guidelines* for your team

and you find all of these in the project *settings* just mentioned.
Again, for details on any section/topic mentioned, please check the main
documentation.

* In the section **Documents, **you may upload your files to be
annotated. Make sure that the format selected (see the dropdown on the
right) is the same as the file.
* In the section **Users, **you may add users to your project and change
their rights in this project. You can only add existing users here from
the dropdown (left).
** In order to *add new users* so they can be chosen from this dropdown,
click on „*administration*“- button in the very top right corner and
select section *Users* on the left. For *user roles* (within the whole
instance of INCEpTION) see
https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/INCEpTION%20(GitHub)%20(master)/de.tudarmstadt.ukp.inception.app$inception-app-webapp/doclinks/1/#sect_users
** *Selecting a user from the dropdown* in the project settings section
*Users*, you can check/unchek the *user‘s rights *(they are different
from roles and count for this project only) on the right side. Any
combination is possible and the user will always have _all_ rights
combined.

[cols=",,",]
|===
|User right |Description |*Access to Dashborad Sections *

|Annotator |- annotate only a|
- Annotation

- Knowledge Base

|Courator |- curate only a|
- Couration

- Monitoring

- Agreement

- Evaluation

|Project Manager |- annotate +
- courate +
- create projects +
- add new documents +
- add guidelines +
- manage users +
- open documents like an other user sees it (read only) |All pages
available
|===

* In the section **Layers, **you may modify existing layers to use for
your annotation and create own layers. In case you do not want to work
on default layers only, we highly recommend reading the main
documentation on layers. LINK EINFÜGEN
* In the section **Knowledge Base, **you can change the settings for the
knowledge bases used in your project and also import local and remote
knowledgebases or create a new one. Herefore, just click the
„create“-button and follow the wizzard.
** Note that you can have several knowledge bases in your INCEpTION
instance but you can choose for every project which one(s) to use. Using
many knowledge bases in one project will slow down the performance.
** Via the *Dashboard* (click the Dashboard-button at the top centre),
you can get to the knowledge base page. This is a page different from
the one in the project settings where you can modify and work on your
knowledge bases.
** For details on knowledge bases, see our main documentation LINK
EINFÜGEN or our tutorial video „Overview“ which also talks about
knowledge bases quickly:
https://www.youtube.com/watch?v=wp4AN3p23mQ&list=PL5Hz5pttaj96SlXHGRZf8KzlYvpVHIoL-&index=3&t=0s..
If you like to explore a knowledge base learning by doing, you may
download and import the example project _Interactive Concept Linking_:
https://inception-project.github.io/example-projects/concept-linking/
which contains a small knowledge base.
* In the section **Recommenders, **you can create and modify your
recommenders. They learn from your behaviour and give automatic
suggestions for creating annotations. For details on this topic to broad
for a getting-started-guide, see our main documentation LINK EINFÜGEN or
our tutorial video „Recommender Basics“:
https://www.youtube.com/watch?v=Xz3Hs8Lyoeg&list=PL5Hz5pttaj96SlXHGRZf8KzlYvpVHIoL-&index=3
.

* In the *Guidelines* section, you may import guideline files for your
team to read and to check quickly while working. On the annotation page
(→ _dashboard_ → _annotation_ → open any document), everyone can quickly
look them up by clicking on the guidelines button on the top (it looks
like a book).

* We have imported a whole project already (the example project) as well
as single documents (in the **documents **section). In the **Export
**section, you can export your project partially or wholly. Projects
which have been exported can be imported again in INCEpTION the way we
did before: at the start page with the *Import* button. We recommend
exporting projects on a regular basis in order to have a backup. For the
different formats, their strengths and weaknesses, check our main
documentation LINK EINFÜGEN. We recommend using WebAnno TSV x.x (where
x.x. is the highest number available, e.g. 3.2) whenever possible. Since
it has been created specially for this application, it ill provide all
features required best. However, many other formats are provided.

We hope this guide helped you with your first steps on INCEpTION and it
gave you a general idea of hiw INCEpTION works. As mentioned before, our
main documentation provides deep information on every issue. Don‘t
hestitate to contact us if you struggle or have any questions. We wish
you success and fun with your projects. Let us know how you are doing!

For advanced ...see [#anchor]####Advanced functionalities[#anchor-1]####
Corpus building LINK EINFÜGEN

------------------------------------------------------------------------------------------------------------------------

Hier die Struktur, an der ich mich orientiert habe:

X = nicht übernommen

V (Häkchen) = übernommen

? = was meint ihr damit?

* ? Workflow
* ? Annotation project phases

* V Core functionality

* X Annotation structure/Annotation schema
** Also describe setup here
** layer types
** Write what layers are
** Span
** Relation
** Chain
* V Features types
** Write what features are
** Only core features here
** For more complex features, write a short description (1-2 sentences)
and link
* X Behaviours
* X Granularity

* V Import/Export

* V Annotation page

* X Action bar
* ? Open doc
* ? Annotation detail editor
* V(X) Sidebars
** V Search sidebar
** (V) Recommender sidebar

* V Knowledge bases

* V Curation

* V Monitoring

* X Workload management

* V Quality assurance (Agreement)

* V User management

* X Advanced stuff

* (X) Tagsets
* X Constraints
* V Recommenders
* X Entity and fact linking
* X Document repository (external search)
* V Guidelines
* X+? Cas doctor

* ? Appendices

* X Supported document formats
* X WebAnno TSV 3.2 file format specification (ggf. in sep Dok
auslagern)
* X MTAS syntax
* X Glossary
* X Recommender types
