// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_settings_concept-linking]]
= Concept Linking

There are several configurable parameters related to the Concept Linking functionality:

.Cache size
This parameter controls the size of the Candidate Cache, which stores a set of candidates for a mention.
Increasing the cache size will reduce the number of queries that have to be made against the KB
and therefore increase average retrieval time.

.Candidate Frequency Threshold
This parameter controls after how many concepts the ranking approach should take into account by
selecting the `n` most frequent concepts. Increasing this parameter will lead to a longer ranking time,
since more candidates are considered for ranking.

.Mention Context Size
This parameter declares the size `k` of the context, where the context is defined as the words
included in a window with `k` words to both left and right.

.Candidate Retrieval Limit
This parameter defines how many concepts should be retrieved for the Candidate Retrieval step.
Increasing this parameter will lead to a longer time to retrieve candidates from the KB.

.Semantic Signature Query Limit
This parameter defines how many concepts should be retrieved for the Semantic Signature of a candidate.
Increasing this parameter will lead to a longer time to retrieve concepts for constructing the Semantic Signature.

.Candidate Display Limit
This parameter regulates how many candidates will be displayed for a mention in the Concept Selector UI.

If no value for a parameter is specified, its default value is used. The default values are shown as
examples of how the parameters can be configured below:

.Concept linking settings overview
[cols="4*", options="header"]
|===
| Setting
| Description
| Default
| Example

| inception.entity-linking.cacheSize
| Cache size
| 1024
| -

| inception.entity-linking.candidateQueryLimit
| Candidate Retrieval Limit
| 2500
| -

| inception.entity-linking.mentionContextSize
| Mention Context Size
| 5
| -

| inception.entity-linking.candidateDisplayLimit
| Candidate Display Limit
| 100
| -

| inception.entity-linking.signatureQueryLimit
| Semantic Signature Query Limit
| 2147483647
| -
|===

== Resources

In order to improve the quality of suggestions, several additional resources can be incorporated.
These are to be put into the `.inception/resources` folder. These include:

* properties_with_labels.txt
- List of properties, each line containing information for one property, tab-separated
|===
| ID | Label | Description | Aliases | Data type | Count
|P6
|head of government
|head of the executive power of this town, city, municipality, state,
 country, or other governmental body
|government headed by, executive power headed by, president, chancellor
|wikibase-item
|17,592
|===

* property_blacklist.txt
- A list of properties that are filtered when computing the Semantic Signature, one property ID per line,
e.g. `P1005`, `P1014`


* stopwords-en.txt
- A list of stopwords, one stopword per line, e.g. `i`, `me`

* wikidata_entity_freqs.map
- Each line consists of a the ID of a concept and its frequency in the KB, tab-separated,
e.g. `Q4664130  409104, Q30 205747`

