// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_projects_annotation_sidebar]]
= Annotation sidebar

.Pinned Groups
This setting allows configuring groups which are always visible in the annotation sidebar on the
annotation page when the sidebar is in **group by label** mode.

Consider a situation where annotators should always locate one or more mentions of a particular 
concept in every document.
Configuring the labels of these concepts as pinned groups will show them in the sidebar, even if the annotator has not yet created an annotation for them.
This can help the annotator to see which concepts still need to be located and annotated in the text.

This functionality can also be used to enforce a particular order of groups if the automatic alphabetic sorting is not convenient.

Note that groups are formed by the label of an annotation which consists of the concatenated feature values.
Thus, for annotations that have multiple features included in their labels, you need to pay close attention to exactly match the rendered labels in your pinned groups (wildcards are not 
supported!).
You might consider excluding non-essential features from the label by unchecking the option **Visible** in the settings for the respective feature.
