= Releasing

== Prerequisites

When releasing and publishing the resulting artifact, make sure that you actually have the rights
to publish new artifacts to the target repository. See e.g.
https://maven.apache.org/settings.html#Servers[the Maven documentation authentication] 
for more information on how to do this. Additionally, this documentation assumes that you have write permissions
to the protected `main` branch and to the protected maintenance branches.

== Branching model

INCEpTION uses a branching model where the development towards the next feature release happens on the
`main`. Additionally, there are *maintenance* (also called *stable*) branches for all past feature 
releases which are used to create bugfix releases when necessary (`0.1.x`, `0.2.x`, `0.3.x` etc.). 

To prepare a new feature release, we first create a maintenance branch from `main`. Assuming the current
development version on the `main` branch is `0.8.0-SNAPSHOT`, we create a maintenance branch by the name
`0.8.x`. After this, the version on the `main` branch must be manually updated to the next feature version,
typically by increasing the second digit of the version (e.g. `0.8.0-SNAPSHOT` becomes `0.9.0-SNAPSHOT`).

The process of doing the initial feature release on a new maintenance branch (e.g. for version `0.8.0`) is 
largely the same then as for performing a bugfix release (e.g. for version `0.8.1`) as described in the next section.

Changes are usually not committed directly to the `main` or maintenance branches. Instead we work with
*feature* branches. Feature branches for new enhancements or refactorings are normally made from the 
`main` branch. Feature branches for bugfixes are made from a maintenance branch (unless the bug only 
exists on the `main` branch or is too difficult to fix without extensive refactoring and risk of 
breaking other things). After accepting a pull request for a bugfix to a maintenance branch, a developer
with write access to the `main` branch should regularly merge the maintenance branch into the `main` branch
to have the fix both in maintenance and `main`. From time to time, a new bugfix release is made. Here, the third digit
of the version is increased (e.g. from `0.8.0` to `0.8.1`). 

The first digit of the version can be increased to indicate e.g. major improvements, major technological
changes or incompatible changes. This is done only very rarely (maybe once every 1-3 years). 

== Release steps

For the sake of this guide, we assume that `0.8.x`
is the most recent maintenance branch.

For these steps, we assume push permissions to the `main` branch. If these are not given, pull
requests have to be used for the relevant steps. For pull requests the target branch will need to be branched first 
and then other branches can be merged into it. E.g. for a bugfix release as a first step the bugfix branch needs to be merged into `main`
to transfer bugfixes to the development version. In this case, you need to create a new branch from the `main` branch, then merge branch `0.8.x`
into this new branch and finally create the pull request to merge this new branch into `main`.


== Bugfix release preparations

Do this when you want to do a bugfix release.

. Create a bugfix release issue in the INCEpTION Github issue tracker
. Checkout the `main` branch: e.g. `git checkout main`
. Merge the maintenance into the `main` branch; this makes sure that all bugfixes are
  also applied to `main`: e.g. `git merge 0.8.x` and then `git push`
. Checkout the maintenance branch of which you want to make a bugfix release, by e.g. `git checkout 0.8.x`

== Feature release preparations

Do this when you want to do a feature release.

. Checkout `main` and make sure that you pulled the most recent version of it
. Create a new branch from `main` and name it according to the new version with the last digit (the bugfix part of the version) being `x`, by e.g. `git checkout -b 0.9.x`

== Running the release process

. Check that the release branch depends on the right WebAnno release or update it in the top-level `pom.xml` (properties -> `webanno.version`).
. Check that the JDK version you are using corresponds to the minimum Java version specified in the system requirements section of the documentation. Building against a newer version might create a release that will not run on the minimum required version because usages of APIs not available in the minimum version may not be detected. You can check the JDK version that Maven is using with `mvn -version` and change it (temporarily) by setting `JAVA_HOME` to the path of the JDK version you need: `export JAVA_HOME="/path/to/jvm"`.
. Run `mvn release:prepare`; this step will ask you for the release version (e.g. `0.9.0`) for the tag to be created (e.g. `inception-app-0.9.0`), and for the new development version (e.g. `0.10.0-SNAPSHOT`). After that, it will update the version (push), build the code, and create a tag (push).
. Run `mvn release:perform`; this will check out the created tag into the folder `target/checkout` and build the release artifacts there.
. Immediately after the release, again merge the released branch into the
  `main` branch, using e.g. `git checkout main` and `git merge -s ours 0.9.x` and `git push`. 
  Doing this second merge does not actually change anything in the `main` branch. 
  However, it ensures that the updates to the version number in the released_branch (e.g.  `0.9.x`) will not make it to the `main` branch.
. The released jar is now in `target/checkout/inception-app-webapp/target/` (*not* in `inception-app-webapp/target/`), look for the standalone jar.

== Making the release available

[arabic]
. Sign the standalone jar using `gpg --detach-sign --armor`. This creates the signature in a separate file. Attach both files to
the link:https://github.com/inception-project/inception/releases[GitHub release] that
you are currently preparing. GitHub automatically creates a stub release for every tag
and the Maven release process has automatically created such a tag for your release. The issues
that were solved with this release can be found by filtering issues by milestones.

== Update GitHub milestones

After the release you will need to close the respective milestone on Github to prevent further issues or pull requests being assigned to it.

== Deploy the new release

In order to deploy the new version, see the <<admin-guide.adoc#sect_upgrade,upgrade process>> 
in the Administrator Guide. After the new version was successfully deployed, the footer on the webpage 
of the running inception instance will show the release version.

== Updating documentation

Checkout or go into the `inception-project.github.io` repository and
create a new branch. In order to publish the documentation for this new
release, copy the data from the INCEpTION repository that was just
released under
`target/checkout/inception-app-webapp/target/generated-docs` into a
version folder under `releases/{version}/docs` in the documentation
repository. Also update the `_data/releases.yml` file. Create a pull
request for this as well.

== Publish to GitHub Packages

Make sure that you configured your docker user in your Maven settings:

[source,xml]
----
<server>
  <id>docker.io</id>
  <username>user</username>
  <password>password</password>
</server>
----

Also, your user needs to have push rights to the `ghcr.io/inception-project` GitHub package repository.
If you have just made a release, change to `target/checkout/inception-docker`. Otherwise check out the release
tag e.g. via `git checkout tags/inception-app-0.18.0`. 
Make sure that in the top-level POM, the version is set to a release version (no snapshot suffix).
Then go to the `inception-docker` module folder and there run the following commands:

[source,xml]
----
mvn -Pdocker clean docker:build -Ddocker.image.name="ghcr.io/inception-project/inception"
mvn -Pdocker docker:push -Ddocker.image.name="ghcr.io/inception-project/inception"
----

After successfully publishing, the GitHub package repository will show your released
version as the latest version.

== Aborting and re-running a release

If for some reason the release process failed, re-run the maven command during which the process was aborted 
(i.e. `mvn release:prepare` or `mvn release:perform`). Maven should repeat any failed steps of the respective process.

If you need to abort the release process use `mvn release:rollback`. However, in this case, you also need to check
if the release tag was already created. You then might need to manually remove it. You might also need to revert the commits 
that were created during the release to re-set the version to the previous state. 
This can be done with `git revert <commit>`.
