/* Generated By:JJTree: Do not edit this line. ASTCondition.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.tudarmstadt.ukp.clarin.webanno.constraints.grammar;

public class ASTCondition
    extends SimpleNode
{
    private ASTPath path;
    private String value;

    public ASTCondition(int id)
    {
        super(id);
    }

    public ASTCondition(ConstraintsParser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(ConstraintsParserVisitor visitor, Object data)
    {

        return visitor.visit(this, data);
    }

    public ASTPath getPath()
    {
        return path;
    }

    public void setPath(ASTPath aPath)
    {
        path = aPath;
    }

    public String getValue()
    {
        return value;
    }

    public void setValue(String aValue)
    {
        value = aValue;
    }
}
/* JavaCC - OriginalChecksum=262aff308ecbb2c95f7af26c1b819e14 (do not edit this line) */
