/* Generated By:JJTree: Do not edit this line. ASTRuleDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.tudarmstadt.ukp.clarin.webanno.constraints.grammar;

public class ASTRule
    extends SimpleNode
{
    private ASTConditions conditions;
    private ASTRestrictions restrictions;

    public ASTRule(int id)
    {
        super(id);
    }

    public ASTRule(ConstraintsParser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(ConstraintsParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public void setConditions(ASTConditions aConditions)
    {
        conditions = aConditions;
    }

    public ASTConditions getConditions()
    {
        return conditions;
    }

    public void setRestrictions(ASTRestrictions aRestrictions)
    {
        restrictions = aRestrictions;
    }

    public ASTRestrictions getRestrictions()
    {
        return restrictions;
    }
}
/* JavaCC - OriginalChecksum=5211ec9745acbb924daf6ef1958d22f1 (do not edit this line) */
