kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "inception.persistence.pvc.name" . }}
spec:
  storageClassName: {{ .Values.persistence.data.storageClassName }}
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}