// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_activeLearning]]
= Active Learning

The active learning module aims to guide the user through recommendations in such a way that the
the judgements made by the user are most informative to the recommenders. The goal is to reduce
the required user interactions to a minimum. The module consists of the following classes and
interfaces:

* The `ActiveLearningService` interface and its default implementation `ActiveLearningServiceImpl`
  which provide access to the ranked suggestions.
* The `ActiveLearningStrategy` interface which allows plugging in different sampling strategies.
* The `UncertaintySamplingStrategy` class which is currently the only sampling strategy available.
* The `ActiveLearningSidebar` class which provides the active learning sidebar for the annotation
  page. Here the user can accept/reject/correct/skip suggestions.
  
The active learning module relies on the recommendation module for the actual annotation
recommendations. This means that the active learning module does not directly make use of the
user feedback. If suggestions are accepted, they are used in the next train/predict run of the 
recommendation module as training data. The active learning module then samples the new annotation
suggestions from this run and updates the order in which it offers the suggestions to the user.

[plantuml]
....
package "webanno-ui-annotation" {
  [AnnotationPage]
}

package "inception-active-learning" {
  [ActiveLearningService]
  [ActiveLearningSidebar]
  [ActiveLearningStrategy]
  [UncertaintySamplingStrategy]
}

package "inception-recommendation" {
  [RecommendationService]
  [LearningRecordService]
}

AnnotationPage -- ActiveLearningSidebar
ActiveLearningSidebar -- ActiveLearningService
ActiveLearningService -- ActiveLearningStrategy
ActiveLearningService -- RecommendationService
ActiveLearningService -- LearningRecordService
ActiveLearningStrategy <|-- UncertaintySamplingStrategy
....

.Events
* `ActiveLearningSuggestionOfferedEvent` - active learning has pointed the user at a recommentation
* `ActiveLearningRecommendationEvent` - user has accepted/rejected a recommendation
* `ActiveLearningSessionStartedEvent` - user has opened an active learning session
* `ActiveLearningSessionCompletedEvent` - user has closed the active learning session

== Sampling strategies

[[sect_activeLearning_uncertaintySampling]]
=== Uncertainty sampling
Currently, there is only a single sampling strategy, namely the `UncertaintySamplingStrategy`. It
it compares the scores of the annotation suggestion. The smaller the difference between
the best and the second best score, the earlier the suggestion is proposed to the user. The 
scores produced by different recommenders can be on different scales and are therefore
not really comparable. Thus, the strategy only compares suggestions from the same recommender to
each other. So if recommender A produces two suggestions X and Y, they are compared to each other.
However, if there are two recommenders A and B producing each one suggestion X and Y, then X and Y
are not compared to each other.

