= Releasing INCEpTION

== Prerequisites

When releasing and publishing the resulting artifact, make sure that you have actually the rights
to publish new artifacts to the target repository. See e.g.
https://maven.apache.org/settings.html#Servers[the Maven documentationon authentication] or
https://dkpro.github.io/dkpro-core/pages/setup-maven[DKPro Core - Setting up Maven repository]
for more information on how to do this.

== Branching model

INCEpTION uses a branching model where new features are added to master. When a stable version is
release, it is branched from master and called after the to be release version where the last digit is
replace by an `x`, e.g. `0.8.x`. Bugfixes are in general performed by branching from the stable
version in which the error occurs. Afterwards, this stable branch is then merged back into master to
have the fix both in stable and master. From time to time, a new stable minor version is
released (bugfix release).

== Release steps

For these steps, we assume push permissions to the master branch. If these are not given, pull
requests have to be used for the relevant steps. For the sake of this guide, we assume that `0.8.x`
is the latest stable version.

== Bugfix release preparations

Do this when you want to do a bugfix release.

. Create a bugfix release issue in the INCEpTION Github issue tracker
. Checkout the stable branch of which you want to make a bugfix release, by e.g. `git checkout 0.8.x`
. Merge the branch you just created into the master branch; this makes sure that all bugfixes are
  also applied to master git merge:

[source,bash]
----
git checkout master
git merge 0.8.x
----

== Stable release preparations

Do this when you want to do a stable release.

. Checkout master and make sure that you pulled the most recent version of it
. Create a new branch from master and call it after the release you want to do, by e.g. `git checkout -b 0.9.x`

== Running the release process

. Run `mvn release:prepare release:perform`; the released jar is then in
  `target/checkout/inception-app-webapp/target/`, look for the standalone jar
. Immediately after the release, again merge the released branch into the
  master branch, using e.g. `git merge -s ours 0.9.x`. Doing this second merge does
  not actually change anything in the master. However, it ensures that the updates to the
  version number in the released_branch (e.g.  `0.9.x`) will not make it to the master branch.

== Making the release available

[arabic]
. Sign the jar with `gpg --detach-sign --armor`. Use these files to
create a new release under https://github.com/inception-project/inception/releases . The issues
that were solved with this release can be found by filtering issues by milestones.

== Deploy the new release

In order to deploy the new version, see the https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/INCEpTION%20(GitHub)%20(master)/de.tudarmstadt.ukp.inception.app$inception-app-webapp/doclinks/2/#sect_upgrade[Admin Upgrading Guide].

== Updating documentation

Checkout or or go into the `inception-project.github.io` repository and
create a new branch. In order to publish the documentation for this new
release, copy the data from the INCEpTION repository that was just
released under
`target/checkout/inception-app-webapp/target/generated-docs` into a
version folder under `releases/docs/{version}` in the documentation
repoository. Also updating the `_data/releases.yml` file. Create a pull
request for this as well.

== Publish to docker

Make sure that you configured your docker user in your maven settings:

[source,xml]
----
<server>
    <id>docker.io</id>
    <username>user</username>
    <password>password</password>
</server>
----

Also, your user needs to have push rights to the `inceptionproject` Dockerhub group.
Check out the release tag, make sure that in the master pom, the version is set to
a release version (no snapshot suffix). Then run

[source,xml]
----
mvn -Pdocker clean install docker:build -Ddocker.image.name="inceptionproject/inception"
mvn -Pdocker clean install docker:push -Ddocker.image.name="inceptionproject/inception"
----
