// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_upgrade]]
== Upgrade

This section describes how to upgrade the standalone version of WebAnno using an embedded database. For further information on how to upgrade WebAnno, in particular the WAR version, when using a MySQL database, or older versions of WebAnno, please refer to the <<admin-guide.adoc#,Administrator Guide>>.

=== Make a backup

Before any upgrade, make a copy of your WebAnno home folder.

IMPORTANT: If WebAnno is configured to use an external database, e.g. MySQL, make a backup of this
         database as well. See the <<admin-guide.adoc#,Administrator Guide>> for further information.

=== Upgrade from 2.0.x to 2.1.x

* clean up the temporary installation before running the new version:
** On OS X: `rm -R "$TMPDIR/winstoneEmbeddedWAR"`
** On Linux: `rm -R /tmp/winstoneEmbeddedWAR`
** On Windows: remove the `winstoneEmbeddedWAR` that should be somewhere under `C:\Users\<username>\AppData\Local\Temp`
* start the new version

