// Copyright 2016
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_webannotsv]]
= WebAnno TSV File format

In this section, we will discuss the TSV (Tab Separated Value) WebAnno file format. The format is similar to the CoNNL file formats with specialized additions to the header and column representations. The file format inhabits a header and a body section. The *header* section present information about the different types of annotation layers and features used in the file. While importing the WebAnno TSV file, the specified headers should be first created in to the running WebAnno project. Otherwise, the importing of the file will not be possible.

The *body* section of the TSV file presents the document and all the associated annotations including sentence and token annotations.

== Header Section

Layers are marked by the *#* character followed by *T_SP=*for `span types` (including `slot features`), *T_CH=*for `chain layers`, and *T_RL=*for `relation layers`. 
Every layer is written in new line, followed by the features in the layer

If all layer type exists, first, all the span layers will be written and then the chain layer and finally the relation layers.

Features are separated by the *|* character and only the short name of the feature is provided.

Example: `#T_SP=webanno.custom.Pred|bestSense|lemmaMapped|senseId|senseMapped`
 
Here the layer name is `webanno.custom.Pred` and the features are named `bestSense`, `lemmaMapped`, `senseId`, `senseMapped`.
Slot features start with a prefix `ROLE_`followed by the name of the role and the link. The role feature name and the link feature name are separated by the *_* character.

The target of the slot feature always follows the role/link name

Example: `#T_SP=webanno.custom.SemPred|ROLE_webanno.custom.SemPred:RoleSet_webanno.custom.SemPredRoleSetLink|uima.tcas.Annotation|aFrame`


Here the name of the role is  `webanno.custom.SemPred:RoleSet` and the name of the role link is `webanno.custom.SemPredRoleSetLink` and the target type is `uima.tcas.Annotation`

Chain layers will have always two features, `referenceType` and `referenceRelation`

Example: 
`#T_CH=de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink|referenceType|referenceRelation`

Relation layers will come at last in the list and the very last entry in the features will be the type of the base (governor or dependent) annotations with a prefix `BT_`.

Example: 
`#T_RL=de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency|DependencyType|BT_de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS`

Here, the relation type `de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency` has a feature `DependencyType` and the relation is between a base type of `de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS`.

== Annotations Section

In this section we discuss the different representations of texts and annotation in WebAnno TSV3format

=== Sentence Representation

Sentence annotations are presented following the text marker `#Text=`, before the token annotations.
Example

`#Text=Bell , based in Los Angeles , makes and distributes electronic , computer and building products .`

The sentence annotation do not include offsets and mainly presented as additional information. Re-importing the WebAnno TSV file construct sentences from the token annotations.

=== Token and Sub-token Annotations

Token annotation starts with a `sentence-token` number marker followed by the begin-end offsets and the token itself, separated by a TAB characters. 

Example

`1-2	4-8	Haag`

Here `1` indicates the sentence number, `2` indicates the token number (here, the second token in the first sentence) and `4` is the begin offset of the token and `8` is the end offset of the toke while `Haag` is the token.

Sub-token representations are affixed with a `.` and a number starts from 1 to N. 

Exampel

`1-3	9-14	plays`

`1-3.1	9-13	play`

`1-3.2	13-14	s`

Here, the sub-token `play` is indicated by sentence-token number `1-3.1` and the sub-token `s` is indicated by `1-3.2`. 
