/*
 * Copyright 2018
 * Ubiquitous Knowledge Processing (UKP) Lab
 * Technische Universität Darmstadt
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.tudarmstadt.ukp.inception.recommendation.api.model;

import static java.util.Arrays.asList;
import static java.util.Collections.emptyMap;
import static java.util.Collections.singletonMap;
import static java.util.Collections.sort;
import static java.util.Collections.unmodifiableList;
import static java.util.Collections.unmodifiableMap;
import static java.util.Comparator.comparing;
import static java.util.stream.Collectors.groupingBy;
import static java.util.stream.Collectors.toList;
import static org.apache.commons.collections4.IteratorUtils.unmodifiableIterator;

import java.io.Serializable;
import java.util.AbstractCollection;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.SortedMap;
import java.util.TreeMap;
import java.util.function.BiConsumer;
import java.util.function.BinaryOperator;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.stream.Collector;
import java.util.stream.Stream;

import org.apache.commons.lang3.Validate;
import org.apache.commons.lang3.builder.CompareToBuilder;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

/**
 * Group of alternative suggestions generated by one or more recommenders. The group maintains an
 * order of the alternative suggestions, by default using the confidence score.
 */
public class SuggestionGroup<T extends AnnotationSuggestion_ImplBase>
    extends AbstractCollection<T>
    implements Serializable
{
    private static final long serialVersionUID = 8729617486073480240L;
    
    private final List<T> suggestions;
    private boolean sorted = true;
    private Position position;
    private String feature;
    private long layerId;
    private String documentName;

    public SuggestionGroup()
    {
        suggestions = new ArrayList<>();
    }
    
    public SuggestionGroup(T... aItems)
    {
        suggestions = new ArrayList<>(asList(aItems));
        sorted = suggestions.size() < 2;
        if (!suggestions.isEmpty()) {
            position = suggestions.get(0).getPosition();
            feature = get(0).getFeature();
            layerId = get(0).getLayerId();
            documentName = get(0).getDocumentName();
        }
    }

    public String getFeature()
    {
        return feature;
    }

    public long getLayerId()
    {
        return layerId;
    }

    public String getDocumentName()
    {
        return documentName;
    }
    
    public Position getPosition()
    {
        return position;
    }
    
    public T get(int aIndex)
    {
        return suggestions.get(aIndex);
    }
    
    private void ensureSortedState()
    {
        // To the outside, the group should appear to be sorted.
        if (!sorted) {
            sort(suggestions, comparing(AnnotationSuggestion_ImplBase::getConfidence).reversed());
            sorted = true;
        }
    }
    
    @Override
    public Stream<T> stream()
    {
        ensureSortedState();
        return suggestions.stream();
    }
    
    /**
     * Get the deltas of all candidates. The deltas are calculated separately for each recommender
     * if the group contains recommendations from multiple recommenders. That is necessary because
     * the confidence scores of different recommenders are not necessarily on the same scale.
     * Additionally, only suggestions that are {@link SpanSuggestion#isVisible() visible} are
     * taken into consideration.
     */
    public Map<Long, List<Delta<T>>> getAllDeltas()
    {
        if (isEmpty()) {
            return emptyMap();
        }
        else if (size() == 1) {
            T top = get(0);
            return singletonMap(top.getRecommenderId(), asList(new Delta(top)));
        }
        else {
            // Group the suggestions by recommender because the confidence scores cannot be compared
            // across recommenders
            Map<Long, List<T>> suggestionsByRecommenders = stream()
                    .collect(groupingBy(AnnotationSuggestion_ImplBase::getRecommenderId));

            Map<Long, List<Delta<T>>> result = new HashMap<>();
            for (Entry<Long, List<T>> e : suggestionsByRecommenders.entrySet()) {
                long recommenderId = e.getKey();
                // We consider only candidates that are visible
                List<T> candidates = e.getValue().stream()
                        .filter(AnnotationSuggestion_ImplBase::isVisible).collect(toList());
                List<Delta<T>> deltas = new ArrayList<>();
                
                Iterator<T> i = candidates.iterator();
                T first = i.next();
                while (i.hasNext()) {
                    T second = i.next();
                    deltas.add(new Delta<T>(first, second));
                    first = second;
                }
                deltas.add(new Delta<T>(first));
                
                result.put(recommenderId, unmodifiableList(deltas));
            }
            
            return unmodifiableMap(result);
        }
    }

    /**
     * Get the top delta per recommender. The deltas are calculated separately for each recommender
     * if the group contains recommendations from multiple recommenders. That is necessary because
     * the confidence scores of different recommenders are not necessarily on the same scale.
     * Additionally, only suggestions that are {@link SpanSuggestion#isVisible() visible} are
     * taken into consideration.
     */
    public Map<Long, Delta<T>> getTopDeltas()
    {
        if (isEmpty()) {
            return emptyMap();
        }
        else if (size() == 1) {
            T top = get(0);
            if (top.isVisible()) {
                return singletonMap(top.getRecommenderId(), new Delta(top));
            }
            else {
                return emptyMap();
            }
        }
        else {
            // Group the suggestions by recommender because the confidence scores cannot be compared
            // across recommenders - note that the grouped lists are still sorted as the
            // we ensure that all the access methods (iterator, stream, etc) only return sorted
            // data.
            Map<Long, List<T>> predictionsByRecommenders = stream()
                    .collect(groupingBy(AnnotationSuggestion_ImplBase::getRecommenderId));

            Map<Long, Delta<T>> result = new HashMap<>();
            for (Entry<Long, List<T>> e : predictionsByRecommenders.entrySet()) {
                long recommenderId = e.getKey();
                // We consider only candidates that are visible - note that the filtered list is
                // still sorted
                List<T> visibleSuggestions = e.getValue().stream()
                        .filter(AnnotationSuggestion_ImplBase::isVisible)
                        .collect(toList());
                
                if (visibleSuggestions.isEmpty()) {
                    // If a recommender has no visible suggestions, we skip it - nothing to do here
                }
                else if (visibleSuggestions.size() == 1) {
                    // If there is only one visible suggestions, grab it to create the delta
                    result.put(recommenderId, new Delta(visibleSuggestions.get(0)));
                }
                else {
                    // Exploiting the fact that the filtered suggestions are still sorted, we just
                    // grab the first and second one to construct the delta
                    result.put(recommenderId,
                            new Delta(visibleSuggestions.get(0), visibleSuggestions.get(1)));
                }
            }
            
            return unmodifiableMap(result);
        }
    }

    @Override
    public boolean add(T aSuggestion)
    {
        boolean empty = isEmpty();
        
        // When we add the second element to the group, then it is probably no longer sorted
        if (!empty) {
            sorted = false;
        }
        
        // All suggestions in a group must come from the same document (because they must be
        // on the same position) and layer/feature
        if (!empty) {
            T representative = get(0);
            Validate.isTrue(
                    Objects.equals(representative.getPosition(), aSuggestion.getPosition()),
                    "All suggestions in a group must be at the same position: expected [%s] but got [%s]",
                    representative.getPosition(), aSuggestion.getPosition());
            Validate.isTrue(representative.getDocumentName().equals(aSuggestion.getDocumentName()),
                    "All suggestions in a group must come from the same document: expected [%s] but got [%s]",
                    representative.getDocumentName(), aSuggestion.getDocumentName());
            Validate.isTrue(representative.getLayerId() == aSuggestion.getLayerId(),
                    "All suggestions in a group must be on the same layer: expected [%d] but got [%d]",
                    representative.getLayerId(), aSuggestion.getLayerId());
            Validate.isTrue(representative.getFeature().equals(aSuggestion.getFeature()),
                    "All suggestions in a group must be for the same feature: expected [%s] but got [%s]",
                    representative.getFeature(), aSuggestion.getFeature());
        }
        
        // Cache information that must be consistent in the group when the first item is added
        if (empty) {
            position = aSuggestion.getPosition();
            feature = aSuggestion.getFeature();
            layerId = aSuggestion.getLayerId();
            documentName = aSuggestion.getDocumentName();
        }
        
        return suggestions.add(aSuggestion);
    }

    @Override
    public Iterator<T> iterator()
    {
        ensureSortedState();
        // Avoid changes to the group via the iterator since that might interfere with our sorting
        return unmodifiableIterator(suggestions.iterator());
    }
    
    @Override
    public boolean isEmpty()
    {
        return suggestions.isEmpty();
    }

    @Override
    public int size()
    {
        return suggestions.size();
    }

    public static <T extends AnnotationSuggestion_ImplBase> SuggestionGroupCollector<T> collector()
    {
        return new SuggestionGroupCollector<T>();
    }
    
    public static <T extends AnnotationSuggestion_ImplBase> Collection<SuggestionGroup<T>> group(
            Collection<T> aSuggestions)
    {
        SortedMap<GroupKey, SuggestionGroup<T>> grouped = aSuggestions.stream()
                .collect(groupingBy(GroupKey::new, 
                        TreeMap::new, 
                        SuggestionGroup.<T>collector()));
        return grouped.values();
    }

    private static class GroupKey
        implements Comparable<GroupKey>
    {
        private final Position position;
        private final String feature;
        private final long layerId;

        public GroupKey(AnnotationSuggestion_ImplBase aSuggestion)
        {
            super();
            position = aSuggestion.getPosition();
            feature = aSuggestion.getFeature();
            layerId = aSuggestion.getLayerId();
        }

        @Override
        public boolean equals(final Object other)
        {
            if (!(other instanceof GroupKey)) {
                return false;
            }
            GroupKey castOther = (GroupKey) other;
            return new EqualsBuilder().append(position, castOther.position)
                    .append(feature, castOther.feature).append(layerId, castOther.layerId)
                    .isEquals();
        }

        @Override
        public int hashCode()
        {
            return new HashCodeBuilder().append(position).append(position).append(feature)
                    .append(layerId).toHashCode();
        }

        @Override
        public int compareTo(final GroupKey other)
        {
            return new CompareToBuilder()
                    .append(layerId, other.layerId)
                    .append(feature, other.feature)
                    .append(position, other.position)
                    .toComparison();
        }
    }
    
    public static class Delta<T extends AnnotationSuggestion_ImplBase>
        implements Serializable
    {
        private static final long serialVersionUID = -4892325166786170047L;
        
        private final double delta;
        private final T first;
        private final T second;

        public Delta(T aFirst)
        {
            this(aFirst, null);
        }

        public Delta(T aFirst, T aSecond)
        {
            Validate.notNull(aFirst, "At least first item must be given to compute delta");

            first = aFirst;
            second = aSecond;

            if (second == null) {
                delta = Math.abs(aFirst.getConfidence());
            }
            else {
                delta = Math.abs(first.getConfidence() - second.getConfidence());
            }
        }

        public T getFirst()
        {
            return first;
        }

        public Optional<T> getSecond()
        {
            return Optional.ofNullable(second);
        }

        public double getDelta()
        {
            return delta;
        }
    }
    
    public static class SuggestionGroupCollector<T extends AnnotationSuggestion_ImplBase>
        implements Collector<T, SuggestionGroup<T>, SuggestionGroup<T>>
    {

        @Override
        public Supplier<SuggestionGroup<T>> supplier()
        {
            return SuggestionGroup::new;
        }

        @Override
        public BiConsumer<SuggestionGroup<T>, T> accumulator()
        {
            return SuggestionGroup::add;
        }

        @Override
        public BinaryOperator<SuggestionGroup<T>> combiner()
        {
            return (group1, group2) -> {
                group2.forEach(suggestion -> group1.add(suggestion));
                return group1;
            };
        }

        @Override
        public Function<SuggestionGroup<T>, SuggestionGroup<T>> finisher()
        {
            return Function.identity();
        }

        @Override
        public Set<Characteristics> characteristics()
        {
            return Collections.emptySet();
        }
    }
}
